function percentageIndex(value: number | null | undefined): number {
  const finite = typeof value === 'number' && Number.isFinite(value) ? value : 0;
  return Math.round(Math.max(0, Math.min(100, finite)));
}

/**
 * Maps arbitrary percentages to one of the CSP-safe utility classes generated by
 * tailwind.config.js. No style attribute or client-side class table is required.
 */
export function percentageWidthClass(value: number | null | undefined): string {
  return `lens-w-${percentageIndex(value)}`;
}

export function percentageLeftClass(value: number | null | undefined): string {
  return `lens-left-${percentageIndex(value)}`;
}

export function percentageHeightClass(value: number | null | undefined): string {
  return `lens-h-${percentageIndex(value)}`;
}
