import { normalizeChatText } from './chat-normalize';

type MenuFocus = { pattern: RegExp; title: string; guidance: string };

// Ringkasan yang dipilih per menu. Knowledge base lengkap tetap tersedia untuk teori
// pasar, tetapi blok ini memberi prioritas sempit agar jawaban fitur tidak melebar ke
// menu lain yang tidak ditanyakan pengguna.
const MENU_FOCUS: MenuFocus[] = [
  { pattern: /\b(intraday validation|intraday lab|lensintraday)\b/, title: 'Intraday Validation Lab', guidance: 'Jelaskan sebagai lab riset LensIntraday: posisi buka-tutup hari yang sama, horizon 15/30/60 menit dan EOD, net return setelah biaya, dan forward OOS terpisah dari T+20. Cara pakai: buka Admin → Intraday Validation Lab, pilih cohort/horizon yang tersedia, lalu baca sample/edge/net return/status OOS. Jangan menyamakannya dengan Calibration Lab LensScore.' },
  { pattern: /\b(tp\/?cl validation|tpcl validation|tp cl validation|validation lab tp|lab tp)\b/, title: 'TP/CL Validation Lab', guidance: 'Jelaskan bahwa lab menguji engine TP1/TP2/CL production (structure + Wilder ATR + tick IDX), termasuk ambiguity TP-vs-CL dalam bar yang sama. Ini bukan kalibrasi LensScore. Fokus cara pakai, outcome, expectancy, sample dan batas backtest.' },
  { pattern: /\b(calibration lab|lensradar calibration|kalibrasi lensscore|score calibration)\b/, title: 'LensRadar Calibration Lab', guidance: 'Jelaskan validasi bucket LensScore/T+20, sample, CI, reliability, Brier/ECE dan isotonic temporal train/test. Hasil lab tidak auto-adopt threshold/bobot dan tidak otomatis membuat advisory aktif.' },
  { pattern: /\b(fundamental backfill|backfill fundamental|pit fundamental|fundamental pit)\b/, title: 'Fundamental Backfill & PIT', guidance: 'Jelaskan point-in-time: observed_date = saat informasi tersedia. Cara pakai admin: upload/paste CSV → Dry Run → perbaiki invalid/PIT issue → Insert append-only. Jangan memakai current data sebagai pengganti histori.' },
  { pattern: /\b(financial integrity|adoption gate|macro pit|valuation inputs|bank fundamentals evidence|bank evidence)\b/, title: 'Financial Integrity & Evidence', guidance: 'Jelaskan evidence/provenance PIT dan adoption gate. Candidate macro/bank evidence bersifat research/data-only dan tidak auto-adopt ke valuation atau LensScore; perubahan production butuh model-version + tests + validation.' },
  { pattern: /\b(ownership flow validation|ownership validation)\b/, title: 'Ownership Flow Validation Lab', guidance: 'Jelaskan lab untuk coverage, freshness, distribusi delta foreign/local dan point-in-time gate sebelum label ownership dianggap tervalidasi. Ownership Flow bukan transaksi broker.' },
  { pattern: /\b(ownership flow|foreign ownership|kepemilikan asing|kepemilikan lokal)\b/, title: 'Ownership Flow', guidance: 'Jelaskan perubahan komposisi kepemilikan foreign/local antar snapshot, delta dan structural-break guard. Bukan broker flow, tidak boleh menyimpulkan broker tertentu membeli, dan saat ini tidak ikut LensScore.' },
  { pattern: /\b(broker summary|broker distribution|broker flow|broksum)\b/, title: 'Broker Summary / Distribution', guidance: 'Bedakan transaksi per kode broker dari Ownership Flow. Data import dapat berisi buy/sell value, volume/frequency; panel teknikal membaca periode import. Ingestion otomatis saat ini nonaktif dan data belum memengaruhi LensScore/advisory.' },
  { pattern: /\b(kesehatan operasional|operational health|scheduled jobs|cron jobs|job health)\b/, title: 'Kesehatan Operasional', guidance: 'Jelaskan menu admin untuk memantau cron, cache, database dan error provider/job terakhir. Gunakan status aktual bila tersedia; jangan menebak penyebab gangguan.' },
  { pattern: /\b(feedback lensai|lensai feedback)\b/, title: 'Feedback LensAI', guidance: 'Jelaskan quality loop admin: lihat 👍/👎, intent, prompt/jawaban dan prioritaskan routing/knowledge/regression test. Feedback tidak otomatis melatih atau mengubah model.' },
  { pattern: /\b(backtest)\b/, title: 'Backtest', guidance: 'Jelaskan fungsi → langkah pakai → metrik hasil → batasan. Builder filter: pilih preset/filter, modal, periode, tekan Backtest, lalu baca return/win rate/drawdown vs IHSG. Live Filter Check membaca kandidat saat ini. Backtest saham tunggal hanya replay candle: pilih ticker/periode, Backtest memuat, Start memutar, Stop menghentikan.' },
  { pattern: /\b(lensmarket|market pulse|ihsg|breadth|sektor)\b/, title: 'LensMarket', guidance: 'Fokus pada arah indeks, breadth, regime, dan sektor. Jelaskan data sesi terakhir jika pasar tidak reguler; jangan mengubahnya menjadi prediksi atau rekomendasi indeks.' },
  { pattern: /\b(breakout radar|opportunity scanner)\b/, title: 'Breakout Radar', guidance: 'Jelaskan sebagai tampilan LensRadar untuk kandidat breakout/opportunity dari scan eligibility. Daftar kosong bisa berarti memang tidak ada kandidat yang lolos; data bisa stale/sesi terakhir. Flow berbasis OHLCV adalah proksi, bukan broker/foreign flow resmi.' },
  { pattern: /\b(lensradar|lensscore|ai pick|scanner peluang)\b/, title: 'LensRadar', guidance: 'Jelaskan bahwa ini scanner universe likuid. Pengguna membaca skor/alasan lalu melanjutkan riset per emiten. Kategori dan signal model bukan rekomendasi transaksi otomatis.' },
  { pattern: /\b(lenstechnical|teknikal|rsi|macd|ema|sma|support|resistance)\b/, title: 'LensTechnical', guidance: 'Jelaskan cara pilih ticker dan membaca tren, momentum, volume, RSI/MACD/MA, support-resistance, serta TP/CL bila tersedia. Tegaskan indikator tidak otomatis menjadi keputusan beli/jual.' },
  { pattern: /\b(lensscanner|screener)\b/, title: 'LensScanner', guidance: 'Jelaskan pilihan profil risiko dan filter sektor/harga/market cap/likuiditas, lalu cara membaca daftar kandidat. Hasilnya adalah penyaringan, bukan rekomendasi beli.' },
  { pattern: /\b(compare|bandingkan)\b/, title: 'Compare', guidance: 'Jelaskan masukkan minimal dua ticker, pilih fokus fundamental/teknikal/valuasi, lalu bandingkan metrik sejenis. Jangan menentukan pemenang dari satu rasio saja.' },
  { pattern: /\b(lensfundamental|fundamental|roe|npm|per|pbv)\b/, title: 'LensFundamental', guidance: 'Fokus pada kualitas laba, pertumbuhan, leverage, arus kas, dan rasio sesuai sektor. Jelaskan istilah yang ditanya dalam bahasa praktis; angka emiten hanya dari data server.' },
  { pattern: /\b(valuation|valuasi|dcf|nilai wajar|nilai intrinsik|fair value)\b/, title: 'Valuation / DCF', guidance: 'Jelaskan fair value sebagai estimasi model dari asumsi/metode yang tersedia, bukan target harga pasti. Jika meminta nilai emiten, bacakan hasil dan asumsi aktual; jika meminta cara pakai, arahkan pilih ticker lalu baca nilai wajar dan margin of safety.' },
  { pattern: /\b(moat)\b/, title: 'Moat', guidance: 'Jelaskan Moat sebagai proksi ketahanan bisnis dari data fundamental, bukan rating kualitatif mutlak. Sebutkan faktor yang tersedia serta batas proksinya.' },
  { pattern: /\b(earnings|laporan keuangan|kuartal)\b/, title: 'Earnings', guidance: 'Jelaskan monitoring laporan/agenda earnings dan cara membaca periode, angka rilis, serta perubahan relevan. Jangan menyatakan beat/miss tanpa basis pembanding yang tersedia.' },
  { pattern: /\b(dividen|dividend|yield)\b/, title: 'Dividend', guidance: 'Jelaskan data dividen/yield/jadwal dan simulator arus kas. Dalam simulator, pengguna mengisi modal/target lalu membaca asumsi; yield tinggi tidak otomatis aman.' },
  { pattern: /\b(lenswatch|watchlist|akun demo|paper trading|portofolio|portfolio)\b/, title: 'Portfolio & Watchlist', guidance: 'Jelaskan LensWatch untuk ticker dan alert, serta Akun Demo untuk transaksi simulasi/P&L. Keduanya data pribadi sehingga perlu login; aplikasi tidak mengeksekusi order nyata.' },
  { pattern: /\b(risk matrix|risk calculator|position size|risk reward|risk\/reward)\b/, title: 'Risk', guidance: 'Risk Matrix untuk stress test portofolio; Risk Calculator untuk position sizing dan risk/reward. Jelaskan input modal, risiko, entry, stop, target, lalu hasilnya sebagai panduan risiko, bukan sinyal transaksi.' },
  { pattern: /\b(news|berita|sentimen|corporate calendar|kalender|macro|makro)\b/, title: 'Research', guidance: 'News & Sentiment adalah konteks berita/judul; Corporate Calendar adalah agenda event yang tersedia; Macro menghubungkan BI rate, inflasi, kurs, dan sektor. Jangan mengubah sentimen menjadi sebab-akibat atau kepastian harga.' },
  { pattern: /\b(transparansi|tentang|about|beranda|home|pattern|pola)\b/, title: 'Navigasi & Transparansi', guidance: 'Beranda adalah snapshot awal; Transparansi menjelaskan metodologi/validasi; Tentang menjelaskan prinsip produk; Pattern dibaca bersama tren, volume, dan risiko false breakout. Jawab fungsi menu yang ditanya saja.' },
];

export function getFocusedMenuKnowledge(prompt: string): string {
  const text = normalizeChatText(prompt);
  const focus = MENU_FOCUS.find((item) => item.pattern.test(text));
  return focus
    ? `## Fokus Menu Saat Ini — ${focus.title}\n${focus.guidance}\n- Jawab hanya bagian yang relevan dengan menu ini; jangan membuat tour seluruh aplikasi kecuali pengguna memintanya.`
    : '';
}
