import type { MenuUsageGuideProps } from './MenuUsageGuide';

type GuideCopy = Pick<MenuUsageGuideProps, 'whatItAnswers' | 'steps' | 'freeAccess' | 'afterSignup'>;

export const MENU_GUIDE_EN: Record<string, GuideCopy> = {
  'breakout-radar': { whatItAnswers: 'Which stocks have just broken through an important level today?', steps: ['Review the newest candidates first.', 'Check score, liquidity, freshness, and breakout evidence.', 'Treat the result as research, not an automatic buy signal.'] },
  backtest: { whatItAnswers: 'How would this strategy have performed historically?', steps: ['Set entry and exit rules and the date range.', 'Run the test and inspect the equity curve before summary metrics.', 'Check the trade count; a strong result from only a few trades is weak evidence.'] },
  fundamental: { whatItAnswers: 'Is the business behind this stock financially healthy?', steps: ['Enter a ticker to load its financial statements.', 'Review profitability and balance-sheet ratios first.', 'Compare quality with growth; rising profit and rising debt are not equivalent evidence.'] },
  macro: { whatItAnswers: 'Are Indonesian economic conditions supporting or pressuring equities?', steps: ['Review interest rates and inflation first.', 'Compare the latest direction with prior periods, not a single reading.', 'Use macro as context, not as a buy or sell signal.'] },
  dcf: { whatItAnswers: 'Is this stock cheap or expensive relative to estimated fair value?', steps: ['Fair value is derived from projected cash flow, not market price.', 'Review growth and discount-rate assumptions first.', 'Margin of safety is a valuation gap, not a guarantee.'] },
  technical: { whatItAnswers: 'What do technical, fundamental, and fund-flow data say about this stock?', steps: ['Start with the total 0–100 score.', 'Open Findings to understand the evidence behind the score.', 'Review Technical Consensus indicator by indicator.'] },
  calendar: { whatItAnswers: 'Which corporate actions are coming up for stocks you follow?', steps: ['Review dividend, shareholder-meeting, and earnings dates.', 'Check the cum-dividend date carefully.', 'Filter by event type when the list is crowded.'] },
  dashboard: { whatItAnswers: 'What is the complete technical picture for one stock?', steps: ['Enter a ticker, for example BBCA.', 'Read trend, momentum, and fund flow together.', 'Open the technical evidence behind each conclusion.'] },
  'market-pulse': { whatItAnswers: 'Which way is today’s market leaning, and which sectors are leading?', steps: ['Use the index row to identify today’s IHSG direction.', 'Use Sector Heatmap to compare leading and lagging sectors.', 'Use Market Breadth to see whether gains are broad or concentrated.'], freeAccess: 'today’s IHSG and market-index direction', afterSignup: 'strength across 11 sectors and market-wide advance/decline breadth' },
  screener: { whatItAnswers: 'Which stocks currently meet your technical criteria?', steps: ['Choose a risk profile and filters.', 'Sort candidates by the evidence most relevant to your thesis.', 'Open a ticker to validate the result before acting.'] },
  moat: { whatItAnswers: 'Does this company show evidence of a durable competitive advantage?', steps: ['Enter a ticker.', 'Review profitability durability and business quality.', 'Treat missing evidence as unknown, not automatically weak.'] },
  watchlist: { whatItAnswers: 'What has changed in the stocks you are monitoring?', steps: ['Add tickers you want to monitor.', 'Review alerts and material changes.', 'Reassess the thesis when invalidation conditions appear.'] },
  risk: { whatItAnswers: 'How severely could your portfolio be affected by a market decline?', steps: ['Review portfolio beta and concentration.', 'Run the available stress scenarios.', 'Reduce exposure when projected loss exceeds your risk budget.'] },
  'risk-calculator': { whatItAnswers: 'How many lots can you buy while keeping loss controlled?', steps: ['Enter capital, entry price, and stop-loss level.', 'Set the percentage of capital at risk per trade.', 'Use the resulting maximum position size and risk/reward ratio.'] },
  'ownership-flow': { whatItAnswers: 'How is institutional ownership changing in this stock?', steps: ['Select a ticker and period.', 'Review ownership changes and data coverage.', 'Use flow as supporting evidence, not standalone causation.'] },
  compare: { whatItAnswers: 'Which of these stocks is most attractive on comparable evidence?', steps: ['Add at least two stocks.', 'Compare each metric row side by side.', 'Read why each metric matters before choosing.'] },
  dividend: { whatItAnswers: 'How much dividend cash flow could the selected stock or portfolio generate?', steps: ['Choose a ticker or portfolio mode.', 'Review yield, payment assumptions, and history.', 'Do not treat historical dividends as guaranteed future payments.'] },
  earnings: { whatItAnswers: 'How are earnings and expectations changing for this company?', steps: ['Select a ticker.', 'Compare reported results with prior periods and expectations.', 'Separate one-off effects from operating trends.'] },
  news: { whatItAnswers: 'Which news is influencing the market today?', steps: ['Review the latest relevant headlines.', 'Check source and publication time.', 'Treat headline sentiment as context, not proven price causation.'] },
  portfolio: { whatItAnswers: 'What are your portfolio exposure, performance, and concentration risks?', steps: ['Record paper transactions accurately.', 'Review position weights and unrealized results.', 'Rebalance when concentration or risk exceeds your plan.'] },
};
