import { BarChart3, LoaderCircle, Play, RefreshCw } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { requestFeature } from '../api';

type Preset = { label: string; filters: string[] };
type Result = { returnPct?: number; ihsgReturnPct?: number; alphaPct?: number; winRatePct?: number; totalTrades?: number; maxDrawdownPct?: number; equityCurve?: number[]; ihsgCurve?: number[]; trades?: Array<{ entryDate?: string; date?: string; symbol?: string; buy?: number; sell?: number; pnlPct?: number }>; computedAt?: string; universe?: { eligible?: number; inCache?: number; excludedShortHistory?: number }; performance?: Record<string, number> ; message?: string };
const localPresets: Preset[] = [
  { label: 'Momentum Breakout', filters: ['EMA 20/50 Cross', 'Volume vs Avg 20D', 'RSI 14'] },
  { label: 'Breakout Volume', filters: ['Volume vs Avg 20D', 'MACD', 'SMA Score (5,10,20)'] },
  { label: 'Akumulasi (A/D Volume)', filters: ['Market Flow Index', 'Volume vs Avg 20D', 'Support & Resistance', 'MACD'] },
  { label: 'Trend Following Kuat', filters: ['MA Trend IDX (20,50,200)', 'EMA 20/50 Cross', 'SMA Score (5,10,20)', 'Volume vs Avg 20D'] },
  { label: 'Rebound Support', filters: ['RSI 14', 'Support & Resistance', 'Market Flow Index', 'Volatility (ATR 14)'] },
  { label: 'Buy on Weakness', filters: ['MA Trend IDX (20,50,200)', 'RSI 14', 'Support & Resistance'] },
];
const fmt = (value?: number, suffix = '%') => value == null || !Number.isFinite(value) ? '—' : `${value >= 0 ? '+' : ''}${value.toFixed(2)}${suffix}`;
function Curve({ equity = [], benchmark = [] }: { equity?: number[]; benchmark?: number[] }) {
  const values = [...equity, ...benchmark].filter(Number.isFinite); if (!values.length) return null;
  const min = Math.min(...values), max = Math.max(...values), span = max - min || 1;
  const points = (items: number[]) => items.map((v, i) => `${(i / Math.max(items.length - 1, 1)) * 100},${88 - ((v - min) / span) * 76}`).join(' ');
  return <div className="backtest-chart"><div className="backtest-chart-label"><span><i className="curve-equity" /> Strategi</span><span><i className="curve-index" /> IHSG</span></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Kurva ekuitas backtest"><polyline points={points(benchmark)} className="curve-index-line" /><polyline points={points(equity)} className="curve-equity-line" /></svg></div>;
}
export function BacktestWorkspace() {
  const [presets, setPresets] = useState<Preset[]>(localPresets); const [selected, setSelected] = useState(localPresets[0]); const [modal, setModal] = useState('10000000'); const [period, setPeriod] = useState('12'); const [result, setResult] = useState<Result | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => { void requestFeature('/api/backtest').then((payload) => { const received = (payload as { presets?: Preset[] }).presets; if (received?.length) { setPresets(received); setSelected(received[0]); } }).catch(() => undefined); }, []);
  const run = () => { setLoading(true); setError(''); void requestFeature('/api/backtest', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ filters: selected.filters, modal: Number(modal), period: Number(period) }) }).then((payload) => setResult(payload as Result)).catch((reason) => { setResult(null); setError(reason instanceof Error ? reason.message : 'Backtest belum dapat dijalankan.'); }).finally(() => setLoading(false)); };
  const metrics = useMemo(() => result ? [['Return strategi', fmt(result.returnPct)], ['Return IHSG', fmt(result.ihsgReturnPct)], ['Alpha', fmt(result.alphaPct)], ['Win rate', fmt(result.winRatePct)], ['Max drawdown', fmt(result.maxDrawdownPct)], ['Total trade', String(result.totalTrades ?? '—')]] : [], [result]);
  return <section className="backtest-workspace"><div className="tool-heading"><div><span className="section-kicker">BACKTEST HISTORIS</span><h2>Uji strategi dengan data SahamLens</h2><p>Hasil simulasi historis, bukan sinyal beli/jual. Sinyal dieksekusi pada pembukaan sesi berikutnya untuk menghindari look-ahead bias.</p></div><BarChart3 size={24} /></div><div className="backtest-presets">{presets.map((preset) => <button key={preset.label} className={selected.label === preset.label ? 'active' : ''} onClick={() => setSelected(preset)}>{preset.label}</button>)}</div><div className="backtest-controls"><label>Modal awal<input type="number" min="100000" step="100000" value={modal} onChange={(e) => setModal(e.target.value)} /></label><label>Periode<select value={period} onChange={(e) => setPeriod(e.target.value)}><option value="3">3 bulan</option><option value="6">6 bulan</option><option value="12">12 bulan</option><option value="24">24 bulan</option></select></label><button className="primary-action" onClick={run} disabled={loading}>{loading ? <LoaderCircle className="spin" size={15} /> : <Play size={15} />}{loading ? 'Menjalankan…' : 'Jalankan Backtest'}</button></div><div className="backtest-rules"><strong>Aturan strategi:</strong>{selected.filters.map((filter) => <span key={filter}>{filter}</span>)}</div>{error && <div className="stock-research-state error">{error}</div>}{result && <div className="backtest-result"><div className="backtest-metrics">{metrics.map(([label, value]) => <div key={label}><span>{label}</span><strong className={String(value).startsWith('+') ? 'positive' : String(value).startsWith('-') ? 'negative' : ''}>{value}</strong></div>)}</div><Curve equity={result.equityCurve} benchmark={result.ihsgCurve} /><div className="backtest-meta"><span>Universe layak: {result.universe?.eligible ?? '—'} / {result.universe?.inCache ?? '—'}</span><span>{result.computedAt ? `Dihitung ${new Date(result.computedAt).toLocaleString('id-ID')}` : 'Waktu hitung belum tersedia'}</span></div><h3>Riwayat trade</h3>{result.trades?.length ? <div className="backtest-trades">{result.trades.slice(0, 40).map((trade, index) => <div key={`${trade.symbol}-${trade.entryDate}-${index}`}><span>{trade.symbol?.replace('.JK', '') ?? '—'}</span><time>{trade.entryDate} → {trade.date}</time><span>Rp {trade.buy?.toLocaleString('id-ID') ?? '—'} → {trade.sell?.toLocaleString('id-ID') ?? '—'}</span><strong className={(trade.pnlPct ?? 0) >= 0 ? 'positive' : 'negative'}>{fmt(trade.pnlPct)}</strong></div>)}</div> : <p className="muted">Tidak ada trade yang memenuhi aturan pada periode ini.</p>}</div>}</section>;
}
