import { useEffect, useRef, useState } from 'react';
import { createChart, ColorType, CandlestickSeries, HistogramSeries, LineSeries, type IChartApi, type CandlestickData, type Time } from 'lightweight-charts';
import { ArrowDown, ArrowUp, Plus, X } from 'lucide-react';
import type { Ticker } from '../main';
import { getPublicChart } from '../api';
const ranges = ['1D', '3D', '7D', '1M', '3M', '1Y', '10Y', 'ALL'];
const indicators = ['EMA 20', 'EMA 50', 'EMA 200', 'Bollinger (20,2)', 'Volume', 'RSI 14', 'MACD', 'OBV', 'ATR 14', 'Stochastic', 'ADX 14', 'CMF 20', 'Williams %R'];
export function ChartPanel({ ticker }: { ticker?: Ticker }) {
  const chartElement = useRef<HTMLDivElement>(null); const chartRef = useRef<IChartApi | null>(null); const [range, setRange] = useState('1Y'); const [history, setHistory] = useState<Array<{ time: Time; open: number; high: number; low: number; close: number; volume: number }>>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(false); const [activeIndicators, setActiveIndicators] = useState<string[]>(['EMA 20', 'EMA 50', 'Volume']); const [indicatorOpen, setIndicatorOpen] = useState(false);
  useEffect(() => { if (!ticker) { setHistory([]); return; } let mounted = true; setLoading(true); setError(false); void getPublicChart(ticker.symbol, range).then((payload) => { if (mounted) setHistory(payload.history.map((item) => ({ ...item, time: item.time as Time, volume: Number(item.volume) || 0 }))); }).catch(() => { if (mounted) { setHistory([]); setError(true); } }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [ticker, range]);
  useEffect(() => { if (!chartElement.current || !ticker) return; const chart = createChart(chartElement.current, { autoSize: true, layout: { background: { type: ColorType.Solid, color: 'transparent' }, textColor: '#6f767d', fontFamily: 'Inter, sans-serif', fontSize: 10 }, grid: { vertLines: { color: '#1d2425' }, horzLines: { color: '#1d2425' } }, rightPriceScale: { borderColor: '#252c2d' }, timeScale: { borderColor: '#252c2d', timeVisible: true, secondsVisible: false } }); const series = chart.addSeries(CandlestickSeries, { upColor: '#22c55e', downColor: '#ef4444', borderVisible: false, wickUpColor: '#22c55e', wickDownColor: '#ef4444' }); const candles: CandlestickData<Time>[] = history.map(({ volume: _volume, ...bar }) => bar); if (candles.length) series.setData(candles); const closes = history.map((bar) => bar.close);
    const addLine = (values: Array<number | null>, color: string, title: string) => { const line = chart.addSeries(LineSeries, { color, lineWidth: 1, title, lastValueVisible: false, priceLineVisible: false }); line.setData(values.flatMap((value, index) => value == null ? [] : [{ time: history[index].time, value }])); };
    if (activeIndicators.includes('EMA 20')) addLine(ema(closes, 20), '#fbbf24', 'EMA 20'); if (activeIndicators.includes('EMA 50')) addLine(ema(closes, 50), '#60a5fa', 'EMA 50'); if (activeIndicators.includes('EMA 200')) addLine(ema(closes, 200), '#c084fc', 'EMA 200'); if (activeIndicators.includes('Bollinger (20,2)')) { const bands = bollinger(closes); addLine(bands.upper, '#94a3b8', 'BB atas'); addLine(bands.lower, '#94a3b8', 'BB bawah'); }
    if (activeIndicators.includes('Volume')) { const volume = chart.addSeries(HistogramSeries, { priceFormat: { type: 'volume' }, priceScaleId: '', lastValueVisible: false, priceLineVisible: false }); volume.setData(history.map((bar) => ({ time: bar.time, value: bar.volume, color: bar.close >= bar.open ? '#22c55e77' : '#ef444477' }))); volume.priceScale().applyOptions({ scaleMargins: { top: 0.76, bottom: 0 } }); }
    // Oscillator series are calculated from the same candle set; their latest reading is shown in the legend title.
    const oscillators: Record<string, [Array<number | null>, string]> = { 'RSI 14': [rsi(closes, 14), '#a78bfa'], 'MACD': [macd(closes), '#38bdf8'], 'OBV': [obv(history), '#f97316'], 'ATR 14': [atr(history, 14), '#fb7185'], 'Stochastic': [stochastic(history, 14), '#2dd4bf'], 'ADX 14': [adx(history, 14), '#eab308'], 'CMF 20': [cmf(history, 20), '#fb923c'], 'Williams %R': [williams(history, 14), '#818cf8'] }; Object.entries(oscillators).forEach(([name, [values, color]]) => { if (activeIndicators.includes(name)) addLine(values, color, name); });
    chart.timeScale().fitContent(); chartRef.current = chart; const resize = new ResizeObserver(() => chart.applyOptions({ width: chartElement.current?.clientWidth ?? 0, height: chartElement.current?.clientHeight ?? 0 })); resize.observe(chartElement.current); return () => { resize.disconnect(); chart.remove(); chartRef.current = null; }; }, [history, ticker, activeIndicators]);
  const up = (ticker?.change ?? 0) >= 0; const price = ticker?.price; return <section className="chart-section"><div className="instrument-header"><div className="instrument-title"><span className="instrument-logo">{ticker?.symbol.slice(0, 1) ?? '—'}</span><div><div className="symbol-line"><h1>{ticker?.symbol ?? 'Belum ada ticker'}</h1>{ticker && <><span className="exchange-tag">IDX</span><span className="market-open"><i /> DATA API</span></>}</div><p>{ticker?.name ?? 'Pilih saham dari daftar pantau untuk memuat data resmi'}</p></div></div>{ticker && <div className="ohlc-grid"><Stat label="HARGA" value={price != null ? `Rp ${price.toLocaleString('id-ID')}` : 'Belum tersedia'} /><Stat label="PERUBAHAN" value={ticker.change == null ? 'Belum tersedia' : `${up ? '+' : ''}${ticker.change.toFixed(2)}%`} tone={up ? 'positive' : 'negative'} /></div>}</div><div className="chart-toolbar"><div><strong>{price != null ? `Rp ${price.toLocaleString('id-ID')}` : '—'}</strong>{ticker && <span className={up ? 'positive' : 'negative'}>{up ? <ArrowUp size={12} /> : <ArrowDown size={12} />} {ticker.change == null ? 'Belum tersedia' : `${up ? '+' : ''}${ticker.change.toFixed(2)}%`}</span>}</div><div className="chart-tools"><div className="range-tabs">{ranges.map((item) => <button key={item} className={range === item ? 'active' : ''} onClick={() => setRange(item)}>{item === 'ALL' ? 'Max' : item}</button>)}</div><button className="indicator-button" onClick={() => setIndicatorOpen((value) => !value)}><Plus size={14} /> Indicators</button></div></div>{indicatorOpen && <div className="indicator-picker">{indicators.map((item) => <button key={item} className={activeIndicators.includes(item) ? 'active' : ''} onClick={() => setActiveIndicators((current) => current.includes(item) ? current.filter((value) => value !== item) : [...current, item])}>{item}</button>)}</div>}{activeIndicators.length > 0 && <div className="indicator-chips">{activeIndicators.map((item) => <span key={item}>{item}<button onClick={() => setActiveIndicators((current) => current.filter((value) => value !== item))} aria-label={`Hapus ${item}`}><X size={12} /></button></span>)}</div>}{!ticker ? <div className="chart-empty">Data chart akan tampil setelah saham dipilih.</div> : <div className="chart-canvas" ref={chartElement}>{loading && <div className="chart-overlay">Memuat data resmi…</div>}{error && <div className="chart-overlay">Data chart belum tersedia.</div>}{!loading && !error && !history.length && <div className="chart-overlay">Belum ada candle untuk rentang ini.</div>}</div>}<div className="chart-legend"><span><i className="legend-green" /> Harga</span><span>{ticker ? 'Sumber: API SahamLens' : 'Belum ada data'}</span></div></section>;
}
function Stat({ label, value, tone }: { label: string; value: string; tone?: string }) { return <div className="ohlc-stat"><span>{label}</span><strong className={tone}>{value}</strong></div>; }
function ema(values: number[], period: number) { let previous: number | null = null; const k = 2 / (period + 1); return values.map((value, index) => { if (index < period - 1) return null; if (previous == null) previous = values.slice(index - period + 1, index + 1).reduce((sum, item) => sum + item, 0) / period; else previous = value * k + previous * (1 - k); return previous; }); }
function bollinger(values: number[]) { const upper: Array<number | null> = [], lower: Array<number | null> = []; values.forEach((_, index) => { if (index < 19) { upper.push(null); lower.push(null); return; } const window = values.slice(index - 19, index + 1); const mean = window.reduce((sum, value) => sum + value, 0) / 20; const deviation = Math.sqrt(window.reduce((sum, value) => sum + (value - mean) ** 2, 0) / 20); upper.push(mean + 2 * deviation); lower.push(mean - 2 * deviation); }); return { upper, lower }; }
function rsi(values: number[], period: number) { let gain = 0, loss = 0; return values.map((value, index) => { if (!index) return null; const change = value - values[index - 1]; if (index <= period) { gain += Math.max(change, 0); loss += Math.max(-change, 0); if (index < period) return null; } else { gain = (gain * (period - 1) + Math.max(change, 0)) / period; loss = (loss * (period - 1) + Math.max(-change, 0)) / period; } return loss ? 100 - 100 / (1 + gain / loss) : 100; }); }
function macd(values: number[]) { const fast = ema(values, 12), slow = ema(values, 26); return values.map((_, index) => fast[index] == null || slow[index] == null ? null : fast[index]! - slow[index]!); }
type Bar = { high: number; low: number; close: number; volume: number };
function obv(bars: Bar[]) { let value = 0; return bars.map((bar, index) => { if (index) value += bar.close > bars[index - 1].close ? bar.volume : bar.close < bars[index - 1].close ? -bar.volume : 0; return value; }); }
function atr(bars: Bar[], period: number) { return bars.map((bar, index) => { if (!index || index < period) return null; const trs = bars.slice(index - period + 1, index + 1).map((item, i, list) => i ? Math.max(item.high - item.low, Math.abs(item.high - list[i - 1].close), Math.abs(item.low - list[i - 1].close)) : item.high - item.low); return trs.reduce((sum, value) => sum + value, 0) / period; }); }
function stochastic(bars: Bar[], period: number) { return bars.map((bar, index) => { if (index < period - 1) return null; const window = bars.slice(index - period + 1, index + 1); const high = Math.max(...window.map((item) => item.high)), low = Math.min(...window.map((item) => item.low)); return high === low ? 50 : ((bar.close - low) / (high - low)) * 100; }); }
function williams(bars: Bar[], period: number) { return bars.map((bar, index) => { if (index < period - 1) return null; const window = bars.slice(index - period + 1, index + 1); const high = Math.max(...window.map((item) => item.high)), low = Math.min(...window.map((item) => item.low)); return high === low ? -50 : ((high - bar.close) / (high - low)) * -100; }); }
function cmf(bars: Bar[], period: number) { return bars.map((_, index) => { if (index < period - 1) return null; const window = bars.slice(index - period + 1, index + 1); const numerator = window.reduce((sum, bar) => sum + (bar.high === bar.low ? 0 : ((2 * bar.close - bar.low - bar.high) / (bar.high - bar.low)) * bar.volume), 0); const denominator = window.reduce((sum, bar) => sum + bar.volume, 0); return denominator ? numerator / denominator : 0; }); }
function adx(bars: Bar[], period: number) { return bars.map((_, index) => { if (index < period * 2) return null; const window = bars.slice(index - period * 2 + 1, index + 1); let plus = 0, minus = 0, tr = 0; for (let i = 1; i < window.length; i++) { const up = window[i].high - window[i - 1].high, down = window[i - 1].low - window[i].low; plus += up > down && up > 0 ? up : 0; minus += down > up && down > 0 ? down : 0; tr += Math.max(window[i].high - window[i].low, Math.abs(window[i].high - window[i - 1].close), Math.abs(window[i].low - window[i - 1].close)); } const pdi = 100 * plus / (tr || 1), mdi = 100 * minus / (tr || 1); return 100 * Math.abs(pdi - mdi) / ((pdi + mdi) || 1); }); }
