import { useEffect, useRef, useState } from 'react';
import { createChart, ColorType, CandlestickSeries, type IChartApi, type CandlestickData, type Time } from 'lightweight-charts';
import { ArrowDown, ArrowUp, MoreHorizontal } from 'lucide-react';
import type { Ticker } from '../main';
import { getPublicChart } from '../api';
const ranges = ['1D', '1W', '1M', '3M', '1Y'];
export function ChartPanel({ ticker }: { ticker?: Ticker }) {
  const chartElement = useRef<HTMLDivElement>(null); const chartRef = useRef<IChartApi | null>(null); const [range, setRange] = useState('1D'); const [history, setHistory] = useState<CandlestickData<Time>[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState(false);
  useEffect(() => { if (!ticker) { setHistory([]); return; } let mounted = true; setLoading(true); setError(false); void getPublicChart(ticker.symbol, range).then((payload) => { if (mounted) setHistory(payload.history.map((item) => ({ time: item.time as Time, open: item.open, high: item.high, low: item.low, close: item.close }))); }).catch(() => { if (mounted) { setHistory([]); setError(true); } }).finally(() => { if (mounted) setLoading(false); }); return () => { mounted = false; }; }, [ticker, range]);
  useEffect(() => { if (!chartElement.current || !ticker) return; const chart = createChart(chartElement.current, { autoSize: true, layout: { background: { type: ColorType.Solid, color: 'transparent' }, textColor: '#6f767d', fontFamily: 'Inter, sans-serif', fontSize: 10 }, grid: { vertLines: { color: '#1d2425' }, horzLines: { color: '#1d2425' } }, rightPriceScale: { borderColor: '#252c2d' }, timeScale: { borderColor: '#252c2d', timeVisible: true, secondsVisible: false } }); const series = chart.addSeries(CandlestickSeries, { upColor: '#22c55e', downColor: '#ef4444', borderVisible: false, wickUpColor: '#22c55e', wickDownColor: '#ef4444' }); if (history.length) series.setData(history); chart.timeScale().fitContent(); chartRef.current = chart; const resize = new ResizeObserver(() => chart.applyOptions({ width: chartElement.current?.clientWidth ?? 0, height: chartElement.current?.clientHeight ?? 0 })); resize.observe(chartElement.current); return () => { resize.disconnect(); chart.remove(); chartRef.current = null; }; }, [history, ticker]);
  const up = (ticker?.change ?? 0) >= 0; const price = ticker?.price; return <section className="chart-section"><div className="instrument-header"><div className="instrument-title"><span className="instrument-logo">{ticker?.symbol.slice(0, 1) ?? '—'}</span><div><div className="symbol-line"><h1>{ticker?.symbol ?? 'Belum ada ticker'}</h1>{ticker && <><span className="exchange-tag">IDX</span><span className="market-open"><i /> DATA API</span></>}</div><p>{ticker?.name ?? 'Pilih saham dari daftar pantau untuk memuat data resmi'}</p></div></div>{ticker && <div className="ohlc-grid"><Stat label="HARGA" value={price != null ? `Rp ${price.toLocaleString('id-ID')}` : 'Belum tersedia'} /><Stat label="PERUBAHAN" value={ticker.change == null ? 'Belum tersedia' : `${up ? '+' : ''}${ticker.change.toFixed(2)}%`} tone={up ? 'positive' : 'negative'} /></div>}</div><div className="chart-toolbar"><div><strong>{price != null ? `Rp ${price.toLocaleString('id-ID')}` : '—'}</strong>{ticker && <span className={up ? 'positive' : 'negative'}>{up ? <ArrowUp size={12} /> : <ArrowDown size={12} />} {ticker.change == null ? 'Belum tersedia' : `${up ? '+' : ''}${ticker.change.toFixed(2)}%`}</span>}</div><div className="chart-tools"><div className="range-tabs">{ranges.map((item) => <button key={item} className={range === item ? 'active' : ''} onClick={() => setRange(item)}>{item}</button>)}</div><button className="more-button" aria-label="Opsi chart"><MoreHorizontal size={16} /></button></div></div>{!ticker ? <div className="chart-empty">Data chart akan tampil setelah saham dipilih.</div> : <div className="chart-canvas" ref={chartElement}>{loading && <div className="chart-overlay">Memuat data resmi…</div>}{error && <div className="chart-overlay">Data chart belum tersedia.</div>}{!loading && !error && !history.length && <div className="chart-overlay">Belum ada candle untuk rentang ini.</div>}</div>}<div className="chart-legend"><span><i className="legend-green" /> Harga</span><span>{ticker ? 'Sumber: API SahamLens' : 'Belum ada data'}</span></div></section>;
}
function Stat({ label, value, tone }: { label: string; value: string; tone?: string }) { return <div className="ohlc-stat"><span>{label}</span><strong className={tone}>{value}</strong></div>; }
