import { useEffect, useMemo, useState } from 'react';
import { AlertCircle, BadgeCheck, Building2, CalendarClock, LoaderCircle, Scale, ShieldCheck, Users } from 'lucide-react';
import { requestFeature } from '../api';

type Tab = 'overview' | 'fundamental' | 'dcf' | 'earnings' | 'ownership';
type Props = { tab: Tab; symbol?: string };
type RecordValue = Record<string, unknown>;

const paths: Record<Tab, (symbol: string) => string> = {
  overview: (symbol) => `/api/fundamental/${encodeURIComponent(symbol)}`,
  fundamental: (symbol) => `/api/fundamental/${encodeURIComponent(symbol)}`,
  dcf: (symbol) => `/api/dcf/${encodeURIComponent(symbol)}`,
  earnings: (symbol) => `/api/earnings/${encodeURIComponent(symbol)}`,
  ownership: (symbol) => `/api/ownership-flow/${encodeURIComponent(symbol)}`,
};

function asRecord(value: unknown): RecordValue { return value && typeof value === 'object' ? value as RecordValue : {}; }
function asNumber(value: unknown) { return typeof value === 'number' && Number.isFinite(value) ? value : null; }
function formatNumber(value: unknown) { const number = asNumber(value); return number == null ? '—' : number.toLocaleString('id-ID', { maximumFractionDigits: 2 }); }
function formatPercent(value: unknown, fraction = true) { const number = asNumber(value); return number == null ? '—' : `${(fraction ? number * 100 : number).toLocaleString('id-ID', { maximumFractionDigits: 2 })}%`; }
function formatIdr(value: unknown) { const number = asNumber(value); return number == null ? '—' : `Rp ${number.toLocaleString('id-ID', { maximumFractionDigits: 0 })}`; }
function Metric({ label, value, tone }: { label: string; value: string; tone?: 'positive' | 'negative' }) { return <div className="research-metric"><span>{label}</span><strong className={tone}>{value}</strong></div>; }

export function StockResearchWorkspace({ tab, symbol }: Props) {
  const [payload, setPayload] = useState<RecordValue | null>(null);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  useEffect(() => { if (!symbol) { setPayload(null); setError(''); return; } let active = true; setLoading(true); setError(''); void requestFeature(paths[tab](symbol)).then((data) => { if (active) setPayload(asRecord(data)); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : 'Data riset belum tersedia.'); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [symbol, tab]);
  const content = useMemo(() => { if (!payload) return null; if (tab === 'overview' || tab === 'fundamental') return <Fundamental data={payload} overview={tab === 'overview'} />; if (tab === 'dcf') return <Dcf data={payload} />; if (tab === 'earnings') return <Earnings data={payload} />; return <Ownership data={payload} />; }, [payload, tab]);
  return <section className="stock-research-workspace" aria-live="polite">{!symbol ? <Empty text="Cari atau pilih emiten untuk membuka riset berbasis data SahamLens." /> : loading ? <Empty loading text={`Memuat riset ${symbol}…`} /> : error ? <Empty error text={error} /> : content ?? <Empty text="Server belum mengembalikan data riset." />}</section>;
}

function Empty({ text, loading, error }: { text: string; loading?: boolean; error?: boolean }) { return <div className={`stock-research-state${error ? ' error' : ''}`}>{loading ? <LoaderCircle className="spin" size={19} /> : error ? <AlertCircle size={19} /> : <Building2 size={19} />}{text}</div>; }
function Fundamental({ data, overview }: { data: RecordValue; overview: boolean }) { const stock = asRecord(data.stock); const fundamentals = asRecord(data.fundamentals); const quality = asRecord(data.fundamentalQuality); const moat = asRecord(data.moatDurability); const consensus = typeof data.consensus === 'string' ? data.consensus : 'Kesimpulan belum tersedia.'; const source = asRecord(data.source); return <><div className="research-summary-card"><div><span>{overview ? 'RINGKASAN EMITEN' : 'KUALITAS FUNDAMENTAL'}</span><h2>{typeof stock.name === 'string' ? stock.name : typeof stock.symbol === 'string' ? stock.symbol : 'Emiten'}</h2><p>{consensus}</p></div><div className="research-score-badge"><span>{overview ? 'HARGA' : 'SKOR'}</span><strong>{overview ? formatIdr(stock.current_price) : quality.pct == null ? '—' : `${formatNumber(quality.pct)}%`}</strong><small>{overview ? formatPercent(stock.change_pct, false) : typeof quality.label === 'string' ? quality.label : 'Belum dinilai'}</small></div></div><div className="research-metrics-grid"><Metric label="P/E" value={asNumber(fundamentals.trailingPE) == null ? '—' : `${formatNumber(fundamentals.trailingPE)}x`} /><Metric label="PBV" value={asNumber(fundamentals.priceToBook) == null ? '—' : `${formatNumber(fundamentals.priceToBook)}x`} /><Metric label="ROE" value={formatPercent(fundamentals.returnOnEquity)} /><Metric label="DIVIDEN" value={formatPercent(fundamentals.dividendYield)} /></div><div className="research-evidence"><ShieldCheck size={17} /><div><strong>{typeof moat.status === 'string' ? `Moat: ${moat.status}` : 'Bukti fundamental'}</strong><p>{typeof moat.conclusion === 'string' ? moat.conclusion : 'Bukti dan keterbatasan tersedia dari server SahamLens.'}</p><small>Sumber: {typeof source.provider === 'string' ? source.provider : 'SahamLens'} · Data aktual, bukan estimasi UI.</small></div></div></>; }
function Dcf({ data }: { data: RecordValue }) { const stock = asRecord(data.stock); const quant = asRecord(data.quant); const analysis = asRecord(data.analysis); const unavailable = Boolean(quant.not_applicable); return <><div className="research-summary-card"><div><span>VALUASI</span><h2>{unavailable ? 'Model DCF tidak berlaku' : 'Valuasi Discounted Cash Flow'}</h2><p>{typeof analysis.executive_summary === 'string' ? analysis.executive_summary : 'Ringkasan valuasi belum tersedia.'}</p></div><Scale size={34} className="research-summary-icon" /></div>{unavailable ? <div className="research-evidence"><AlertCircle size={17} /><div><strong>Metode disesuaikan dengan sektor</strong><p>{typeof data.not_applicable_reason === 'string' ? `Alasan: ${data.not_applicable_reason}.` : 'Gunakan metode valuasi yang sesuai dengan karakter bisnis emiten.'}</p></div></div> : <div className="research-metrics-grid"><Metric label="HARGA SAAT INI" value={formatIdr(quant.current_price ?? stock.current_price)} /><Metric label="PROYEKSI FCF" value={Array.isArray(quant.fcf_projections) ? `${quant.fcf_projections.length} periode` : '—'} /><Metric label="DATA TERKUNCI" value={formatNumber(quant.fcf_locked_count)} /><Metric label="SENSITIVITAS" value={Array.isArray(quant.sensitivity_table) ? `${quant.sensitivity_table.length} skenario` : '—'} /></div>}</>; }
function Earnings({ data }: { data: RecordValue }) { const stock = asRecord(data.stock); const upcoming = asRecord(data.upcoming); const expectation = asRecord(data.expectation); const eps = asRecord(expectation.eps); const revenue = asRecord(expectation.revenue); const latest = asRecord(data.latestFundamentals); return <><div className="research-summary-card"><div><span>EARNINGS</span><h2>{typeof stock.name === 'string' ? stock.name : 'Jadwal dan ekspektasi earnings'}</h2><p>{typeof upcoming.date === 'string' ? `Perkiraan laporan berikutnya: ${new Date(upcoming.date).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' })}.` : 'Jadwal earnings belum tersedia.'}</p></div><CalendarClock size={34} className="research-summary-icon" /></div><div className="research-metrics-grid"><Metric label="EPS ESTIMASI" value={formatNumber(eps.average)} /><Metric label="PERTUMBUHAN EPS" value={formatPercent(eps.growth)} tone={asNumber(eps.growth) != null && asNumber(eps.growth)! >= 0 ? 'positive' : 'negative'} /><Metric label="REVENUE ESTIMASI" value={formatIdr(revenue.average)} /><Metric label="GROWTH REVENUE" value={formatPercent(revenue.growth)} tone={asNumber(revenue.growth) != null && asNumber(revenue.growth)! >= 0 ? 'positive' : 'negative'} /></div><div className="research-evidence"><BadgeCheck size={17} /><div><strong>Fundamental terakhir</strong><p>Margin laba {formatPercent(latest.profitMargin)} · pertumbuhan laba {formatPercent(latest.earningsGrowth)}.</p><small>Estimate dan aktual dibedakan oleh API SahamLens.</small></div></div></>; }
function Ownership({ data }: { data: RecordValue }) { const delta = asRecord(data.delta); const previous = asRecord(data.previous); const foreign = asNumber(data.foreignPct); const foreignDelta = asNumber(delta['30d']); return <><div className="research-summary-card"><div><span>OWNERSHIP FLOW</span><h2>{typeof data.ticker === 'string' ? data.ticker : 'Komposisi kepemilikan'}</h2><p>{typeof data.trendReason === 'string' ? data.trendReason : 'Komposisi kepemilikan berdasarkan data KSEI.'}</p></div><Users size={34} className="research-summary-icon" /></div><div className="research-metrics-grid"><Metric label="ASING" value={formatPercent(foreign, false)} /><Metric label="LOKAL" value={formatPercent(data.localPct, false)} /><Metric label="Δ 30 HARI" value={foreignDelta == null ? '—' : `${foreignDelta >= 0 ? '+' : ''}${formatPercent(foreignDelta, false)} pp`} tone={foreignDelta != null && foreignDelta >= 0 ? 'positive' : 'negative'} /><Metric label="FRESHNESS" value={typeof data.freshness === 'string' ? data.freshness : '—'} /></div><div className="research-evidence"><ShieldCheck size={17} /><div><strong>Basis observasi</strong><p>{typeof data.observedDate === 'string' ? `Data per ${data.observedDate}.` : 'Tanggal observasi belum tersedia.'} {Boolean(previous.structuralBreak) ? 'Ada perubahan struktural pada basis pembanding.' : 'Basis pembanding konsisten.'}</p><small>Cadence: {typeof data.cadence === 'string' ? data.cadence : '—'} · Sumber: {typeof data.source === 'string' ? data.source : 'SahamLens'}.</small></div></div></>; }
