export const TICKERS = [
  { symbol: '^JKSE', name: 'Indeks Harga Saham Gabungan (IHSG)' },
  { symbol: 'IHSG', name: 'Indeks Harga Saham Gabungan (^JKSE Composite Index)' },
  { symbol: 'AADI.JK', name: 'Adaro Andalan Indonesia Tbk.' },
  { symbol: 'AALI.JK', name: 'Astra Agro Lestari Tbk.' },
  { symbol: 'ABBA.JK', name: 'Mahaka Media Tbk.' },
  { symbol: 'ABDA.JK', name: 'Asuransi Bina Dana Arta Tbk.' },
  { symbol: 'ABMM.JK', name: 'ABM Investama Tbk.' },
  { symbol: 'ACES.JK', name: 'Aspirasi Hidup Indonesia Tbk.' },
  { symbol: 'ACRO.JK', name: 'Samcro Hyosung Adilestari Tbk.' },
  { symbol: 'ACST.JK', name: 'Acset Indonusa Tbk.' },
  { symbol: 'ADCP.JK', name: 'Adhi Commuter Properti Tbk.' },
  { symbol: 'ADES.JK', name: 'Akasha Wira International Tbk.' },
  { symbol: 'ADHI.JK', name: 'Adhi Karya (Persero) Tbk.' },
  { symbol: 'ADMF.JK', name: 'Adira Dinamika Multi Finance T' },
  { symbol: 'ADMG.JK', name: 'Polychem Indonesia Tbk' },
  { symbol: 'ADMR.JK', name: 'Alamtri Minerals Indonesia Tbk' },
  { symbol: 'ADRO.JK', name: 'Alamtri Resources Indonesia Tb' },
  { symbol: 'AEGS.JK', name: 'Anugerah Spareparts Sejahtera' },
  { symbol: 'AGAR.JK', name: 'Asia Sejahtera Mina Tbk.' },
  { symbol: 'AGII.JK', name: 'Samator Indo Gas Tbk.' },
  { symbol: 'AGRO.JK', name: 'Bank Raya Indonesia Tbk.' },
  { symbol: 'AGRS.JK', name: 'Bank IBK Indonesia Tbk.' },
  { symbol: 'AHAP.JK', name: 'Asuransi Harta Aman Pratama Tb' },
  { symbol: 'AIMS.JK', name: 'Artha Mahiya Investama Tbk.' },
  { symbol: 'AISA.JK', name: 'FKS Food Sejahtera Tbk.' },
  { symbol: 'AKKU.JK', name: 'Anugerah Kagum Karya Utama Tbk' },
  { symbol: 'AKPI.JK', name: 'Argha Karya Prima Industry Tbk' },
  { symbol: 'AKRA.JK', name: 'AKR Corporindo Tbk.' },
  { symbol: 'AKSI.JK', name: 'Mineral Sumberdaya Mandiri Tbk' },
  { symbol: 'ALDO.JK', name: 'Alkindo Naratama Tbk.' },
  { symbol: 'ALII.JK', name: 'Ancara Logistics Indonesia Tbk' },
  { symbol: 'ALKA.JK', name: 'Alakasa Industrindo Tbk' },
  { symbol: 'ALMI.JK', name: 'Alumindo Light Metal Industry' },
  { symbol: 'ALTO.JK', name: 'Tri Banyan Tirta Tbk.' },
  { symbol: 'AMAG.JK', name: 'Asuransi Multi Artha Guna Tbk.' },
  { symbol: 'AMAN.JK', name: 'Makmur Berkah Amanda Tbk.' },
  { symbol: 'AMAR.JK', name: 'Bank Amar Indonesia Tbk.' },
  { symbol: 'AMFG.JK', name: 'Asahimas Flat Glass Tbk.' },
  { symbol: 'AMIN.JK', name: 'Ateliers Mecaniques D Indonesi' },
  { symbol: 'AMMN.JK', name: 'Amman Mineral Internasional Tb' },
  { symbol: 'AMMS.JK', name: 'Agung Menjangan Mas Tbk.' },
  { symbol: 'AMOR.JK', name: 'Ashmore Asset Management Indon' },
  { symbol: 'AMRT.JK', name: 'Sumber Alfaria Trijaya Tbk.' },
  { symbol: 'ANDI.JK', name: 'Andira Agro Tbk.' },
  { symbol: 'ANJT.JK', name: 'Austindo Nusantara Jaya Tbk.' },
  { symbol: 'ANTM.JK', name: 'ANTAM (Persero) Tbk.' },
  { symbol: 'APEX.JK', name: 'Apexindo Pratama Duta Tbk.' },
  { symbol: 'APIC.JK', name: 'Pacific Strategic Financial Tb' },
  { symbol: 'APII.JK', name: 'Arita Prima Indonesia Tbk.' },
  { symbol: 'APLI.JK', name: 'Asiaplast Industries Tbk.' },
  { symbol: 'APLN.JK', name: 'Agung Podomoro Land Tbk.' },
  { symbol: 'ARCI.JK', name: 'Archi Indonesia Tbk.' },
  { symbol: 'AREA.JK', name: 'Dunia Virtual Online Tbk.' },
  { symbol: 'ARGO.JK', name: 'Argo Pantes Tbk' },
  { symbol: 'ARII.JK', name: 'Atlas Resources Tbk.' },
  { symbol: 'ARKA.JK', name: 'Arkha Jayanti Persada Tbk.' },
  { symbol: 'ARKO.JK', name: 'Arkora Hydro Tbk.' },
  { symbol: 'ARMY.JK', name: 'Armidian Karyatama Tbk.' },
  { symbol: 'ARNA.JK', name: 'Arwana Citramulia Tbk.' },
  { symbol: 'ARTA.JK', name: 'Arthavest Tbk' },
  { symbol: 'ARTI.JK', name: 'Ratu Prabu Energi Tbk' },
  { symbol: 'ARTO.JK', name: 'Bank Jago Tbk.' },
  { symbol: 'ASBI.JK', name: 'Asuransi Bintang Tbk.' },
  { symbol: 'ASDM.JK', name: 'Asuransi Dayin Mitra Tbk.' },
  { symbol: 'ASGR.JK', name: 'Astra Graphia Tbk.' },
  { symbol: 'ASHA.JK', name: 'Cilacap Samudera Fishing Indus' },
  { symbol: 'ASII.JK', name: 'Astra International Tbk.' },
  { symbol: 'ASJT.JK', name: 'Asuransi Jasa Tania Tbk.' },
  { symbol: 'ASLC.JK', name: 'Autopedia Sukses Lestari Tbk.' },
  { symbol: 'ASLI.JK', name: 'Asri Karya Lestari Tbk.' },
  { symbol: 'ASMI.JK', name: 'Asuransi Maximus Graha Persada' },
  { symbol: 'ASPI.JK', name: 'Andalan Sakti Primaindo Tbk.' },
  { symbol: 'ASPR.JK', name: 'Asia Pramulia Tbk.' },
  { symbol: 'ASRI.JK', name: 'Alam Sutera Realty Tbk.' },
  { symbol: 'ASRM.JK', name: 'Asuransi Ramayana Tbk.' },
  { symbol: 'ASSA.JK', name: 'Adi Sarana Armada Tbk.' },
  { symbol: 'ATAP.JK', name: 'Trimitra Prawara Goldland Tbk.' },
  { symbol: 'ATIC.JK', name: 'Anabatic Technologies Tbk.' },
  { symbol: 'ATLA.JK', name: 'Atlantis Subsea Indonesia Tbk.' },
  { symbol: 'AUTO.JK', name: 'Astra Otoparts Tbk.' },
  { symbol: 'AVIA.JK', name: 'Avia Avian Tbk.' },
  { symbol: 'AWAN.JK', name: 'Era Digital Media Tbk.' },
  { symbol: 'AXIO.JK', name: 'Tera Data Indonusa Tbk.' },
  { symbol: 'AYAM.JK', name: 'Janu Putra Sejahtera Tbk.' },
  { symbol: 'AYLS.JK', name: 'Arkayana Lestari Grup Tbk.' },
  { symbol: 'BABP.JK', name: 'Bank MNC Internasional Tbk.' },
  { symbol: 'BABY.JK', name: 'Multitrend Indo Tbk.' },
  { symbol: 'BACA.JK', name: 'Bank Capital Indonesia Tbk.' },
  { symbol: 'BACH.JK', name: 'Bach Multi Global Tbk.' },
  { symbol: 'BAIK.JK', name: 'Bersama Mencapai Puncak Tbk.' },
  { symbol: 'BAJA.JK', name: 'Saranacentral Bajatama Tbk.' },
  { symbol: 'BALI.JK', name: 'Bali Towerindo Sentra Tbk.' },
  { symbol: 'BANK.JK', name: 'Bank Aladin Syariah Tbk.' },
  { symbol: 'BAPA.JK', name: 'Bekasi Asri Pemula Tbk.' },
  { symbol: 'BAPI.JK', name: 'Bhakti Agung Propertindo Tbk.' },
  { symbol: 'BATA.JK', name: 'Sepatu Bata Tbk.' },
  { symbol: 'BATR.JK', name: 'Benteng Api Technic Tbk.' },
  { symbol: 'BAUT.JK', name: 'Mitra Angkasa Sejahtera Tbk.' },
  { symbol: 'BAYU.JK', name: 'Bayu Buana Tbk' },
  { symbol: 'BBCA.JK', name: 'Bank Central Asia Tbk.' },
  { symbol: 'BBHI.JK', name: 'Allo Bank Indonesia Tbk.' },
  { symbol: 'BBKP.JK', name: 'Bank KB Indonesia Tbk.' },
  { symbol: 'BBLD.JK', name: 'Buana Finance Tbk.' },
  { symbol: 'BBMD.JK', name: 'Bank Mestika Dharma Tbk.' },
  { symbol: 'BBNI.JK', name: 'Bank Negara Indonesia (Persero' },
  { symbol: 'BBRI.JK', name: 'Bank Rakyat Indonesia (Persero' },
  { symbol: 'BBRM.JK', name: 'Pelayaran Nasional Bina Buana' },
  { symbol: 'BBSI.JK', name: 'Krom Bank Indonesia Tbk.' },
  { symbol: 'BBSS.JK', name: 'Bumi Benowo Sukses Sejahtera T' },
  { symbol: 'BBTN.JK', name: 'Bank Tabungan Negara (Persero)' },
  { symbol: 'BBYB.JK', name: 'Bank Neo Commerce Tbk.' },
  { symbol: 'BCAP.JK', name: 'MNC Kapital Indonesia Tbk.' },
  { symbol: 'BCIC.JK', name: 'Bank JTrust Indonesia Tbk.' },
  { symbol: 'BCIP.JK', name: 'Bumi Citra Permai Tbk.' },
  { symbol: 'BDKR.JK', name: 'Berdikari Pondasi Perkasa Tbk.' },
  { symbol: 'BDMN.JK', name: 'Bank Danamon Indonesia Tbk.' },
  { symbol: 'BEBS.JK', name: 'Berkah Beton Sadaya Tbk.' },
  { symbol: 'BEEF.JK', name: 'Estika Tata Tiara Tbk.' },
  { symbol: 'BEER.JK', name: 'Jobubu Jarum Minahasa Tbk.' },
  { symbol: 'BEKS.JK', name: 'Bank Pembangunan Daerah Banten' },
  { symbol: 'BELI.JK', name: 'Global Digital Niaga Tbk.' },
  { symbol: 'BELL.JK', name: 'Trisula Textile Industries Tbk' },
  { symbol: 'BESS.JK', name: 'Batulicin Nusantara Maritim Tb' },
  { symbol: 'BEST.JK', name: 'Bekasi Fajar Industrial Estate' },
  { symbol: 'BFIN.JK', name: 'BFI Finance  Indonesia Tbk.' },
  { symbol: 'BGTG.JK', name: 'Bank Ganesha Tbk.' },
  { symbol: 'BHAT.JK', name: 'Bhakti Multi Artha Tbk.' },
  { symbol: 'BHIT.JK', name: 'MNC Asia Holding Tbk.' },
  { symbol: 'BIKA.JK', name: 'Binakarya Jaya Abadi Tbk.' },
  { symbol: 'BIKE.JK', name: 'Bhineka Inovasi Ketahanan Ener' },
  { symbol: 'BIMA.JK', name: 'Primarindo Asia Infrastructure' },
  { symbol: 'BINA.JK', name: 'Bank Ina Perdana Tbk.' },
  { symbol: 'BINO.JK', name: 'Perma Plasindo Tbk.' },
  { symbol: 'BIPI.JK', name: 'Astrindo Nusantara Infrastrukt' },
  { symbol: 'BIPP.JK', name: 'Bhuwanatala Indah Permai Tbk.' },
  { symbol: 'BIRD.JK', name: 'Blue Bird Tbk.' },
  { symbol: 'BISI.JK', name: 'BISI International Tbk.' },
  { symbol: 'BJBR.JK', name: 'Bank Pembangunan Daerah Jawa B' },
  { symbol: 'BJTM.JK', name: 'Bank Pembangunan Daerah Jawa T' },
  { symbol: 'BKDP.JK', name: 'Bukit Darmo Property Tbk' },
  { symbol: 'BKSL.JK', name: 'Sentul City Tbk.' },
  { symbol: 'BKSW.JK', name: 'Bank QNB Indonesia Tbk.' },
  { symbol: 'BLES.JK', name: 'Superior Prima Sukses Tbk.' },
  { symbol: 'BLOG.JK', name: 'Trimitra Trans Persada Tbk.' },
  { symbol: 'BLTA.JK', name: 'Berlian Laju Tanker Tbk' },
  { symbol: 'BLTZ.JK', name: 'Graha Layar Prima Tbk.' },
  { symbol: 'BLUE.JK', name: 'Berkah Prima Perkasa Tbk.' },
  { symbol: 'BMAS.JK', name: 'Bank Kasikorn Indonesia Tbk.' },
  { symbol: 'BMBL.JK', name: 'Lavender Bina Cendikia Tbk.' },
  { symbol: 'BMHS.JK', name: 'Bundamedik Tbk.' },
  { symbol: 'BMRI.JK', name: 'Bank Mandiri (Persero) Tbk.' },
  { symbol: 'BMSR.JK', name: 'Bintang Mitra Semestaraya Tbk' },
  { symbol: 'BMTR.JK', name: 'Global Mediacom Tbk.' },
  { symbol: 'BNBA.JK', name: 'Bank Bumi Arta Tbk.' },
  { symbol: 'BNBR.JK', name: 'Bakrie & Brothers Tbk' },
  { symbol: 'BNGA.JK', name: 'Bank CIMB Niaga Tbk.' },
  { symbol: 'BNII.JK', name: 'Bank Maybank Indonesia Tbk.' },
  { symbol: 'BNLI.JK', name: 'Bank Permata Tbk.' },
  { symbol: 'BOAT.JK', name: 'Newport Marine Services Tbk.' },
  { symbol: 'BOBA.JK', name: 'Formosa Ingredient Factory Tbk' },
  { symbol: 'BOGA.JK', name: 'Apollo Global Interactive Tbk.' },
  { symbol: 'BOLA.JK', name: 'Bali Bintang Sejahtera Tbk.' },
  { symbol: 'BOLT.JK', name: 'Garuda Metalindo Tbk.' },
  { symbol: 'BOSS.JK', name: 'Borneo Olah Sarana Sukses Tbk.' },
  { symbol: 'BPFI.JK', name: 'Woori Finance Indonesia Tbk.' },
  { symbol: 'BPII.JK', name: 'Batavia Prosperindo Internasio' },
  { symbol: 'BPTR.JK', name: 'Batavia Prosperindo Trans Tbk.' },
  { symbol: 'BRAM.JK', name: 'Indo Kordsa Tbk.' },
  { symbol: 'BREN.JK', name: 'Barito Renewables Energy Tbk.' },
  { symbol: 'BRIS.JK', name: 'Bank Syariah Indonesia (Perser' },
  { symbol: 'BRMS.JK', name: 'Bumi Resources Minerals Tbk.' },
  { symbol: 'BRNA.JK', name: 'Berlina Tbk.' },
  { symbol: 'BRPT.JK', name: 'Barito Pacific Tbk.' },
  { symbol: 'BRRC.JK', name: 'Raja Roti Cemerlang Tbk.' },
  { symbol: 'BSBK.JK', name: 'Wulandari Bangun Laksana Tbk.' },
  { symbol: 'BSDE.JK', name: 'Bumi Serpong Damai Tbk.' },
  { symbol: 'BSIM.JK', name: 'Bank Sinarmas Tbk.' },
  { symbol: 'BSML.JK', name: 'Bintang Samudera Mandiri Lines' },
  { symbol: 'BSSR.JK', name: 'Baramulti Suksessarana Tbk.' },
  { symbol: 'BSWD.JK', name: 'Bank Of India Indonesia Tbk.' },
  { symbol: 'BTEK.JK', name: 'Bumi Teknokultura Unggul Tbk' },
  { symbol: 'BTEL.JK', name: 'Bakrie Telecom Tbk.' },
  { symbol: 'BTON.JK', name: 'Betonjaya Manunggal Tbk.' },
  { symbol: 'BTPN.JK', name: 'Bank SMBC Indonesia Tbk.' },
  { symbol: 'BTPS.JK', name: 'Bank BTPN Syariah Tbk.' },
  { symbol: 'BUAH.JK', name: 'Segar Kumala Indonesia Tbk.' },
  { symbol: 'BUDI.JK', name: 'Budi Starch & Sweetener Tbk.' },
  { symbol: 'BUKA.JK', name: 'Bukalapak.com Tbk.' },
  { symbol: 'BUKK.JK', name: 'Bukaka Teknik Utama Tbk.' },
  { symbol: 'BULL.JK', name: 'Buana Lintas Lautan Tbk.' },
  { symbol: 'BUMI.JK', name: 'Bumi Resources Tbk.' },
  { symbol: 'BUVA.JK', name: 'Bukit Uluwatu Villa Tbk.' },
  { symbol: 'BVIC.JK', name: 'Bank Victoria International Tb' },
  { symbol: 'BWPT.JK', name: 'Eagle High Plantations Tbk.' },
  { symbol: 'BYAN.JK', name: 'Bayan Resources Tbk.' },
  { symbol: 'CAKK.JK', name: 'Cahayaputra Asa Keramik Tbk.' },
  { symbol: 'CAMP.JK', name: 'Campina Ice Cream Industry Tbk' },
  { symbol: 'CANI.JK', name: 'Capitol Nusantara Indonesia Tb' },
  { symbol: 'CARE.JK', name: 'Metro Healthcare Indonesia Tbk' },
  { symbol: 'CARS.JK', name: 'Industri dan Perdagangan Bintr' },
  { symbol: 'CASA.JK', name: 'Capital Financial Indonesia Tb' },
  { symbol: 'CASH.JK', name: 'Cashlez Worldwide Indonesia Tb' },
  { symbol: 'CASS.JK', name: 'Cahaya Aero Services Tbk.' },
  { symbol: 'CBDK.JK', name: 'Bangun Kosambi Sukses Tbk.' },
  { symbol: 'CBMF.JK', name: 'Cahaya Bintang Medan Tbk.' },
  { symbol: 'CBPE.JK', name: 'Citra Buana Prasida Tbk.' },
  { symbol: 'CBRE.JK', name: 'Cakra Buana Resources Energi T' },
  { symbol: 'CBUT.JK', name: 'Citra Borneo Utama Tbk.' },
  { symbol: 'CCSI.JK', name: 'Communication Cable Systems In' },
  { symbol: 'CDIA.JK', name: 'Chandra Daya Investasi Tbk.' },
  { symbol: 'CEKA.JK', name: 'Wilmar Cahaya Indonesia Tbk.' },
  { symbol: 'CENT.JK', name: 'Centratama Telekomunikasi Indo' },
  { symbol: 'CFIN.JK', name: 'Clipan Finance Indonesia Tbk.' },
  { symbol: 'CGAS.JK', name: 'Citra Nusantara Gemilang Tbk.' },
  { symbol: 'CHEK.JK', name: 'Diastika Biotekindo Tbk.' },
  { symbol: 'CHEM.JK', name: 'Chemstar Indonesia Tbk.' },
  { symbol: 'CHIP.JK', name: 'Pelita Teknologi Global Tbk.' },
  { symbol: 'CINT.JK', name: 'Chitose Internasional Tbk.' },
  { symbol: 'CITA.JK', name: 'Cita Mineral Investindo Tbk.' },
  { symbol: 'CITY.JK', name: 'Natura City Developments Tbk.' },
  { symbol: 'CLAY.JK', name: 'Citra Putra Realty Tbk.' },
  { symbol: 'CLEO.JK', name: 'Sariguna Primatirta Tbk.' },
  { symbol: 'CLPI.JK', name: 'Colorpak Indonesia Tbk.' },
  { symbol: 'CMNP.JK', name: 'Citra Marga Nusaphala Persada' },
  { symbol: 'CMNT.JK', name: 'Cemindo Gemilang Tbk.' },
  { symbol: 'CMPP.JK', name: 'AirAsia Indonesia Tbk.' },
  { symbol: 'CMRY.JK', name: 'Cisarua Mountain Dairy Tbk.' },
  { symbol: 'CNKO.JK', name: 'Exploitasi Energi Indonesia Tb' },
  { symbol: 'CNMA.JK', name: 'Nusantara Sejahtera Raya Tbk.' },
  { symbol: 'COAL.JK', name: 'Black Diamond Resources Tbk.' },
  { symbol: 'COCO.JK', name: 'Wahana Interfood Nusantara Tbk' },
  { symbol: 'COIN.JK', name: 'Indokripto Koin Semesta Tbk.' },
  { symbol: 'COWL.JK', name: 'Cowell Development Tbk.' },
  { symbol: 'CPIN.JK', name: 'Charoen Pokphand Indonesia Tbk' },
  { symbol: 'CPRI.JK', name: 'Capri Nusa Satu Properti Tbk.' },
  { symbol: 'CPRO.JK', name: 'Central Proteina Prima Tbk.' },
  { symbol: 'CRAB.JK', name: 'Toba Surimi Industries Tbk.' },
  { symbol: 'CRSN.JK', name: 'Carsurin Tbk.' },
  { symbol: 'CSAP.JK', name: 'Catur Sentosa Adiprana Tbk.' },
  { symbol: 'CSIS.JK', name: 'Cahayasakti Investindo Sukses' },
  { symbol: 'CSMI.JK', name: 'Cipta Selera Murni Tbk.' },
  { symbol: 'CSRA.JK', name: 'Cisadane Sawit Raya Tbk.' },
  { symbol: 'CTBN.JK', name: 'Citra Tubindo Tbk.' },
  { symbol: 'CTRA.JK', name: 'Ciputra Development Tbk.' },
  { symbol: 'CTTH.JK', name: 'Citatah Tbk.' },
  { symbol: 'CUAN.JK', name: 'Petrindo Jaya Kreasi Tbk.' },
  { symbol: 'CYBR.JK', name: 'ITSEC Asia Tbk.' },
  { symbol: 'DAAZ.JK', name: 'Daaz Bara Lestari Tbk.' },
  { symbol: 'DADA.JK', name: 'Diamond Citra Propertindo Tbk.' },
  { symbol: 'DART.JK', name: 'Duta Anggada Realty Tbk.' },
  { symbol: 'DATA.JK', name: 'Remala Abadi Tbk.' },
  { symbol: 'DAYA.JK', name: 'Duta Intidaya Tbk.' },
  { symbol: 'DCII.JK', name: 'DCI Indonesia Tbk.' },
  { symbol: 'DEAL.JK', name: 'Dewata Freightinternational Tb' },
  { symbol: 'DEFI.JK', name: 'Danasupra Erapacific Tbk.' },
  { symbol: 'DEPO.JK', name: 'Caturkarda Depo Bangunan Tbk.' },
  { symbol: 'DEWA.JK', name: 'Darma Henwa Tbk' },
  { symbol: 'DEWI.JK', name: 'Dewi Shri Farmindo Tbk.' },
  { symbol: 'DFAM.JK', name: 'Dafam Property Indonesia Tbk.' },
  { symbol: 'DGIK.JK', name: 'Nusa Konstruksi Enjiniring Tbk' },
  { symbol: 'DGNS.JK', name: 'Diagnos Laboratorium Utama Tbk' },
  { symbol: 'DGWG.JK', name: 'Delta Giri Wacana Tbk.' },
  { symbol: 'DIGI.JK', name: 'Arkadia Digital Media Tbk.' },
  { symbol: 'DILD.JK', name: 'Intiland Development Tbk.' },
  { symbol: 'DIVA.JK', name: 'Distribusi Voucher Nusantara T' },
  { symbol: 'DKFT.JK', name: 'Central Omega Resources Tbk.' },
  { symbol: 'DKHH.JK', name: 'Cipta Sarana Medika Tbk.' },
  { symbol: 'DLTA.JK', name: 'Delta Djakarta Tbk.' },
  { symbol: 'DMAS.JK', name: 'Puradelta Lestari Tbk.' },
  { symbol: 'DMMX.JK', name: 'Digital Mediatama Maxima Tbk.' },
  { symbol: 'DMND.JK', name: 'Diamond Food Indonesia Tbk.' },
  { symbol: 'DNAR.JK', name: 'Bank Oke Indonesia Tbk.' },
  { symbol: 'DNET.JK', name: 'Indoritel Makmur Internasional' },
  { symbol: 'DOID.JK', name: 'BUMA Internasional Grup Tbk.' },
  { symbol: 'DOOH.JK', name: 'Era Media Sejahtera Tbk.' },
  { symbol: 'DOSS.JK', name: 'Global Sukses Digital Tbk.' },
  { symbol: 'DPNS.JK', name: 'Duta Pertiwi Nusantara Tbk.' },
  { symbol: 'DPUM.JK', name: 'Dua Putra Utama Makmur Tbk.' },
  { symbol: 'DRMA.JK', name: 'Dharma Polimetal Tbk.' },
  { symbol: 'DSFI.JK', name: 'Dharma Samudera Fishing Indust' },
  { symbol: 'DSNG.JK', name: 'Dharma Satya Nusantara Tbk.' },
  { symbol: 'DSSA.JK', name: 'Dian Swastatika Sentosa Tbk' },
  { symbol: 'DUCK.JK', name: 'Jaya Bersama Indo Tbk.' },
  { symbol: 'DUTI.JK', name: 'Duta Pertiwi Tbk' },
  { symbol: 'DVLA.JK', name: 'Darya-Varia Laboratoria Tbk.' },
  { symbol: 'DWGL.JK', name: 'Dwi Guna Laksana Tbk.' },
  { symbol: 'DYAN.JK', name: 'Dyandra Media International Tb' },
  { symbol: 'EAST.JK', name: 'Eastparc Hotel Tbk.' },
  { symbol: 'ECII.JK', name: 'Electronic City Indonesia Tbk.' },
  { symbol: 'EDGE.JK', name: 'Indointernet Tbk.' },
  { symbol: 'EKAD.JK', name: 'Ekadharma International Tbk.' },
  { symbol: 'ELIT.JK', name: 'Data Sinergitama Jaya Tbk.' },
  { symbol: 'ELPI.JK', name: 'Pelayaran Nasional Ekalya Purn' },
  { symbol: 'ELSA.JK', name: 'Elnusa Tbk.' },
  { symbol: 'ELTY.JK', name: 'Bakrieland Development Tbk.' },
  { symbol: 'EMAS.JK', name: 'Merdeka Gold Resources Tbk.' },
  { symbol: 'EMDE.JK', name: 'Megapolitan Developments Tbk.' },
  { symbol: 'EMMI.JK', name: 'Esa Medika Mandiri Tbk.' },
  { symbol: 'EMTK.JK', name: 'Elang Mahkota Teknologi Tbk.' },
  { symbol: 'ENAK.JK', name: 'Champ Resto Indonesia Tbk.' },
  { symbol: 'ENRG.JK', name: 'Energi Mega Persada Tbk.' },
  { symbol: 'ENVY.JK', name: 'Envy Technologies Indonesia Tb' },
  { symbol: 'ENZO.JK', name: 'Morenzo Abadi Perkasa Tbk.' },
  { symbol: 'EPAC.JK', name: 'Megalestari Epack Sentosaraya' },
  { symbol: 'EPMT.JK', name: 'Enseval Putera Megatrading Tbk' },
  { symbol: 'ERAA.JK', name: 'Erajaya Swasembada Tbk.' },
  { symbol: 'ERAL.JK', name: 'Sinar Eka Selaras Tbk.' },
  { symbol: 'ERTX.JK', name: 'Eratex Djaja Tbk.' },
  { symbol: 'ESIP.JK', name: 'Sinergi Inti Plastindo Tbk.' },
  { symbol: 'ESSA.JK', name: 'ESSA Industries Indonesia Tbk.' },
  { symbol: 'ESTA.JK', name: 'Esta Multi Usaha Tbk.' },
  { symbol: 'ESTI.JK', name: 'Ever Shine Tex Tbk.' },
  { symbol: 'ETWA.JK', name: 'Eterindo Wahanatama Tbk' },
  { symbol: 'EURO.JK', name: 'Estee Gold Feet Tbk.' },
  { symbol: 'EXCL.JK', name: 'XLSMART Telecom Sejahtera Tbk.' },
  { symbol: 'FAPA.JK', name: 'FAP Agri Tbk.' },
  { symbol: 'FAST.JK', name: 'Fast Food Indonesia Tbk.' },
  { symbol: 'FASW.JK', name: 'Fajar Surya Wisesa Tbk.' },
  { symbol: 'FILM.JK', name: 'MD Entertainment Tbk.' },
  { symbol: 'FIMP.JK', name: 'Fimperkasa Utama Tbk.' },
  { symbol: 'FIRE.JK', name: 'Alfa Energi Investama Tbk.' },
  { symbol: 'FISH.JK', name: 'FKS Multi Agro Tbk.' },
  { symbol: 'FITT.JK', name: 'Hotel Fitra International Tbk.' },
  { symbol: 'FLMC.JK', name: 'Falmaco Nonwoven Industri Tbk.' },
  { symbol: 'FMII.JK', name: 'Fortune Mate Indonesia Tbk' },
  { symbol: 'FOLK.JK', name: 'Multi Garam Utama Tbk.' },
  { symbol: 'FOOD.JK', name: 'Sentra Food Indonesia Tbk.' },
  { symbol: 'FORE.JK', name: 'Fore Kopi Indonesia Tbk.' },
  { symbol: 'FORU.JK', name: 'Fortune Indonesia Tbk' },
  { symbol: 'FPNI.JK', name: 'Lotte Chemical Titan Tbk.' },
  { symbol: 'FUJI.JK', name: 'Fuji Finance Indonesia Tbk.' },
  { symbol: 'FUTR.JK', name: 'Futura Energi Global Tbk.' },
  { symbol: 'FWCT.JK', name: 'Wijaya Cahaya Timber Tbk.' },
  { symbol: 'GAMA.JK', name: 'Aksara Global Development Tbk.' },
  { symbol: 'GDST.JK', name: 'Gunawan Dianjaya Steel Tbk.' },
  { symbol: 'GDYR.JK', name: 'Goodyear Indonesia Tbk.' },
  { symbol: 'GEMA.JK', name: 'Gema Grahasarana Tbk.' },
  { symbol: 'GEMS.JK', name: 'Golden Energy Mines Tbk.' },
  { symbol: 'GGRM.JK', name: 'Gudang Garam Tbk.' },
  { symbol: 'GGRP.JK', name: 'Gunung Raja Paksi Tbk.' },
  { symbol: 'GHON.JK', name: 'Gihon Telekomunikasi Indonesia' },
  { symbol: 'GIAA.JK', name: 'Garuda Indonesia (Persero) Tbk' },
  { symbol: 'GJTL.JK', name: 'Gajah Tunggal Tbk.' },
  { symbol: 'GLOB.JK', name: 'Globe Kita Terang Tbk.' },
  { symbol: 'GLVA.JK', name: 'Galva Technologies Tbk.' },
  { symbol: 'GMFI.JK', name: 'Garuda Maintenance Facility Ae' },
  { symbol: 'GMTD.JK', name: 'Gowa Makassar Tourism Developm' },
  { symbol: 'GOLD.JK', name: 'Visi Telekomunikasi Infrastruk' },
  { symbol: 'GOLF.JK', name: 'Intra Golflink Resorts Tbk.' },
  { symbol: 'GOLL.JK', name: 'Golden Plantation Tbk.' },
  { symbol: 'GOOD.JK', name: 'Garudafood Putra Putri Jaya Tb' },
  { symbol: 'GOTO.JK', name: 'GoTo Gojek Tokopedia Tbk.' },
  { symbol: 'GPRA.JK', name: 'Perdana Gapuraprima Tbk.' },
  { symbol: 'GPSO.JK', name: 'Geoprima Solusi Tbk.' },
  { symbol: 'GRIA.JK', name: 'Ingria Pratama Capitalindo Tbk' },
  { symbol: 'GRPH.JK', name: 'Griptha Putra Persada Tbk.' },
  { symbol: 'GRPM.JK', name: 'Graha Prima Mentari Tbk.' },
  { symbol: 'GSMF.JK', name: 'Equity Development Investment' },
  { symbol: 'GTBO.JK', name: 'Garda Tujuh Buana Tbk' },
  { symbol: 'GTRA.JK', name: 'Grahaprima Suksesmandiri Tbk.' },
  { symbol: 'GTSI.JK', name: 'GTS Internasional Tbk.' },
  { symbol: 'GULA.JK', name: 'Aman Agrindo Tbk.' },
  { symbol: 'GUNA.JK', name: 'Gunanusa Eramandiri Tbk.' },
  { symbol: 'GWSA.JK', name: 'Greenwood Sejahtera Tbk.' },
  { symbol: 'GZCO.JK', name: 'Gozco Plantations Tbk.' },
  { symbol: 'HADE.JK', name: 'Himalaya Energi Perkasa Tbk.' },
  { symbol: 'HAIS.JK', name: 'Hasnur Internasional Shipping' },
  { symbol: 'HAJJ.JK', name: 'Arsy Buana Travelindo Tbk.' },
  { symbol: 'HALO.JK', name: 'Haloni Jane Tbk.' },
  { symbol: 'HATM.JK', name: 'Habco Trans Maritima Tbk.' },
  { symbol: 'HBAT.JK', name: 'Minahasa Membangun Hebat Tbk.' },
  { symbol: 'HDFA.JK', name: 'Radana Bhaskara Finance Tbk.' },
  { symbol: 'HDIT.JK', name: 'Hensel Davest Indonesia Tbk.' },
  { symbol: 'HEAL.JK', name: 'Medikaloka Hermina Tbk.' },
  { symbol: 'HELI.JK', name: 'Jaya Trishindo Tbk.' },
  { symbol: 'HERO.JK', name: 'DFI Retail Nusantara Tbk.' },
  { symbol: 'HEXA.JK', name: 'Hexindo Adiperkasa Tbk.' },
  { symbol: 'HGII.JK', name: 'Hero Global Investment Tbk.' },
  { symbol: 'HILL.JK', name: 'Hillcon Tbk.' },
  { symbol: 'HITS.JK', name: 'Humpuss Intermoda Transportasi' },
  { symbol: 'HKMU.JK', name: 'HK Metals Utama Tbk.' },
  { symbol: 'HMSP.JK', name: 'H.M. Sampoerna Tbk.' },
  { symbol: 'HOKI.JK', name: 'Buyung Poetra Sembada Tbk.' },
  { symbol: 'HOME.JK', name: 'Hotel Mandarine Regency Tbk.' },
  { symbol: 'HOMI.JK', name: 'Grand House Mulia Tbk.' },
  { symbol: 'HOPE.JK', name: 'Harapan Duta Pertiwi Tbk.' },
  { symbol: 'HOTL.JK', name: 'Saraswati Griya Lestari Tbk.' },
  { symbol: 'HRME.JK', name: 'Menteng Heritage Realty Tbk.' },
  { symbol: 'HRTA.JK', name: 'Hartadinata Abadi Tbk.' },
  { symbol: 'HRUM.JK', name: 'Harum Energy Tbk.' },
  { symbol: 'HUMI.JK', name: 'Humpuss Maritim Internasional' },
  { symbol: 'HYGN.JK', name: 'Ecocare Indo Pasifik Tbk.' },
  { symbol: 'IATA.JK', name: 'Karya Pacific Energy Tbk.' },
  { symbol: 'IBFN.JK', name: 'Intan Baru Prana Tbk.' },
  { symbol: 'IBOS.JK', name: 'Indo Boga Sukses Tbk.' },
  { symbol: 'IBST.JK', name: 'Inti Bangun Sejahtera Tbk.' },
  { symbol: 'ICBP.JK', name: 'Indofood CBP Sukses Makmur Tbk' },
  { symbol: 'ICON.JK', name: 'Island Concepts Indonesia Tbk.' },
  { symbol: 'IDEA.JK', name: 'Idea Indonesia Akademi Tbk.' },
  { symbol: 'IDPR.JK', name: 'Indonesia Pondasi Raya Tbk.' },
  { symbol: 'IFII.JK', name: 'Indonesia Fibreboard Industry' },
  { symbol: 'IFSH.JK', name: 'Ifishdeco Tbk.' },
  { symbol: 'IGAR.JK', name: 'Champion Pacific Indonesia Tbk' },
  { symbol: 'IIKP.JK', name: 'Inti Agri Resources Tbk' },
  { symbol: 'IKAI.JK', name: 'Intikeramik Alamasri Industri' },
  { symbol: 'IKAN.JK', name: 'Era Mandiri Cemerlang Tbk.' },
  { symbol: 'IKBI.JK', name: 'Sumi Indo Kabel Tbk.' },
  { symbol: 'IKPM.JK', name: 'Ikapharmindo Putramas Tbk.' },
  { symbol: 'IMAS.JK', name: 'Indomobil Sukses Internasional' },
  { symbol: 'IMJS.JK', name: 'Indomobil Multi Jasa Tbk.' },
  { symbol: 'IMPC.JK', name: 'Impack Pratama Industri Tbk.' },
  { symbol: 'INAF.JK', name: 'Indofarma Tbk.' },
  { symbol: 'INAI.JK', name: 'Indal Aluminium Industry Tbk.' },
  { symbol: 'INCF.JK', name: 'Indo Komoditi Korpora Tbk.' },
  { symbol: 'INCI.JK', name: 'Intanwijaya Internasional Tbk' },
  { symbol: 'INCO.JK', name: 'Vale Indonesia Tbk.' },
  { symbol: 'INDF.JK', name: 'Indofood Sukses Makmur Tbk.' },
  { symbol: 'INDO.JK', name: 'Royalindo Investa Wijaya Tbk.' },
  { symbol: 'INDR.JK', name: 'Indo-Rama Synthetics Tbk.' },
  { symbol: 'INDS.JK', name: 'Indospring Tbk.' },
  { symbol: 'INDX.JK', name: 'Tanah Laut Tbk' },
  { symbol: 'INDY.JK', name: 'Indika Energy Tbk.' },
  { symbol: 'INET.JK', name: 'Sinergi Inti Andalan Prima Tbk' },
  { symbol: 'INKP.JK', name: 'Indah Kiat Pulp & Paper Tbk.' },
  { symbol: 'INOV.JK', name: 'Inocycle Technology Group Tbk.' },
  { symbol: 'INPC.JK', name: 'Bank Artha Graha Internasional' },
  { symbol: 'INPP.JK', name: 'Indonesian Paradise Property T' },
  { symbol: 'INPS.JK', name: 'Indah Prakasa Sentosa Tbk.' },
  { symbol: 'INRU.JK', name: 'Toba Pulp Lestari Tbk.' },
  { symbol: 'INTA.JK', name: 'Intraco Penta Tbk.' },
  { symbol: 'INTD.JK', name: 'Inter Delta Tbk' },
  { symbol: 'INTP.JK', name: 'Indocement Tunggal Prakarsa Tb' },
  { symbol: 'IOTF.JK', name: 'Sumber Sinergi Makmur Tbk.' },
  { symbol: 'IPAC.JK', name: 'Era Graharealty Tbk.' },
  { symbol: 'IPCC.JK', name: 'Indonesia Kendaraan Terminal T' },
  { symbol: 'IPCM.JK', name: 'Jasa Armada Indonesia Tbk.' },
  { symbol: 'IPOL.JK', name: 'Indopoly Swakarsa Industry Tbk' },
  { symbol: 'IPPE.JK', name: 'Indo Pureco Pratama Tbk.' },
  { symbol: 'IPTV.JK', name: 'MNC Vision Networks Tbk.' },
  { symbol: 'IRRA.JK', name: 'Itama Ranoraya Tbk.' },
  { symbol: 'IRSX.JK', name: 'Folago Global Nusantara Tbk.' },
  { symbol: 'ISAP.JK', name: 'Isra Presisi Indonesia Tbk.' },
  { symbol: 'ISAT.JK', name: 'Indosat Tbk.' },
  { symbol: 'ISEA.JK', name: 'Indo American Seafoods Tbk.' },
  { symbol: 'ISSP.JK', name: 'Steel Pipe Industry of Indones' },
  { symbol: 'ITIC.JK', name: 'Indonesian Tobacco Tbk.' },
  { symbol: 'ITMA.JK', name: 'Sumber Energi Andalan Tbk.' },
  { symbol: 'ITMG.JK', name: 'Indo Tambangraya Megah Tbk.' },
  { symbol: 'JARR.JK', name: 'Jhonlin Agro Raya Tbk.' },
  { symbol: 'JAST.JK', name: 'Jasnita Telekomindo Tbk.' },
  { symbol: 'JATI.JK', name: 'Informasi Teknologi Indonesia' },
  { symbol: 'JAWA.JK', name: 'Jaya Agra Wattie Tbk.' },
  { symbol: 'JAYA.JK', name: 'Armada Berjaya Trans Tbk.' },
  { symbol: 'JECC.JK', name: 'Jembo Cable Company Tbk.' },
  { symbol: 'JECX.JK', name: 'Nitrasanata Dharma Tbk.' },
  { symbol: 'JELI.JK', name: 'Niramas Utama Tbk.' },
  { symbol: 'JGLE.JK', name: 'Graha Andrasentra Propertindo' },
  { symbol: 'JIHD.JK', name: 'Jakarta International Hotels &' },
  { symbol: 'JKON.JK', name: 'Jaya Konstruksi Manggala Prata' },
  { symbol: 'JMAS.JK', name: 'Asuransi Jiwa Syariah Jasa Mit' },
  { symbol: 'JPFA.JK', name: 'Japfa Comfeed Indonesia Tbk.' },
  { symbol: 'JRPT.JK', name: 'Jaya Real Property Tbk.' },
  { symbol: 'JSKY.JK', name: 'Sky Energy Indonesia Tbk.' },
  { symbol: 'JSMR.JK', name: 'Jasa Marga (Persero) Tbk.' },
  { symbol: 'JSPT.JK', name: 'Jakarta Setiabudi Internasiona' },
  { symbol: 'JTPE.JK', name: 'Jasuindo Tiga Perkasa Tbk.' },
  { symbol: 'KAEF.JK', name: 'Kimia Farma (Persero) Tbk.' },
  { symbol: 'KAQI.JK', name: 'Jantra Grupo Indonesia Tbk.' },
  { symbol: 'KARW.JK', name: 'Meratus Jasa Prima Tbk.' },
  { symbol: 'KAYU.JK', name: 'Darmi Bersaudara Tbk.' },
  { symbol: 'KBAG.JK', name: 'Karya Bersama Anugerah Tbk.' },
  { symbol: 'KBLI.JK', name: 'KMI Wire & Cable Tbk.' },
  { symbol: 'KBLM.JK', name: 'Kabelindo Murni Tbk.' },
  { symbol: 'KBLV.JK', name: 'First Media Tbk.' },
  { symbol: 'KBRI.JK', name: 'Kertas Basuki Rachmat Indonesi' },
  { symbol: 'KDSI.JK', name: 'Kedawung Setia Industrial Tbk.' },
  { symbol: 'KDTN.JK', name: 'Puri Sentul Permai Tbk.' },
  { symbol: 'KEEN.JK', name: 'Kencana Energi Lestari Tbk.' },
  { symbol: 'KEJU.JK', name: 'Mulia Boga Raya Tbk.' },
  { symbol: 'KETR.JK', name: 'Ketrosden Triasmitra Tbk.' },
  { symbol: 'KIAS.JK', name: 'Keramika Indonesia Assosiasi T' },
  { symbol: 'KICI.JK', name: 'Kedaung Indah Can Tbk' },
  { symbol: 'KIJA.JK', name: 'Kawasan Industri Jababeka Tbk.' },
  { symbol: 'KING.JK', name: 'Hoffmen Cleanindo Tbk.' },
  { symbol: 'KINO.JK', name: 'Kino Indonesia Tbk.' },
  { symbol: 'KIOS.JK', name: 'Kioson Komersial Indonesia Tbk' },
  { symbol: 'KJEN.JK', name: 'Krida Jaringan Nusantara Tbk.' },
  { symbol: 'KKES.JK', name: 'Kusuma Kemindo Sentosa Tbk.' },
  { symbol: 'KKGI.JK', name: 'Resource Alam Indonesia Tbk.' },
  { symbol: 'KLAS.JK', name: 'Pelayaran Kurnia Lautan Semest' },
  { symbol: 'KLBF.JK', name: 'Kalbe Farma Tbk.' },
  { symbol: 'KLIN.JK', name: 'Klinko Karya Imaji Tbk.' },
  { symbol: 'KMDS.JK', name: 'Kurniamitra Duta Sentosa Tbk.' },
  { symbol: 'KMTR.JK', name: 'Kirana Megatara Tbk.' },
  { symbol: 'KOBX.JK', name: 'Kobexindo Tractors Tbk.' },
  { symbol: 'KOCI.JK', name: 'Kokoh Exa Nusantara Tbk.' },
  { symbol: 'KOIN.JK', name: 'Kokoh Inti Arebama Tbk' },
  { symbol: 'KOKA.JK', name: 'Koka Indonesia Tbk.' },
  { symbol: 'KONI.JK', name: 'Perdana Bangun Pusaka Tbk' },
  { symbol: 'KOPI.JK', name: 'Mitra Energi Persada Tbk.' },
  { symbol: 'KOTA.JK', name: 'DMS Propertindo Tbk.' },
  { symbol: 'KPIG.JK', name: 'MNC Tourism Indonesia Tbk.' },
  { symbol: 'KRAS.JK', name: 'Krakatau Steel (Persero) Tbk.' },
  { symbol: 'KREN.JK', name: 'Quantum Clovera Investama Tbk.' },
  { symbol: 'KRYA.JK', name: 'Bangun Karya Perkasa Jaya Tbk.' },
  { symbol: 'KSIX.JK', name: 'Kentanix Supra International T' },
  { symbol: 'KUAS.JK', name: 'Ace Oldfields Tbk.' },
  { symbol: 'LABA.JK', name: 'Green Power Group Tbk.' },
  { symbol: 'LABS.JK', name: 'UBC Medical Indonesia Tbk.' },
  { symbol: 'LAJU.JK', name: 'Jasa Berdikari Logistics Tbk.' },
  { symbol: 'LAND.JK', name: 'Trimitra Propertindo Tbk.' },
  { symbol: 'LAPD.JK', name: 'Leyand International Tbk.' },
  { symbol: 'LCGP.JK', name: 'Eureka Prima Jakarta Tbk.' },
  { symbol: 'LCKM.JK', name: 'LCK Global Kedaton Tbk.' },
  { symbol: 'LEAD.JK', name: 'Logindo Samudramakmur Tbk.' },
  { symbol: 'LFLO.JK', name: 'Imago Mulia Persada Tbk.' },
  { symbol: 'LIFE.JK', name: 'MSIG Life Insurance Indonesia' },
  { symbol: 'LINK.JK', name: 'Link Net Tbk.' },
  { symbol: 'LION.JK', name: 'Lion Metal Works Tbk.' },
  { symbol: 'LIVE.JK', name: 'Homeco Victoria Makmur Tbk.' },
  { symbol: 'LMAS.JK', name: 'Limas Indonesia Makmur Tbk' },
  { symbol: 'LMAX.JK', name: 'Lupromax Pelumas Indonesia Tbk' },
  { symbol: 'LMPI.JK', name: 'Langgeng Makmur Industri Tbk.' },
  { symbol: 'LMSH.JK', name: 'Lionmesh Prima Tbk.' },
  { symbol: 'LOPI.JK', name: 'Logisticsplus International Tb' },
  { symbol: 'LPCK.JK', name: 'Lippo Cikarang Tbk' },
  { symbol: 'LPGI.JK', name: 'Lippo General Insurance Tbk.' },
  { symbol: 'LPIN.JK', name: 'Multi Prima Sejahtera Tbk' },
  { symbol: 'LPKR.JK', name: 'Lippo Karawaci Tbk.' },
  { symbol: 'LPLI.JK', name: 'Star Pacific Tbk' },
  { symbol: 'LPPF.JK', name: 'MDS Retailing Tbk.' },
  { symbol: 'LPPS.JK', name: 'Lenox Pasifik Investama Tbk.' },
  { symbol: 'LRNA.JK', name: 'Eka Sari Lorena Transport Tbk.' },
  { symbol: 'LSIP.JK', name: 'PP London Sumatra Indonesia Tb' },
  { symbol: 'LTLS.JK', name: 'Lautan Luas Tbk.' },
  { symbol: 'LUCK.JK', name: 'Sentral Mitra Informatika Tbk.' },
  { symbol: 'LUCY.JK', name: 'Lima Dua Lima Tiga Tbk.' },
  { symbol: 'MABA.JK', name: 'Marga Abhinaya Abadi Tbk.' },
  { symbol: 'MAGP.JK', name: 'Multi Agro Gemilang Plantation' },
  { symbol: 'MAHA.JK', name: 'Mandiri Herindo Adiperkasa Tbk' },
  { symbol: 'MAIN.JK', name: 'Malindo Feedmill Tbk.' },
  { symbol: 'MANG.JK', name: 'Manggung Polahraya Tbk.' },
  { symbol: 'MAPA.JK', name: 'Map Aktif Adiperkasa Tbk.' },
  { symbol: 'MAPB.JK', name: 'MAP Boga Adiperkasa Tbk.' },
  { symbol: 'MAPI.JK', name: 'Mitra Adiperkasa Tbk.' },
  { symbol: 'MARI.JK', name: 'Mahaka Radio Integra Tbk.' },
  { symbol: 'MARK.JK', name: 'Mark Dynamics Indonesia Tbk.' },
  { symbol: 'MASB.JK', name: 'Bank Multiarta Sentosa Tbk.' },
  { symbol: 'MAXI.JK', name: 'Maxindo Karya Anugerah Tbk.' },
  { symbol: 'MAYA.JK', name: 'Bank Mayapada Internasional Tb' },
  { symbol: 'MBAP.JK', name: 'Mitrabara Adiperdana Tbk.' },
  { symbol: 'MBMA.JK', name: 'Merdeka Battery Materials Tbk.' },
  { symbol: 'MBSS.JK', name: 'Mitrabahtera Segara Sejati Tbk' },
  { symbol: 'MBTO.JK', name: 'Martina Berto Tbk.' },
  { symbol: 'MCAS.JK', name: 'M Cash Integrasi Tbk.' },
  { symbol: 'MCOL.JK', name: 'Prima Andalan Mandiri Tbk.' },
  { symbol: 'MCOR.JK', name: 'Bank China Construction Bank I' },
  { symbol: 'MDIA.JK', name: 'Intermedia Capital Tbk.' },
  { symbol: 'MDIY.JK', name: 'Daya Intiguna Yasa Tbk.' },
  { symbol: 'MDKA.JK', name: 'Merdeka Copper Gold Tbk.' },
  { symbol: 'MDKI.JK', name: 'Emdeki Utama Tbk.' },
  { symbol: 'MDLA.JK', name: 'Medela Potentia Tbk.' },
  { symbol: 'MDLN.JK', name: 'Modernland Realty Tbk.' },
  { symbol: 'MDRN.JK', name: 'Modern Internasional Tbk.' },
  { symbol: 'MEDC.JK', name: 'Medco Energi Internasional Tbk' },
  { symbol: 'MEDS.JK', name: 'Hetzer Medical Indonesia Tbk.' },
  { symbol: 'MEGA.JK', name: 'Bank Mega Tbk.' },
  { symbol: 'MEJA.JK', name: 'Harta Djaya Karya Tbk.' },
  { symbol: 'MENN.JK', name: 'Menn Teknologi Indonesia Tbk.' },
  { symbol: 'MERI.JK', name: 'Merry Riana Edukasi Tbk.' },
  { symbol: 'MERK.JK', name: 'Merck Tbk.' },
  { symbol: 'META.JK', name: 'Nusantara Infrastructure Tbk.' },
  { symbol: 'MFMI.JK', name: 'Multifiling Mitra Indonesia Tb' },
  { symbol: 'MGLV.JK', name: 'NexAI Digital Infrastruktur Tb' },
  { symbol: 'MGNA.JK', name: 'Magna Investama Mandiri Tbk.' },
  { symbol: 'MGRO.JK', name: 'Mahkota Group Tbk.' },
  { symbol: 'MHKI.JK', name: 'Multi Hanna Kreasindo Tbk.' },
  { symbol: 'MICE.JK', name: 'Multi Indocitra Tbk.' },
  { symbol: 'MIDI.JK', name: 'Midi Utama Indonesia Tbk.' },
  { symbol: 'MIKA.JK', name: 'Mitra Keluarga Karyasehat Tbk.' },
  { symbol: 'MINA.JK', name: 'Sanurhasta Mitra Tbk.' },
  { symbol: 'MINE.JK', name: 'Sinar Terang Mandiri Tbk.' },
  { symbol: 'MIRA.JK', name: 'Mitra International Resources' },
  { symbol: 'MITI.JK', name: 'Mitra Investindo Tbk.' },
  { symbol: 'MKAP.JK', name: 'Multikarya Asia Pasifik Raya T' },
  { symbol: 'MKNT.JK', name: 'Mitra Komunikasi Nusantara Tbk' },
  { symbol: 'MKPI.JK', name: 'Metropolitan Kentjana Tbk.' },
  { symbol: 'MKTR.JK', name: 'Menthobi Karyatama Raya Tbk.' },
  { symbol: 'MLBI.JK', name: 'Multi Bintang Indonesia Tbk.' },
  { symbol: 'MLIA.JK', name: 'Mulia Industrindo Tbk' },
  { symbol: 'MLPL.JK', name: 'Multipolar Tbk.' },
  { symbol: 'MLPT.JK', name: 'Multipolar Technology Tbk.' },
  { symbol: 'MMIX.JK', name: 'Multi Medika Internasional Tbk' },
  { symbol: 'MMLP.JK', name: 'Mega Manunggal Property Tbk.' },
  { symbol: 'MNCN.JK', name: 'Media Nusantara Citra Tbk.' },
  { symbol: 'MOLI.JK', name: 'Madusari Murni Indah Tbk.' },
  { symbol: 'MORA.JK', name: 'Ekamas Mora Republik Tbk.' },
  { symbol: 'MPIX.JK', name: 'Mitra Pedagang Indonesia Tbk.' },
  { symbol: 'MPMX.JK', name: 'Mitra Pinasthika Mustika Tbk.' },
  { symbol: 'MPOW.JK', name: 'Megapower Makmur Tbk.' },
  { symbol: 'MPPA.JK', name: 'Matahari Putra Prima Tbk.' },
  { symbol: 'MPRO.JK', name: 'Maha Properti Indonesia Tbk.' },
  { symbol: 'MPXL.JK', name: 'MPX Logistics International Tb' },
  { symbol: 'MRAT.JK', name: 'Mustika Ratu Tbk.' },
  { symbol: 'MREI.JK', name: 'Maskapai Reasuransi Indonesia' },
  { symbol: 'MSIE.JK', name: 'Multisarana Intan Eduka Tbk.' },
  { symbol: 'MSIN.JK', name: 'MNC Digital Entertainment Tbk.' },
  { symbol: 'MSJA.JK', name: 'Multi Spunindo Jaya Tbk.' },
  { symbol: 'MSKY.JK', name: 'MNC Sky Vision Tbk.' },
  { symbol: 'MSTI.JK', name: 'Mastersystem Infotama Tbk.' },
  { symbol: 'MTDL.JK', name: 'Metrodata Electronics Tbk.' },
  { symbol: 'MTEL.JK', name: 'Dayamitra Telekomunikasi Tbk.' },
  { symbol: 'MTFN.JK', name: 'Capitalinc Investment Tbk.' },
  { symbol: 'MTLA.JK', name: 'Metropolitan Land Tbk.' },
  { symbol: 'MTMH.JK', name: 'Murni Sadar Tbk.' },
  { symbol: 'MTPS.JK', name: 'Meta Epsi Tbk.' },
  { symbol: 'MTRA.JK', name: 'Mitra Pemuda Tbk.' },
  { symbol: 'MTSM.JK', name: 'Metro Realty Tbk.' },
  { symbol: 'MTWI.JK', name: 'Malacca Trust Wuwungan Insuran' },
  { symbol: 'MUTU.JK', name: 'Mutuagung Lestari Tbk.' },
  { symbol: 'MYOH.JK', name: 'Samindo Resources Tbk.' },
  { symbol: 'MYOR.JK', name: 'Mayora Indah Tbk.' },
  { symbol: 'MYTX.JK', name: 'Asia Pacific Investama Tbk.' },
  { symbol: 'NAIK.JK', name: 'Adiwarna Anugerah Abadi Tbk.' },
  { symbol: 'NANO.JK', name: 'Nanotech Indonesia Global Tbk.' },
  { symbol: 'NASA.JK', name: 'Andalan Perkasa Abadi Tbk.' },
  { symbol: 'NASI.JK', name: 'Wahana Inti Makmur Tbk.' },
  { symbol: 'NATO.JK', name: 'Olympus Strategic Indonesia Tb' },
  { symbol: 'NAYZ.JK', name: 'Hassana Boga Sejahtera Tbk.' },
  { symbol: 'NCKL.JK', name: 'Trimegah Bangun Persada Tbk.' },
  { symbol: 'NELY.JK', name: 'Pelayaran Nelly Dwi Putri Tbk.' },
  { symbol: 'NEST.JK', name: 'Esta Indonesia Tbk.' },
  { symbol: 'NETV.JK', name: 'MDTV Media Technologies Tbk.' },
  { symbol: 'NFCX.JK', name: 'NFC Indonesia Tbk.' },
  { symbol: 'NICE.JK', name: 'Adhi Kartiko Pratama Tbk.' },
  { symbol: 'NICK.JK', name: 'Charnic Capital Tbk.' },
  { symbol: 'NICL.JK', name: 'PAM Mineral Tbk.' },
  { symbol: 'NIKL.JK', name: 'Pelat Timah Nusantara Tbk.' },
  { symbol: 'NINE.JK', name: 'Techno9 Indonesia Tbk.' },
  { symbol: 'NIRO.JK', name: 'City Retail Developments Tbk.' },
  { symbol: 'NISP.JK', name: 'Bank OCBC NISP Tbk.' },
  { symbol: 'NOBU.JK', name: 'Bank Nationalnobu Tbk.' },
  { symbol: 'NPGF.JK', name: 'Nusa Palapa Gemilang Tbk.' },
  { symbol: 'NRCA.JK', name: 'Nusa Raya Cipta Tbk.' },
  { symbol: 'NSSS.JK', name: 'Nusantara Sawit Sejahtera Tbk.' },
  { symbol: 'NTBK.JK', name: 'Nusatama Berkah Tbk.' },
  { symbol: 'NUSA.JK', name: 'Sinergi Megah Internusa Tbk.' },
  { symbol: 'NZIA.JK', name: 'Nusantara Almazia Tbk.' },
  { symbol: 'OASA.JK', name: 'Maharaksa Biru Energi Tbk.' },
  { symbol: 'OBAT.JK', name: 'Brigit Biofarmaka Teknologi Tb' },
  { symbol: 'OBMD.JK', name: 'OBM Drilchem Tbk.' },
  { symbol: 'OCAP.JK', name: 'Onix Capital Tbk.' },
  { symbol: 'OILS.JK', name: 'Indo Oil Perkasa Tbk.' },
  { symbol: 'OKAS.JK', name: 'Ancora Indonesia Resources Tbk' },
  { symbol: 'OLIV.JK', name: 'Atlas Nexus Group Tbk.' },
  { symbol: 'OMED.JK', name: 'Jayamas Medica Industri Tbk.' },
  { symbol: 'OMRE.JK', name: 'Indonesia Prima Property Tbk' },
  { symbol: 'OPMS.JK', name: 'Optima Prima Metal Sinergi Tbk' },
  { symbol: 'PACK.JK', name: 'Abadi Nusantara Hijau Investam' },
  { symbol: 'PADA.JK', name: 'Personel Alih Daya Tbk.' },
  { symbol: 'PADI.JK', name: 'Minna Padi Investama Sekuritas' },
  { symbol: 'PALM.JK', name: 'Provident Investasi Bersama Tb' },
  { symbol: 'PAMG.JK', name: 'Bima Sakti Pertiwi Tbk.' },
  { symbol: 'PANI.JK', name: 'Pantai Indah Kapuk Dua Tbk.' },
  { symbol: 'PANR.JK', name: 'Panorama Sentrawisata Tbk.' },
  { symbol: 'PANS.JK', name: 'Panin Sekuritas Tbk.' },
  { symbol: 'PART.JK', name: 'Cipta Perdana Lancar Tbk.' },
  { symbol: 'PBID.JK', name: 'Panca Budi Idaman Tbk.' },
  { symbol: 'PBRX.JK', name: 'Pan Brothers Tbk.' },
  { symbol: 'PBSA.JK', name: 'Paramita Bangun Sarana Tbk.' },
  { symbol: 'PCAR.JK', name: 'Prima Cakrawala Abadi Tbk.' },
  { symbol: 'PDES.JK', name: 'Destinasi Tirta Nusantara Tbk' },
  { symbol: 'PDPP.JK', name: 'Primadaya Plastisindo Tbk.' },
  { symbol: 'PEGE.JK', name: 'Panca Global Kapital Tbk.' },
  { symbol: 'PEHA.JK', name: 'Phapros Tbk.' },
  { symbol: 'PEVE.JK', name: 'Penta Valent Tbk.' },
  { symbol: 'PGAS.JK', name: 'Perusahaan Gas Negara (Persero' },
  { symbol: 'PGEO.JK', name: 'Pertamina Geothermal Energy Tb' },
  { symbol: 'PGJO.JK', name: 'Bahtera Bumi Raya Tbk.' },
  { symbol: 'PGLI.JK', name: 'Pembangunan Graha Lestari Inda' },
  { symbol: 'PGUN.JK', name: 'Pradiksi Gunatama Tbk.' },
  { symbol: 'PICO.JK', name: 'Pelangi Indah Canindo Tbk' },
  { symbol: 'PIPA.JK', name: 'Oxala Energy International Tbk' },
  { symbol: 'PJAA.JK', name: 'Pembangunan Jaya Ancol Tbk.' },
  { symbol: 'PJHB.JK', name: 'Pelayaran Jaya Hidup Baru Tbk.' },
  { symbol: 'PKPK.JK', name: 'Paragon Karya Perkasa Tbk.' },
  { symbol: 'PLAN.JK', name: 'Planet Properindo Jaya Tbk.' },
  { symbol: 'PLAS.JK', name: 'Polaris Investama Tbk' },
  { symbol: 'PLIN.JK', name: 'Plaza Indonesia Realty Tbk.' },
  { symbol: 'PMJS.JK', name: 'Putra Mandiri Jembar Tbk.' },
  { symbol: 'PMMP.JK', name: 'Panca Mitra Multiperdana Tbk.' },
  { symbol: 'PMUI.JK', name: 'Prima Multi Usaha Indonesia Tb' },
  { symbol: 'PNBN.JK', name: 'Bank Pan Indonesia Tbk' },
  { symbol: 'PNBS.JK', name: 'Bank Panin Dubai Syariah Tbk.' },
  { symbol: 'PNGO.JK', name: 'AEP Pinago Plantations Tbk.' },
  { symbol: 'PNIN.JK', name: 'Paninvest Tbk.' },
  { symbol: 'PNLF.JK', name: 'Panin Financial Tbk.' },
  { symbol: 'PNSE.JK', name: 'Pudjiadi & Sons Tbk.' },
  { symbol: 'POLA.JK', name: 'Pool Advista Finance Tbk.' },
  { symbol: 'POLI.JK', name: 'Pollux Hotels Group Tbk.' },
  { symbol: 'POLL.JK', name: 'Pollux Properties Indonesia Tb' },
  { symbol: 'POLU.JK', name: 'Golden Flower Tbk.' },
  { symbol: 'POLY.JK', name: 'Asia Pacific Fibers Tbk' },
  { symbol: 'POOL.JK', name: 'Pool Advista Indonesia Tbk.' },
  { symbol: 'PORT.JK', name: 'Nusantara Pelabuhan Handal Tbk' },
  { symbol: 'POSA.JK', name: 'Bliss Properti Indonesia Tbk.' },
  { symbol: 'POWR.JK', name: 'Cikarang Listrindo Tbk.' },
  { symbol: 'PPGL.JK', name: 'Prima Globalindo Logistik Tbk.' },
  { symbol: 'PPRE.JK', name: 'PP Presisi Tbk.' },
  { symbol: 'PPRI.JK', name: 'Paperocks Indonesia Tbk.' },
  { symbol: 'PPRO.JK', name: 'PP Properti Tbk.' },
  { symbol: 'PRAY.JK', name: 'Famon Awal Bros Sedaya Tbk.' },
  { symbol: 'PRDA.JK', name: 'Prodia Widyahusada Tbk.' },
  { symbol: 'PRDL.JK', name: 'Prodia Diagnostic Line Tbk.' },
  { symbol: 'PRIM.JK', name: 'Royal Prima Tbk.' },
  { symbol: 'PSAB.JK', name: 'J Resources Asia Pasifik Tbk.' },
  { symbol: 'PSAT.JK', name: 'Pancaran Samudera Transport Tb' },
  { symbol: 'PSDN.JK', name: 'Prasidha Aneka Niaga Tbk' },
  { symbol: 'PSGO.JK', name: 'Palma Serasih Tbk.' },
  { symbol: 'PSKT.JK', name: 'Red Planet Indonesia Tbk.' },
  { symbol: 'PSSI.JK', name: 'IMC Pelita Logistik Tbk.' },
  { symbol: 'PTBA.JK', name: 'Bukit Asam (Persero) Tbk.' },
  { symbol: 'PTDU.JK', name: 'Djasa Ubersakti Tbk.' },
  { symbol: 'PTIS.JK', name: 'Indo Straits Tbk.' },
  { symbol: 'PTMP.JK', name: 'Mitra Pack Tbk.' },
  { symbol: 'PTMR.JK', name: 'Master Print Tbk.' },
  { symbol: 'PTPP.JK', name: 'PP (Persero) Tbk.' },
  { symbol: 'PTPS.JK', name: 'Pulau Subur Tbk.' },
  { symbol: 'PTPW.JK', name: 'Pratama Widya Tbk.' },
  { symbol: 'PTRO.JK', name: 'Petrosea Tbk.' },
  { symbol: 'PTSN.JK', name: 'Sat Nusapersada Tbk' },
  { symbol: 'PTSP.JK', name: 'Pioneerindo Gourmet Internatio' },
  { symbol: 'PUDP.JK', name: 'Pudjiadi Prestige Tbk.' },
  { symbol: 'PURA.JK', name: 'Putra Rajawali Kencana Tbk.' },
  { symbol: 'PURE.JK', name: 'Trinitan Metals and Minerals T' },
  { symbol: 'PURI.JK', name: 'Puri Global Sukses Tbk.' },
  { symbol: 'PWON.JK', name: 'Pakuwon Jati Tbk.' },
  { symbol: 'PYFA.JK', name: 'Pyridam Farma Tbk' },
  { symbol: 'PZZA.JK', name: 'Sarimelati Kencana Tbk.' },
  { symbol: 'RAAM.JK', name: 'Tripar Multivision Plus Tbk.' },
  { symbol: 'RAFI.JK', name: 'Sari Kreasi Boga Tbk.' },
  { symbol: 'RAJA.JK', name: 'Rukun Raharja Tbk.' },
  { symbol: 'RALS.JK', name: 'Ramayana Lestari Sentosa Tbk.' },
  { symbol: 'RANC.JK', name: 'Supra Boga Lestari Tbk.' },
  { symbol: 'RANS.JK', name: 'Rans Entertainmen Indonesia Tb' },
  { symbol: 'RATU.JK', name: 'Raharja Energi Cepu Tbk.' },
  { symbol: 'RBMS.JK', name: 'Ristia Bintang Mahkotasejati T' },
  { symbol: 'RCCC.JK', name: 'Utama Radar Cahaya Tbk.' },
  { symbol: 'RDTX.JK', name: 'Roda Vivatex Tbk' },
  { symbol: 'REAL.JK', name: 'Repower Asia Indonesia Tbk.' },
  { symbol: 'RELF.JK', name: 'Graha Mitra Asia Tbk.' },
  { symbol: 'RELI.JK', name: 'Reliance Sekuritas Indonesia T' },
  { symbol: 'RGAS.JK', name: 'Kian Santang Muliatama Tbk.' },
  { symbol: 'RICY.JK', name: 'Ricky Putra Globalindo Tbk' },
  { symbol: 'RIGS.JK', name: 'Rig Tenders Indonesia Tbk.' },
  { symbol: 'RIMO.JK', name: 'Rimo International Lestari Tbk' },
  { symbol: 'RISE.JK', name: 'Jaya Sukses Makmur Sentosa Tbk' },
  { symbol: 'RLCO.JK', name: 'Abadi Lestari Indonesia Tbk.' },
  { symbol: 'RMKE.JK', name: 'RMK Energy Tbk.' },
  { symbol: 'RMKO.JK', name: 'Royaltama Mulia Kontraktorindo' },
  { symbol: 'ROCK.JK', name: 'Rockfields Properti Indonesia' },
  { symbol: 'RODA.JK', name: 'Pikko Land Development Tbk.' },
  { symbol: 'RONY.JK', name: 'Aracord Nusantara Group Tbk.' },
  { symbol: 'ROTI.JK', name: 'Nippon Indosari Corpindo Tbk.' },
  { symbol: 'RSCH.JK', name: 'Charlie Hospital Semarang Tbk.' },
  { symbol: 'RSGK.JK', name: 'Kedoya Adyaraya Tbk.' },
  { symbol: 'RUIS.JK', name: 'Radiant Utama Interinsco Tbk.' },
  { symbol: 'RUNS.JK', name: 'Global Sukses Solusi Tbk.' },
  { symbol: 'SAFE.JK', name: 'Steady Safe Tbk' },
  { symbol: 'SAGE.JK', name: 'Saptausaha Gemilangindah Tbk.' },
  { symbol: 'SAME.JK', name: 'Sarana Meditama Metropolitan T' },
  { symbol: 'SAMF.JK', name: 'Saraswanti Anugerah Makmur Tbk' },
  { symbol: 'SAPX.JK', name: 'Satria Antaran Prima Tbk.' },
  { symbol: 'SATU.JK', name: 'Kota Satu Properti Tbk.' },
  { symbol: 'SBAT.JK', name: 'Sejahtera Bintang Abadi Textil' },
  { symbol: 'SBMA.JK', name: 'Surya Biru Murni Acetylene Tbk' },
  { symbol: 'SCCO.JK', name: 'Supreme Cable Manufacturing &' },
  { symbol: 'SCMA.JK', name: 'Surya Citra Media Tbk.' },
  { symbol: 'SCNP.JK', name: 'Selaras Citra Nusantara Perkas' },
  { symbol: 'SCPI.JK', name: 'Organon Pharma Indonesia Tbk.' },
  { symbol: 'SDMU.JK', name: 'Sidomulyo Selaras Tbk.' },
  { symbol: 'SDPC.JK', name: 'Millennium Pharmacon Internati' },
  { symbol: 'SDRA.JK', name: 'Bank Woori Saudara Indonesia 1' },
  { symbol: 'SEMA.JK', name: 'Semacom Integrated Tbk.' },
  { symbol: 'SFAN.JK', name: 'Surya Fajar Capital Tbk.' },
  { symbol: 'SGER.JK', name: 'Sumber Global Energy Tbk.' },
  { symbol: 'SGRO.JK', name: 'Prime Agri Resources Tbk.' },
  { symbol: 'SHID.JK', name: 'Hotel Sahid Jaya International' },
  { symbol: 'SHIP.JK', name: 'Sillo Maritime Perdana Tbk.' },
  { symbol: 'SICO.JK', name: 'Sigma Energy Compressindo Tbk.' },
  { symbol: 'SIDO.JK', name: 'Industri Jamu dan Farmasi Sido' },
  { symbol: 'SILO.JK', name: 'Siloam International Hospitals' },
  { symbol: 'SIMA.JK', name: 'Siwani Makmur Tbk' },
  { symbol: 'SIMP.JK', name: 'Salim Ivomas Pratama Tbk.' },
  { symbol: 'SINI.JK', name: 'Singaraja Putra Tbk.' },
  { symbol: 'SIPD.JK', name: 'Sreeya Sewu Indonesia Tbk.' },
  { symbol: 'SKBM.JK', name: 'Sekar Bumi Tbk.' },
  { symbol: 'SKLT.JK', name: 'Sekar Laut Tbk.' },
  { symbol: 'SKRN.JK', name: 'Superkrane Mitra Utama Tbk.' },
  { symbol: 'SKYB.JK', name: 'Northcliff Citranusa Indonesia' },
  { symbol: 'SLIS.JK', name: 'Gaya Abadi Sempurna Tbk.' },
  { symbol: 'SMAR.JK', name: 'Sinar Mas Agro Resources and T' },
  { symbol: 'SMBR.JK', name: 'Semen Baturaja (Persero) Tbk.' },
  { symbol: 'SMCB.JK', name: 'Solusi Bangun Indonesia Tbk.' },
  { symbol: 'SMDM.JK', name: 'Suryamas Dutamakmur Tbk.' },
  { symbol: 'SMDR.JK', name: 'Samudera Indonesia  Tbk.' },
  { symbol: 'SMGA.JK', name: 'Sumber Mineral Global Abadi Tb' },
  { symbol: 'SMGR.JK', name: 'Semen Indonesia (Persero) Tbk.' },
  { symbol: 'SMIL.JK', name: 'Sarana Mitra Luas Tbk.' },
  { symbol: 'SMKL.JK', name: 'Satyamitra Kemas Lestari Tbk.' },
  { symbol: 'SMKM.JK', name: 'Sumber Mas Konstruksi Tbk.' },
  { symbol: 'SMLE.JK', name: 'Sinergi Multi Lestarindo Tbk.' },
  { symbol: 'SMMA.JK', name: 'Sinarmas Multiartha Tbk.' },
  { symbol: 'SMMT.JK', name: 'Golden Eagle Energy Tbk.' },
  { symbol: 'SMRA.JK', name: 'Summarecon Agung Tbk.' },
  { symbol: 'SMRU.JK', name: 'SMR Utama Tbk.' },
  { symbol: 'SMSM.JK', name: 'Selamat Sempurna Tbk.' },
  { symbol: 'SNLK.JK', name: 'Sunter Lakeside Hotel Tbk.' },
  { symbol: 'SOCI.JK', name: 'Soechi Lines Tbk.' },
  { symbol: 'SOFA.JK', name: 'Solusi Environment Asia Tbk.' },
  { symbol: 'SOHO.JK', name: 'Soho Global Health Tbk.' },
  { symbol: 'SOLA.JK', name: 'Xolare RCR Energy Tbk.' },
  { symbol: 'SONA.JK', name: 'Sona Topas Tourism Industry Tb' },
  { symbol: 'SOSS.JK', name: 'ALSOK Indonesia Services Tbk.' },
  { symbol: 'SOTS.JK', name: 'Satria Mega Kencana Tbk.' },
  { symbol: 'SOUL.JK', name: 'Mitra Tirta Buwana Tbk.' },
  { symbol: 'SPMA.JK', name: 'Suparma Tbk.' },
  { symbol: 'SPRE.JK', name: 'Soraya Berjaya Indonesia Tbk.' },
  { symbol: 'SPTO.JK', name: 'Surya Pertiwi Tbk.' },
  { symbol: 'SQMI.JK', name: 'Wilton Makmur Indonesia Tbk.' },
  { symbol: 'SRAJ.JK', name: 'Sejahteraraya Anugrahjaya Tbk.' },
  { symbol: 'SRIL.JK', name: 'Sri Rejeki Isman Tbk.' },
  { symbol: 'SRSN.JK', name: 'Indo Acidatama Tbk' },
  { symbol: 'SRTG.JK', name: 'Saratoga Investama Sedaya Tbk.' },
  { symbol: 'SSIA.JK', name: 'Surya Semesta Internusa Tbk.' },
  { symbol: 'SSMS.JK', name: 'Sawit Sumbermas Sarana Tbk.' },
  { symbol: 'SSTM.JK', name: 'Sunson Textile Manufacture Tbk' },
  { symbol: 'STAA.JK', name: 'Sumber Tani Agung Resources Tb' },
  { symbol: 'STAR.JK', name: 'Calculus Global Ventures Tbk.' },
  { symbol: 'STRK.JK', name: 'Lovina Beach Brewery Tbk.' },
  { symbol: 'STTP.JK', name: 'Siantar Top Tbk.' },
  { symbol: 'SUGI.JK', name: 'Sugih Energy Tbk.' },
  { symbol: 'SULI.JK', name: 'SLJ Global Tbk.' },
  { symbol: 'SUNI.JK', name: 'Sunindo Pratama Tbk.' },
  { symbol: 'SUPA.JK', name: 'Super Bank Indonesia Tbk.' },
  { symbol: 'SUPR.JK', name: 'Solusi Tunas Pratama Tbk.' },
  { symbol: 'SURE.JK', name: 'Super Energy Tbk.' },
  { symbol: 'SURI.JK', name: 'Maja Agung Latexindo Tbk.' },
  { symbol: 'SWAT.JK', name: 'Sriwahana Adityakarta Tbk.' },
  { symbol: 'SWID.JK', name: 'Saraswanti Indoland Developmen' },
  { symbol: 'TALF.JK', name: 'Tunas Alfin Tbk.' },
  { symbol: 'TAMA.JK', name: 'Lancartama Sejati Tbk.' },
  { symbol: 'TAMU.JK', name: 'Pelayaran Tamarin Samudra Tbk.' },
  { symbol: 'TAPG.JK', name: 'Triputra Agro Persada Tbk.' },
  { symbol: 'TARA.JK', name: 'Agung Semesta Sejahtera Tbk.' },
  { symbol: 'TAXI.JK', name: 'Express Transindo Utama Tbk.' },
  { symbol: 'TAYS.JK', name: 'Jaya Swarasa Agung Tbk.' },
  { symbol: 'TBIG.JK', name: 'Tower Bersama Infrastructure T' },
  { symbol: 'TBLA.JK', name: 'Tunas Baru Lampung Tbk.' },
  { symbol: 'TBMS.JK', name: 'Tembaga Mulia Semanan Tbk.' },
  { symbol: 'TCID.JK', name: 'Mandom Indonesia Tbk.' },
  { symbol: 'TCPI.JK', name: 'Transcoal Pacific Tbk.' },
  { symbol: 'TDPM.JK', name: 'Tianrong Chemicals Industry Tb' },
  { symbol: 'TEBE.JK', name: 'Dana Brata Luhur Tbk.' },
  { symbol: 'TECH.JK', name: 'Indosterling Technomedia Tbk.' },
  { symbol: 'TELE.JK', name: 'Omni Inovasi Indonesia Tbk.' },
  { symbol: 'TFAS.JK', name: 'Telefast Indonesia Tbk.' },
  { symbol: 'TFCO.JK', name: 'Tifico Fiber Indonesia Tbk.' },
  { symbol: 'TGKA.JK', name: 'Tigaraksa Satria Tbk.' },
  { symbol: 'TGRA.JK', name: 'Terregra Asia Energy Tbk.' },
  { symbol: 'TGUK.JK', name: 'Platinum Wahab Nusantara Tbk.' },
  { symbol: 'TIFA.JK', name: 'KDB Tifa Finance Tbk.' },
  { symbol: 'TINS.JK', name: 'TIMAH (Persero) Tbk.' },
  { symbol: 'TIRA.JK', name: 'Tira Austenite Tbk' },
  { symbol: 'TIRT.JK', name: 'Tirta Mahakam Resources Tbk' },
  { symbol: 'TKIM.JK', name: 'Pabrik Kertas Tjiwi Kimia Tbk.' },
  { symbol: 'TLDN.JK', name: 'Teladan Prima Agro Tbk.' },
  { symbol: 'TLKM.JK', name: 'Telkom Indonesia (Persero) Tbk' },
  { symbol: 'TMAS.JK', name: 'Temas Tbk.' },
  { symbol: 'TMPO.JK', name: 'Tempo Intimedia Tbk.' },
  { symbol: 'TNCA.JK', name: 'Trimuda Nuansa Citra Tbk.' },
  { symbol: 'TOBA.JK', name: 'TBS Energi Utama Tbk.' },
  { symbol: 'TOOL.JK', name: 'Rohartindo Nusantara Luas Tbk.' },
  { symbol: 'TOPS.JK', name: 'Totalindo Eka Persada Tbk.' },
  { symbol: 'TOSK.JK', name: 'Topindo Solusi Komunika Tbk.' },
  { symbol: 'TOTL.JK', name: 'Total Bangun Persada Tbk.' },
  { symbol: 'TOTO.JK', name: 'Surya Toto Indonesia Tbk.' },
  { symbol: 'TOWR.JK', name: 'Sarana Menara Nusantara Tbk.' },
  { symbol: 'TOYS.JK', name: 'Sunindo Adipersada Tbk.' },
  { symbol: 'TPIA.JK', name: 'Chandra Asri Pacific Tbk.' },
  { symbol: 'TPMA.JK', name: 'Trans Power Marine Tbk.' },
  { symbol: 'TRAM.JK', name: 'Trada Alam Minera Tbk.' },
  { symbol: 'TRGU.JK', name: 'Cerestar Indonesia Tbk.' },
  { symbol: 'TRIL.JK', name: 'Triwira Insanlestari Tbk.' },
  { symbol: 'TRIM.JK', name: 'Trimegah Sekuritas Indonesia T' },
  { symbol: 'TRIN.JK', name: 'Perintis Triniti Properti Tbk.' },
  { symbol: 'TRIO.JK', name: 'Trikomsel Oke Tbk.' },
  { symbol: 'TRIS.JK', name: 'Trisula International Tbk.' },
  { symbol: 'TRJA.JK', name: 'Transkon Jaya Tbk.' },
  { symbol: 'TRON.JK', name: 'Teknologi Karya Digital Nusa T' },
  { symbol: 'TRST.JK', name: 'Trias Sentosa Tbk.' },
  { symbol: 'TRUE.JK', name: 'Triniti Dinamik Tbk.' },
  { symbol: 'TRUK.JK', name: 'Guna Timur Raya Tbk.' },
  { symbol: 'TRUS.JK', name: 'Trust Finance Indonesia Tbk' },
  { symbol: 'TSPC.JK', name: 'Tempo Scan Pacific Tbk.' },
  { symbol: 'TUGU.JK', name: 'Asuransi Tugu Pratama Indonesi' },
  { symbol: 'TYRE.JK', name: 'King Tire Indonesia Tbk.' },
  { symbol: 'UANG.JK', name: 'Pakuan Tbk.' },
  { symbol: 'UCID.JK', name: 'Uni-Charm Indonesia Tbk.' },
  { symbol: 'UDNG.JK', name: 'Agro Bahari Nusantara Tbk.' },
  { symbol: 'UFOE.JK', name: 'Damai Sejahtera Abadi Tbk.' },
  { symbol: 'ULTJ.JK', name: 'Ultrajaya Milk Industry & Trad' },
  { symbol: 'UNIC.JK', name: 'Unggul Indah Cahaya Tbk.' },
  { symbol: 'UNIQ.JK', name: 'Ulima Nitra Tbk.' },
  { symbol: 'UNIT.JK', name: 'Nusantara Inti Corpora Tbk' },
  { symbol: 'UNSP.JK', name: 'Bakrie Sumatera Plantations Tb' },
  { symbol: 'UNTD.JK', name: 'Terang Dunia Internusa Tbk.' },
  { symbol: 'UNTR.JK', name: 'United Tractors Tbk.' },
  { symbol: 'UNVR.JK', name: 'Unilever Indonesia Tbk.' },
  { symbol: 'URBN.JK', name: 'Urban Jakarta Propertindo Tbk.' },
  { symbol: 'UVCR.JK', name: 'Trimegah Karya Pratama Tbk.' },
  { symbol: 'VAST.JK', name: 'Vastland Indonesia Tbk.' },
  { symbol: 'VERN.JK', name: 'Verona Indah Pictures Tbk.' },
  { symbol: 'VICI.JK', name: 'Victoria Care Indonesia Tbk.' },
  { symbol: 'VICO.JK', name: 'Victoria Investama Tbk.' },
  { symbol: 'VINS.JK', name: 'Victoria Insurance Tbk.' },
  { symbol: 'VISI.JK', name: 'Satu Visi Putra Tbk.' },
  { symbol: 'VIVA.JK', name: 'Visi Media Asia Tbk.' },
  { symbol: 'VKTR.JK', name: 'VKTR Teknologi Mobilitas Tbk.' },
  { symbol: 'VOKS.JK', name: 'Voksel Electric Tbk.' },
  { symbol: 'VRNA.JK', name: 'Mizuho Leasing Indonesia Tbk.' },
  { symbol: 'VTNY.JK', name: 'Venteny Fortuna International' },
  { symbol: 'WAPO.JK', name: 'Wahana Pronatural Tbk.' },
  { symbol: 'WBSA.JK', name: 'BSA Logistics Indonesia Tbk.' },
  { symbol: 'WEGE.JK', name: 'Wijaya Karya Bangunan Gedung T' },
  { symbol: 'WEHA.JK', name: 'WEHA Transportasi Indonesia Tb' },
  { symbol: 'WGSH.JK', name: 'Wira Global Solusi Tbk.' },
  { symbol: 'WICO.JK', name: 'Wicaksana Overseas Internation' },
  { symbol: 'WIDI.JK', name: 'Widiant Jaya Krenindo Tbk.' },
  { symbol: 'WIFI.JK', name: 'Solusi Sinergi Digital Tbk.' },
  { symbol: 'WIIM.JK', name: 'Wismilak Inti Makmur Tbk.' },
  { symbol: 'WIKA.JK', name: 'Wijaya Karya (Persero) Tbk.' },
  { symbol: 'WINE.JK', name: 'Hatten Bali Tbk.' },
  { symbol: 'WINR.JK', name: 'Winner Nusantara Jaya Tbk.' },
  { symbol: 'WINS.JK', name: 'Wintermar Offshore Marine Tbk.' },
  { symbol: 'WIRG.JK', name: 'WIR ASIA Tbk.' },
  { symbol: 'WMPP.JK', name: 'Widodo Makmur Perkasa Tbk.' },
  { symbol: 'WMUU.JK', name: 'Widodo Makmur Unggas Tbk.' },
  { symbol: 'WOMF.JK', name: 'Wahana Ottomitra Multiartha Tb' },
  { symbol: 'WOOD.JK', name: 'Integra Indocabinet Tbk.' },
  { symbol: 'WOWS.JK', name: 'Ginting Jaya Energi Tbk.' },
  { symbol: 'WSBP.JK', name: 'Waskita Beton Precast Tbk.' },
  { symbol: 'WSKT.JK', name: 'Waskita Karya (Persero) Tbk.' },
  { symbol: 'WTON.JK', name: 'Wijaya Karya Beton Tbk.' },
  { symbol: 'YELO.JK', name: 'Yelooo Integra Datanet Tbk.' },
  { symbol: 'YOII.JK', name: 'Asuransi Digital Bersama Tbk.' },
  { symbol: 'YPAS.JK', name: 'Yanaprima Hastapersada Tbk' },
  { symbol: 'YULE.JK', name: 'Yulie Sekuritas Indonesia Tbk.' },
  { symbol: 'YUPI.JK', name: 'Yupi Indo Jelly Gum Tbk.' },
  { symbol: 'ZATA.JK', name: 'Bersama Zatta Jaya Tbk.' },
  { symbol: 'ZBRA.JK', name: 'Dosni Roha Indonesia Tbk.' },
  { symbol: 'ZINC.JK', name: 'Kapuas Prima Coal Tbk.' },
  { symbol: 'ZONE.JK', name: 'Mega Perintis Tbk.' },
  { symbol: 'ZYRX.JK', name: 'Zyrexindo Mandiri Buana Tbk.' },
];
