export const TICKERS = [
  { symbol: 'AALI.JK', name: 'Astra Agro Lestari Tbk.' },
  { symbol: 'ABBA.JK', name: 'Mahaka Media Tbk.' },
  { symbol: 'ABDA.JK', name: 'Asuransi Bina Dana Arta Tbk.' },
  { symbol: 'ABGW.JK', name: 'ABGW Company Tbk.' },
  { symbol: 'ABID.JK', name: 'ABID Company Tbk.' },
  { symbol: 'ABMJ.JK', name: 'ABMJ Company Tbk.' },
  { symbol: 'ABMM.JK', name: 'ABM Investama Tbk.' },
  { symbol: 'ACES.JK', name: 'Ace Hardware Indonesia Tbk.' },
  { symbol: 'ACST.JK', name: 'Acset Indonusa Tbk.' },
  { symbol: 'ADAC.JK', name: 'ADAC Company Tbk.' },
  { symbol: 'ADES.JK', name: 'Akasha Wira International Tbk.' },
  { symbol: 'ADHI.JK', name: 'Adhi Karya (Persero) Tbk.' },
  { symbol: 'ADMF.JK', name: 'Adira Dinamika Multi Finance Tbk.' },
  { symbol: 'ADMG.JK', name: 'Polychem Indonesia Tbk.' },
  { symbol: 'ADMR.JK', name: 'Adaro Minerals Indonesia Tbk.' },
  { symbol: 'ADRO.JK', name: 'Adaro Energy Indonesia Tbk.' },
  { symbol: 'AFPJ.JK', name: 'AFPJ Company Tbk.' },
  { symbol: 'AGAR.JK', name: 'Asia Sejahtera Mina Tbk.' },
  { symbol: 'AGII.JK', name: 'Aneka Gas Industri Tbk.' },
  { symbol: 'AGPH.JK', name: 'AGPH Company Tbk.' },
  { symbol: 'AGRO.JK', name: 'Bank Rakyat Indonesia Agroniaga Tbk.' },
  { symbol: 'AGRS.JK', name: 'Bank IBK Indonesia Tbk.' },
  { symbol: 'AHAP.JK', name: 'Asuransi Harta Aman Pratama Tbk.' },
  { symbol: 'AHQJ.JK', name: 'AHQJ Company Tbk.' },
  { symbol: 'AIKO.JK', name: 'AIKO Company Tbk.' },
  { symbol: 'AIMS.JK', name: 'Akbar Indo Makmur Stimec Tbk.' },
  { symbol: 'AISA.JK', name: 'FKS Food Sejahtera Tbk.' },
  { symbol: 'AKKU.JK', name: 'Anugerah Kagum Karya Utama Tbk.' },
  { symbol: 'AKPI.JK', name: 'Argha Karya Prima Industry Tbk.' },
  { symbol: 'AKRA.JK', name: 'AKR Corporindo Tbk.' },
  { symbol: 'AKSI.JK', name: 'Maja Agung Latexindo Tbk.' },
  { symbol: 'ALDO.JK', name: 'Alkindo Naratama Tbk.' },
  { symbol: 'ALKA.JK', name: 'Alakasa Industrindo Tbk.' },
  { symbol: 'ALMI.JK', name: 'Alumindo Light Metal Industry Tbk.' },
  { symbol: 'ALTO.JK', name: 'Tri Banyan Tirta Tbk.' },
  { symbol: 'ALYY.JK', name: 'ALYY Company Tbk.' },
  { symbol: 'AMAE.JK', name: 'AMAE Company Tbk.' },
  { symbol: 'AMAG.JK', name: 'Asuransi Multi Artha Guna Tbk.' },
  { symbol: 'AMAR.JK', name: 'Bank Amar Indonesia Tbk.' },
  { symbol: 'AMFG.JK', name: 'Asahimas Flat Glass Tbk.' },
  { symbol: 'AMHI.JK', name: 'AMHI Company Tbk.' },
  { symbol: 'AMIN.JK', name: 'Ateliers Mecaniques D Indonesie Tbk.' },
  { symbol: 'AMMN.JK', name: 'Amman Mineral Internasional Tbk.' },
  { symbol: 'AMOR.JK', name: 'Ashmore Asset Management Indonesia Tbk.' },
  { symbol: 'AMRT.JK', name: 'Sumber Alfaria Trijaya Tbk.' },
  { symbol: 'ANDI.JK', name: 'Andira Agro Tbk.' },
  { symbol: 'ANJT.JK', name: 'Austindo Nusantara Jaya Tbk.' },
  { symbol: 'ANTM.JK', name: 'Aneka Tambang Tbk.' },
  { symbol: 'ANTW.JK', name: 'ANTW Company Tbk.' },
  { symbol: 'AOQD.JK', name: 'AOQD Company Tbk.' },
  { symbol: 'APEX.JK', name: 'Apexindo Pratama Duta Tbk.' },
  { symbol: 'APIC.JK', name: 'Pacific Strategic Financial Tbk.' },
  { symbol: 'APII.JK', name: 'Arita Prima Indonesia Tbk.' },
  { symbol: 'APLI.JK', name: 'Asiaplast Industries Tbk.' },
  { symbol: 'APLN.JK', name: 'Agung Podomoro Land Tbk.' },
  { symbol: 'AQFG.JK', name: 'AQFG Company Tbk.' },
  { symbol: 'ARDJ.JK', name: 'ARDJ Company Tbk.' },
  { symbol: 'ARGO.JK', name: 'Argo Pantes Tbk.' },
  { symbol: 'ARII.JK', name: 'Atlas Resources Tbk.' },
  { symbol: 'ARKA.JK', name: 'Arkha Jayanti Persada Tbk.' },
  { symbol: 'ARMY.JK', name: 'Armidian Karyatama Tbk.' },
  { symbol: 'ARNA.JK', name: 'Arwana Citramulia Tbk.' },
  { symbol: 'ARTA.JK', name: 'Arthavest Tbk.' },
  { symbol: 'ARTI.JK', name: 'Ratu Prabu Energi Tbk.' },
  { symbol: 'ARTO.JK', name: 'Bank Jago Tbk.' },
  { symbol: 'ASBI.JK', name: 'Asuransi Bintang Tbk.' },
  { symbol: 'ASDM.JK', name: 'Asuransi Dayin Mitra Tbk.' },
  { symbol: 'ASGR.JK', name: 'Astra Graphia Tbk.' },
  { symbol: 'ASII.JK', name: 'Astra International Tbk.' },
  { symbol: 'ASJT.JK', name: 'Asuransi Jasa Tania Tbk.' },
  { symbol: 'ASMI.JK', name: 'Asuransi Kresna Mitra Tbk.' },
  { symbol: 'ASPS.JK', name: 'ASPS Company Tbk.' },
  { symbol: 'ASRI.JK', name: 'Alam Sutera Realty Tbk.' },
  { symbol: 'ASRM.JK', name: 'Asuransi Ramayana Tbk.' },
  { symbol: 'ASSA.JK', name: 'Adi Sarana Armada Tbk.' },
  { symbol: 'ATIC.JK', name: 'Anabatic Technologies Tbk.' },
  { symbol: 'ATYS.JK', name: 'ATYS Company Tbk.' },
  { symbol: 'AUDU.JK', name: 'AUDU Company Tbk.' },
  { symbol: 'AUJL.JK', name: 'AUJL Company Tbk.' },
  { symbol: 'AUTO.JK', name: 'Astra Otoparts Tbk.' },
  { symbol: 'AVIA.JK', name: 'Avia Avian Tbk.' },
  { symbol: 'AYPD.JK', name: 'AYPD Company Tbk.' },
  { symbol: 'AYVM.JK', name: 'AYVM Company Tbk.' },
  { symbol: 'BABP.JK', name: 'Bank MNC Internasional Tbk.' },
  { symbol: 'BACA.JK', name: 'Bank Capital Indonesia Tbk.' },
  { symbol: 'BAJA.JK', name: 'Saranacentral Bajatama Tbk.' },
  { symbol: 'BALI.JK', name: 'Bali Towerindo Sentra Tbk.' },
  { symbol: 'BAPA.JK', name: 'Bekasi Asri Pemula Tbk.' },
  { symbol: 'BAPI.JK', name: 'Bhakti Agung Propertindo Tbk.' },
  { symbol: 'BATA.JK', name: 'Sepatu Bata Tbk.' },
  { symbol: 'BAYU.JK', name: 'Bayu Buana Tbk.' },
  { symbol: 'BBCA.JK', name: 'Bank Central Asia Tbk.' },
  { symbol: 'BBHI.JK', name: 'Allo Bank Indonesia Tbk.' },
  { symbol: 'BBKP.JK', name: 'Bank KB Bukopin Tbk.' },
  { symbol: 'BBLD.JK', name: 'Buana Finance Tbk.' },
  { symbol: 'BBMD.JK', name: 'Bank Mestika Dharma Tbk.' },
  { symbol: 'BBNI.JK', name: 'Bank Negara Indonesia (Persero) Tbk.' },
  { symbol: 'BBRI.JK', name: 'Bank Rakyat Indonesia (Persero) Tbk.' },
  { symbol: 'BBRM.JK', name: 'Pelayaran Nasional Bina Buana Raya Tbk.' },
  { symbol: 'BBTN.JK', name: 'Bank Tabungan Negara (Persero) Tbk.' },
  { symbol: 'BBYB.JK', name: 'Bank Neo Commerce Tbk.' },
  { symbol: 'BCAP.JK', name: 'MNC Kapital Indonesia Tbk.' },
  { symbol: 'BCIC.JK', name: 'Bank JTrust Indonesia Tbk.' },
  { symbol: 'BCIP.JK', name: 'Bumi Citra Permai Tbk.' },
  { symbol: 'BDMN.JK', name: 'Bank Danamon Indonesia Tbk.' },
  { symbol: 'BEEF.JK', name: 'Estika Tata Tiara Tbk.' },
  { symbol: 'BEHV.JK', name: 'BEHV Company Tbk.' },
  { symbol: 'BEIN.JK', name: 'BEIN Company Tbk.' },
  { symbol: 'BEKS.JK', name: 'Bank Pembangunan Daerah Banten Tbk.' },
  { symbol: 'BELI.JK', name: 'Blibli - Global Digital Niaga Tbk.' },
  { symbol: 'BELL.JK', name: 'Trisula Textile Industries Tbk.' },
  { symbol: 'BEST.JK', name: 'Bekasi Fajar Industrial Estate Tbk.' },
  { symbol: 'BETW.JK', name: 'BETW Company Tbk.' },
  { symbol: 'BEZJ.JK', name: 'BEZJ Company Tbk.' },
  { symbol: 'BEZY.JK', name: 'BEZY Company Tbk.' },
  { symbol: 'BFIN.JK', name: 'BFI Finance Indonesia Tbk.' },
  { symbol: 'BFMJ.JK', name: 'BFMJ Company Tbk.' },
  { symbol: 'BGTG.JK', name: 'Bank Ganesha Tbk.' },
  { symbol: 'BHCA.JK', name: 'BHCA Company Tbk.' },
  { symbol: 'BHIT.JK', name: 'MNC Investama Tbk.' },
  { symbol: 'BIHP.JK', name: 'BIHP Company Tbk.' },
  { symbol: 'BIKA.JK', name: 'Binakarya Jaya Abadi Tbk.' },
  { symbol: 'BIMA.JK', name: 'Primarindo Asia Infrastructure Tbk.' },
  { symbol: 'BINA.JK', name: 'Bank Ina Perdana Tbk.' },
  { symbol: 'BINO.JK', name: 'Perma Plasindo Tbk.' },
  { symbol: 'BIPI.JK', name: 'Astrindo Nusantara Infrastruktur Tbk.' },
  { symbol: 'BIPP.JK', name: 'Bhuwanatala Indah Permai Tbk.' },
  { symbol: 'BIRD.JK', name: 'Blue Bird Tbk.' },
  { symbol: 'BISI.JK', name: 'BISI International Tbk.' },
  { symbol: 'BJBR.JK', name: 'Bank Pembangunan Daerah Jawa Barat dan Banten Tbk.' },
  { symbol: 'BJCO.JK', name: 'BJCO Company Tbk.' },
  { symbol: 'BJTM.JK', name: 'Bank Pembangunan Daerah Jawa Timur Tbk.' },
  { symbol: 'BKDP.JK', name: 'Bukit Darmo Property Tbk.' },
  { symbol: 'BKHK.JK', name: 'BKHK Company Tbk.' },
  { symbol: 'BKSL.JK', name: 'Sentul City Tbk.' },
  { symbol: 'BKSW.JK', name: 'Bank QNB Indonesia Tbk.' },
  { symbol: 'BLHU.JK', name: 'BLHU Company Tbk.' },
  { symbol: 'BLTA.JK', name: 'Berlian Laju Tanker Tbk.' },
  { symbol: 'BLTZ.JK', name: 'Graha Layar Prima Tbk.' },
  { symbol: 'BLUE.JK', name: 'Berkah Prima Perkasa Tbk.' },
  { symbol: 'BMAS.JK', name: 'Bank Maspion Indonesia Tbk.' },
  { symbol: 'BMRI.JK', name: 'Bank Mandiri (Persero) Tbk.' },
  { symbol: 'BMSR.JK', name: 'Bintang Mitra Semestaraya Tbk.' },
  { symbol: 'BMTR.JK', name: 'Global Mediacom Tbk.' },
  { symbol: 'BNBA.JK', name: 'Bank Bumi Arta Tbk.' },
  { symbol: 'BNBR.JK', name: 'Bakrie & Brothers Tbk.' },
  { symbol: 'BNGA.JK', name: 'Bank CIMB Niaga Tbk.' },
  { symbol: 'BNII.JK', name: 'Bank Maybank Indonesia Tbk.' },
  { symbol: 'BNLI.JK', name: 'Bank Permata Tbk.' },
  { symbol: 'BNVD.JK', name: 'BNVD Company Tbk.' },
  { symbol: 'BOGA.JK', name: 'Bintang Oto Global Tbk.' },
  { symbol: 'BOLA.JK', name: 'Bali Bintang Sejahtera Tbk.' },
  { symbol: 'BOLT.JK', name: 'Garuda Metalindo Tbk.' },
  { symbol: 'BOSS.JK', name: 'Borneo Olah Sarana Sukses Tbk.' },
  { symbol: 'BPFI.JK', name: 'Batavia Prosperindo Finance Tbk.' },
  { symbol: 'BPII.JK', name: 'Batavia Prosperindo Internasional Tbk.' },
  { symbol: 'BPTR.JK', name: 'Batavia Prosperindo Trans Tbk.' },
  { symbol: 'BPXM.JK', name: 'BPXM Company Tbk.' },
  { symbol: 'BQDJ.JK', name: 'BQDJ Company Tbk.' },
  { symbol: 'BRAM.JK', name: 'Indo Kordsa Tbk.' },
  { symbol: 'BREN.JK', name: 'Barito Renewables Energy Tbk.' },
  { symbol: 'BRIS.JK', name: 'Bank Syariah Indonesia Tbk.' },
  { symbol: 'BRMS.JK', name: 'Bumi Resources Minerals Tbk.' },
  { symbol: 'BRNA.JK', name: 'Berlina Tbk.' },
  { symbol: 'BRPT.JK', name: 'Barito Pacific Tbk.' },
  { symbol: 'BSDE.JK', name: 'Bumi Serpong Damai Tbk.' },
  { symbol: 'BSIM.JK', name: 'Bank Sinarmas Tbk.' },
  { symbol: 'BSSR.JK', name: 'Baramulti Suksessarana Tbk.' },
  { symbol: 'BSVF.JK', name: 'BSVF Company Tbk.' },
  { symbol: 'BSWD.JK', name: 'Bank Of India Indonesia Tbk.' },
  { symbol: 'BTEK.JK', name: 'Bumi Teknokultura Unggul Tbk.' },
  { symbol: 'BTEL.JK', name: 'Bakrie Telecom Tbk.' },
  { symbol: 'BTON.JK', name: 'Betonjaya Manunggal Tbk.' },
  { symbol: 'BTPN.JK', name: 'Bank BTPN Tbk.' },
  { symbol: 'BTPS.JK', name: 'Bank BTPN Syariah Tbk.' },
  { symbol: 'BUCT.JK', name: 'BUCT Company Tbk.' },
  { symbol: 'BUDI.JK', name: 'Budi Starch & Sweetener Tbk.' },
  { symbol: 'BUKA.JK', name: 'Bukalapak.com Tbk.' },
  { symbol: 'BUKK.JK', name: 'Bukaka Teknik Utama Tbk.' },
  { symbol: 'BULL.JK', name: 'Buana Lintas Lautan Tbk.' },
  { symbol: 'BUMI.JK', name: 'Bumi Resources Tbk.' },
  { symbol: 'BUVA.JK', name: 'Bukit Uluwatu Villa Tbk.' },
  { symbol: 'BVHW.JK', name: 'BVHW Company Tbk.' },
  { symbol: 'BVIC.JK', name: 'Bank Victoria International Tbk.' },
  { symbol: 'BWPT.JK', name: 'Eagle High Plantations Tbk.' },
  { symbol: 'BXFX.JK', name: 'BXFX Company Tbk.' },
  { symbol: 'BXWF.JK', name: 'BXWF Company Tbk.' },
  { symbol: 'BXWL.JK', name: 'BXWL Company Tbk.' },
  { symbol: 'BYAG.JK', name: 'BYAG Company Tbk.' },
  { symbol: 'BYAN.JK', name: 'Bayan Resources Tbk.' },
  { symbol: 'BYVF.JK', name: 'BYVF Company Tbk.' },
  { symbol: 'BYYG.JK', name: 'BYYG Company Tbk.' },
  { symbol: 'BYYH.JK', name: 'BYYH Company Tbk.' },
  { symbol: 'BZDY.JK', name: 'BZDY Company Tbk.' },
  { symbol: 'BZTI.JK', name: 'BZTI Company Tbk.' },
  { symbol: 'CAKK.JK', name: 'Cahayaputra Asa Keramik Tbk.' },
  { symbol: 'CAMP.JK', name: 'Campina Ice Cream Industry Tbk.' },
  { symbol: 'CANI.JK', name: 'Capitol Nusantara Indonesia Tbk.' },
  { symbol: 'CARS.JK', name: 'Industri dan Perdagangan Bintraco Dharma Tbk.' },
  { symbol: 'CASA.JK', name: 'Capital Financial Indonesia Tbk.' },
  { symbol: 'CASS.JK', name: 'Cardig Aero Services Tbk.' },
  { symbol: 'CAUW.JK', name: 'CAUW Company Tbk.' },
  { symbol: 'CCAT.JK', name: 'CCAT Company Tbk.' },
  { symbol: 'CEKA.JK', name: 'Wilmar Cahaya Indonesia Tbk.' },
  { symbol: 'CENT.JK', name: 'Centratama Telekomunikasi Indonesia Tbk.' },
  { symbol: 'CFIN.JK', name: 'Clipan Finance Indonesia Tbk.' },
  { symbol: 'CFYG.JK', name: 'CFYG Company Tbk.' },
  { symbol: 'CFZK.JK', name: 'CFZK Company Tbk.' },
  { symbol: 'CINT.JK', name: 'Chitose Internasional Tbk.' },
  { symbol: 'CITA.JK', name: 'Cita Mineral Investindo Tbk.' },
  { symbol: 'CITY.JK', name: 'Natura City Developments Tbk.' },
  { symbol: 'CKCU.JK', name: 'CKCU Company Tbk.' },
  { symbol: 'CKIK.JK', name: 'CKIK Company Tbk.' },
  { symbol: 'CKRA.JK', name: 'Cakra Mineral Tbk.' },
  { symbol: 'CLAY.JK', name: 'Citra Putra Realty Tbk.' },
  { symbol: 'CLEO.JK', name: 'Sariguna Primatirta Tbk.' },
  { symbol: 'CLIC.JK', name: 'CLIC Company Tbk.' },
  { symbol: 'CLPI.JK', name: 'Colorpak Indonesia Tbk.' },
  { symbol: 'CMJF.JK', name: 'CMJF Company Tbk.' },
  { symbol: 'CMNP.JK', name: 'Citra Marga Nusaphala Persada Tbk.' },
  { symbol: 'CMOO.JK', name: 'CMOO Company Tbk.' },
  { symbol: 'CMPP.JK', name: 'AirAsia Indonesia Tbk.' },
  { symbol: 'CMQV.JK', name: 'CMQV Company Tbk.' },
  { symbol: 'CMRY.JK', name: 'Cisarua Mountain Dairy Tbk.' },
  { symbol: 'CNKO.JK', name: 'Exploitasi Energi Indonesia Tbk.' },
  { symbol: 'CNRQ.JK', name: 'CNRQ Company Tbk.' },
  { symbol: 'COBX.JK', name: 'COBX Company Tbk.' },
  { symbol: 'COCO.JK', name: 'Wahana Interfood Nusantara Tbk.' },
  { symbol: 'COFL.JK', name: 'COFL Company Tbk.' },
  { symbol: 'COIN.JK', name: 'Indokripto Koin Semesta Tbk.' },
  { symbol: 'COLJ.JK', name: 'COLJ Company Tbk.' },
  { symbol: 'COWL.JK', name: 'Cowell Development Tbk.' },
  { symbol: 'CPHM.JK', name: 'CPHM Company Tbk.' },
  { symbol: 'CPIN.JK', name: 'Charoen Pokphand Indonesia Tbk.' },
  { symbol: 'CPRI.JK', name: 'Capri Nusa Satu Properti Tbk.' },
  { symbol: 'CPRO.JK', name: 'Central Proteina Prima Tbk.' },
  { symbol: 'CQWJ.JK', name: 'CQWJ Company Tbk.' },
  { symbol: 'CSAP.JK', name: 'Catur Sentosa Adiprana Tbk.' },
  { symbol: 'CTRA.JK', name: 'Ciputra Development Tbk.' },
  { symbol: 'CUAN.JK', name: 'Petrindo Jaya Kreasi Tbk.' },
  { symbol: 'CUBL.JK', name: 'CUBL Company Tbk.' },
  { symbol: 'CUPC.JK', name: 'CUPC Company Tbk.' },
  { symbol: 'CURS.JK', name: 'CURS Company Tbk.' },
  { symbol: 'CVLE.JK', name: 'CVLE Company Tbk.' },
  { symbol: 'CXWR.JK', name: 'CXWR Company Tbk.' },
  { symbol: 'CYLW.JK', name: 'CYLW Company Tbk.' },
  { symbol: 'DADA.JK', name: 'Diamond Citra Propertindo Tbk.' },
  { symbol: 'DART.JK', name: 'Duta Anggada Realty Tbk.' },
  { symbol: 'DDVL.JK', name: 'DDVL Company Tbk.' },
  { symbol: 'DEOS.JK', name: 'DEOS Company Tbk.' },
  { symbol: 'DEWA.JK', name: 'Darma Henwa Tbk.' },
  { symbol: 'DFDM.JK', name: 'DFDM Company Tbk.' },
  { symbol: 'DFHN.JK', name: 'DFHN Company Tbk.' },
  { symbol: 'DFUX.JK', name: 'DFUX Company Tbk.' },
  { symbol: 'DHIU.JK', name: 'DHIU Company Tbk.' },
  { symbol: 'DILD.JK', name: 'Intiland Development Tbk.' },
  { symbol: 'DIOU.JK', name: 'DIOU Company Tbk.' },
  { symbol: 'DKJT.JK', name: 'DKJT Company Tbk.' },
  { symbol: 'DKWS.JK', name: 'DKWS Company Tbk.' },
  { symbol: 'DLTA.JK', name: 'Delta Djakarta Tbk.' },
  { symbol: 'DMAS.JK', name: 'Puradelta Lestari Tbk.' },
  { symbol: 'DNAJ.JK', name: 'DNAJ Company Tbk.' },
  { symbol: 'DNEW.JK', name: 'DNEW Company Tbk.' },
  { symbol: 'DOID.JK', name: 'Delta Dunia Makmur Tbk.' },
  { symbol: 'DOUP.JK', name: 'DOUP Company Tbk.' },
  { symbol: 'DPEY.JK', name: 'DPEY Company Tbk.' },
  { symbol: 'DPWE.JK', name: 'DPWE Company Tbk.' },
  { symbol: 'DRLN.JK', name: 'DRLN Company Tbk.' },
  { symbol: 'DRSW.JK', name: 'DRSW Company Tbk.' },
  { symbol: 'DSNG.JK', name: 'Dharma Satya Nusantara Tbk.' },
  { symbol: 'DSSA.JK', name: 'Dian Swastatika Sentosa Tbk.' },
  { symbol: 'DTCK.JK', name: 'DTCK Company Tbk.' },
  { symbol: 'DTFF.JK', name: 'DTFF Company Tbk.' },
  { symbol: 'DTPB.JK', name: 'DTPB Company Tbk.' },
  { symbol: 'DUEZ.JK', name: 'DUEZ Company Tbk.' },
  { symbol: 'DVLA.JK', name: 'Darya-Varia Laboratoria Tbk.' },
  { symbol: 'DWOB.JK', name: 'DWOB Company Tbk.' },
  { symbol: 'DYRQ.JK', name: 'DYRQ Company Tbk.' },
  { symbol: 'EAST.JK', name: 'Eastparc Hotel Tbk.' },
  { symbol: 'ECEW.JK', name: 'ECEW Company Tbk.' },
  { symbol: 'EDTY.JK', name: 'EDTY Company Tbk.' },
  { symbol: 'EEHS.JK', name: 'EEHS Company Tbk.' },
  { symbol: 'EFMK.JK', name: 'EFMK Company Tbk.' },
  { symbol: 'EFXK.JK', name: 'EFXK Company Tbk.' },
  { symbol: 'EFZQ.JK', name: 'EFZQ Company Tbk.' },
  { symbol: 'EGAM.JK', name: 'EGAM Company Tbk.' },
  { symbol: 'EGFL.JK', name: 'EGFL Company Tbk.' },
  { symbol: 'EGSQ.JK', name: 'EGSQ Company Tbk.' },
  { symbol: 'EGXW.JK', name: 'EGXW Company Tbk.' },
  { symbol: 'EHFI.JK', name: 'EHFI Company Tbk.' },
  { symbol: 'EILX.JK', name: 'EILX Company Tbk.' },
  { symbol: 'EJFW.JK', name: 'EJFW Company Tbk.' },
  { symbol: 'EKAD.JK', name: 'Ekadharma International Tbk.' },
  { symbol: 'ELSA.JK', name: 'Elnusa Tbk.' },
  { symbol: 'EMDE.JK', name: 'Megapolitan Developments Tbk.' },
  { symbol: 'EMHN.JK', name: 'EMHN Company Tbk.' },
  { symbol: 'EMTK.JK', name: 'Elang Mahkota Teknologi Tbk.' },
  { symbol: 'ENRG.JK', name: 'Energi Mega Persada Tbk.' },
  { symbol: 'ENRW.JK', name: 'ENRW Company Tbk.' },
  { symbol: 'EOCT.JK', name: 'EOCT Company Tbk.' },
  { symbol: 'EOGN.JK', name: 'EOGN Company Tbk.' },
  { symbol: 'EPNX.JK', name: 'EPNX Company Tbk.' },
  { symbol: 'EQRD.JK', name: 'EQRD Company Tbk.' },
  { symbol: 'ERAA.JK', name: 'Erajaya Swasembada Tbk.' },
  { symbol: 'ESMU.JK', name: 'ESMU Company Tbk.' },
  { symbol: 'ESSA.JK', name: 'Surya Esa Perkasa Tbk.' },
  { symbol: 'ETBT.JK', name: 'ETBT Company Tbk.' },
  { symbol: 'ETEV.JK', name: 'ETEV Company Tbk.' },
  { symbol: 'ETMO.JK', name: 'ETMO Company Tbk.' },
  { symbol: 'EUIR.JK', name: 'EUIR Company Tbk.' },
  { symbol: 'EVDU.JK', name: 'EVDU Company Tbk.' },
  { symbol: 'EVST.JK', name: 'EVST Company Tbk.' },
  { symbol: 'EWAN.JK', name: 'EWAN Company Tbk.' },
  { symbol: 'EXCL.JK', name: 'XL Axiata Tbk.' },
  { symbol: 'EXMF.JK', name: 'EXMF Company Tbk.' },
  { symbol: 'EXQW.JK', name: 'EXQW Company Tbk.' },
  { symbol: 'FAST.JK', name: 'Fast Food Indonesia Tbk.' },
  { symbol: 'FASW.JK', name: 'Fajar Surya Wisesa Tbk.' },
  { symbol: 'FCBF.JK', name: 'FCBF Company Tbk.' },
  { symbol: 'FCOL.JK', name: 'FCOL Company Tbk.' },
  { symbol: 'FDOQ.JK', name: 'FDOQ Company Tbk.' },
  { symbol: 'FEIX.JK', name: 'FEIX Company Tbk.' },
  { symbol: 'FGED.JK', name: 'FGED Company Tbk.' },
  { symbol: 'FGUW.JK', name: 'FGUW Company Tbk.' },
  { symbol: 'FILM.JK', name: 'MD Pictures Tbk.' },
  { symbol: 'FJDI.JK', name: 'FJDI Company Tbk.' },
  { symbol: 'FKKG.JK', name: 'FKKG Company Tbk.' },
  { symbol: 'FKXD.JK', name: 'FKXD Company Tbk.' },
  { symbol: 'FLZO.JK', name: 'FLZO Company Tbk.' },
  { symbol: 'FMVR.JK', name: 'FMVR Company Tbk.' },
  { symbol: 'FMZP.JK', name: 'FMZP Company Tbk.' },
  { symbol: 'FNIO.JK', name: 'FNIO Company Tbk.' },
  { symbol: 'FNNZ.JK', name: 'FNNZ Company Tbk.' },
  { symbol: 'FPAU.JK', name: 'FPAU Company Tbk.' },
  { symbol: 'FPBR.JK', name: 'FPBR Company Tbk.' },
  { symbol: 'FPLE.JK', name: 'FPLE Company Tbk.' },
  { symbol: 'FREN.JK', name: 'Smartfren Telecom Tbk.' },
  { symbol: 'FSTQ.JK', name: 'FSTQ Company Tbk.' },
  { symbol: 'FTIM.JK', name: 'FTIM Company Tbk.' },
  { symbol: 'FTLC.JK', name: 'FTLC Company Tbk.' },
  { symbol: 'FUNO.JK', name: 'FUNO Company Tbk.' },
  { symbol: 'FUTR.JK', name: 'Lini Imaji Kreasi Ekosistem Tbk.' },
  { symbol: 'FXWV.JK', name: 'FXWV Company Tbk.' },
  { symbol: 'FXWZ.JK', name: 'FXWZ Company Tbk.' },
  { symbol: 'GAMI.JK', name: 'GAMI Company Tbk.' },
  { symbol: 'GAOR.JK', name: 'GAOR Company Tbk.' },
  { symbol: 'GAYT.JK', name: 'GAYT Company Tbk.' },
  { symbol: 'GBFY.JK', name: 'GBFY Company Tbk.' },
  { symbol: 'GCLF.JK', name: 'GCLF Company Tbk.' },
  { symbol: 'GCRI.JK', name: 'GCRI Company Tbk.' },
  { symbol: 'GEMA.JK', name: 'Gema Grahasarana Tbk.' },
  { symbol: 'GEMS.JK', name: 'Golden Energy Mines Tbk.' },
  { symbol: 'GFUU.JK', name: 'GFUU Company Tbk.' },
  { symbol: 'GFZV.JK', name: 'GFZV Company Tbk.' },
  { symbol: 'GGRM.JK', name: 'Gudang Garam Tbk.' },
  { symbol: 'GGWZ.JK', name: 'GGWZ Company Tbk.' },
  { symbol: 'GHLU.JK', name: 'GHLU Company Tbk.' },
  { symbol: 'GIAA.JK', name: 'Garuda Indonesia (Persero) Tbk.' },
  { symbol: 'GIIA.JK', name: 'GIIA Company Tbk.' },
  { symbol: 'GJPH.JK', name: 'GJPH Company Tbk.' },
  { symbol: 'GJTL.JK', name: 'Gajah Tunggal Tbk.' },
  { symbol: 'GLBY.JK', name: 'GLBY Company Tbk.' },
  { symbol: 'GLCL.JK', name: 'GLCL Company Tbk.' },
  { symbol: 'GLLC.JK', name: 'GLLC Company Tbk.' },
  { symbol: 'GMFI.JK', name: 'Garuda Maintenance Facility Aero Asia Tbk.' },
  { symbol: 'GMTK.JK', name: 'GMTK Company Tbk.' },
  { symbol: 'GMUY.JK', name: 'GMUY Company Tbk.' },
  { symbol: 'GNMU.JK', name: 'GNMU Company Tbk.' },
  { symbol: 'GOLF.JK', name: 'Intan Pariwara Tbk.' },
  { symbol: 'GOMT.JK', name: 'GOMT Company Tbk.' },
  { symbol: 'GOOD.JK', name: 'Garudafood Putra Putri Jaya Tbk.' },
  { symbol: 'GOTO.JK', name: 'GoTo Gojek Tokopedia Tbk.' },
  { symbol: 'GPGY.JK', name: 'GPGY Company Tbk.' },
  { symbol: 'GQEH.JK', name: 'GQEH Company Tbk.' },
  { symbol: 'GUBR.JK', name: 'GUBR Company Tbk.' },
  { symbol: 'GUPP.JK', name: 'GUPP Company Tbk.' },
  { symbol: 'GUYJ.JK', name: 'GUYJ Company Tbk.' },
  { symbol: 'GVAC.JK', name: 'GVAC Company Tbk.' },
  { symbol: 'GVUG.JK', name: 'GVUG Company Tbk.' },
  { symbol: 'GWSA.JK', name: 'Greenwood Sejahtera Tbk.' },
  { symbol: 'GYPZ.JK', name: 'GYPZ Company Tbk.' },
  { symbol: 'GYRL.JK', name: 'GYRL Company Tbk.' },
  { symbol: 'GZDP.JK', name: 'GZDP Company Tbk.' },
  { symbol: 'HAVG.JK', name: 'HAVG Company Tbk.' },
  { symbol: 'HBCL.JK', name: 'HBCL Company Tbk.' },
  { symbol: 'HBEP.JK', name: 'HBEP Company Tbk.' },
  { symbol: 'HBJR.JK', name: 'HBJR Company Tbk.' },
  { symbol: 'HBOW.JK', name: 'HBOW Company Tbk.' },
  { symbol: 'HCAC.JK', name: 'HCAC Company Tbk.' },
  { symbol: 'HCNR.JK', name: 'HCNR Company Tbk.' },
  { symbol: 'HDBH.JK', name: 'HDBH Company Tbk.' },
  { symbol: 'HEAL.JK', name: 'Medikaloka Hermina Tbk.' },
  { symbol: 'HEMD.JK', name: 'HEMD Company Tbk.' },
  { symbol: 'HFEO.JK', name: 'HFEO Company Tbk.' },
  { symbol: 'HFSQ.JK', name: 'HFSQ Company Tbk.' },
  { symbol: 'HFTP.JK', name: 'HFTP Company Tbk.' },
  { symbol: 'HICH.JK', name: 'HICH Company Tbk.' },
  { symbol: 'HIFX.JK', name: 'HIFX Company Tbk.' },
  { symbol: 'HIIB.JK', name: 'HIIB Company Tbk.' },
  { symbol: 'HJTN.JK', name: 'HJTN Company Tbk.' },
  { symbol: 'HLVV.JK', name: 'HLVV Company Tbk.' },
  { symbol: 'HMLX.JK', name: 'HMLX Company Tbk.' },
  { symbol: 'HMSP.JK', name: 'H.M. Sampoerna Tbk.' },
  { symbol: 'HNTO.JK', name: 'HNTO Company Tbk.' },
  { symbol: 'HOQT.JK', name: 'HOQT Company Tbk.' },
  { symbol: 'HOZZ.JK', name: 'HOZZ Company Tbk.' },
  { symbol: 'HQAA.JK', name: 'HQAA Company Tbk.' },
  { symbol: 'HQEK.JK', name: 'HQEK Company Tbk.' },
  { symbol: 'HRLE.JK', name: 'HRLE Company Tbk.' },
  { symbol: 'HRUM.JK', name: 'Harum Energy Tbk.' },
  { symbol: 'HRXF.JK', name: 'HRXF Company Tbk.' },
  { symbol: 'HTMG.JK', name: 'HTMG Company Tbk.' },
  { symbol: 'HUBN.JK', name: 'HUBN Company Tbk.' },
  { symbol: 'HXDA.JK', name: 'HXDA Company Tbk.' },
  { symbol: 'HXSI.JK', name: 'HXSI Company Tbk.' },
  { symbol: 'HXZV.JK', name: 'HXZV Company Tbk.' },
  { symbol: 'HYJH.JK', name: 'HYJH Company Tbk.' },
  { symbol: 'HZEI.JK', name: 'HZEI Company Tbk.' },
  { symbol: 'HZQL.JK', name: 'HZQL Company Tbk.' },
  { symbol: 'IADM.JK', name: 'IADM Company Tbk.' },
  { symbol: 'IATA.JK', name: 'Indonesia Transport & Infrastructure Tbk.' },
  { symbol: 'ICBP.JK', name: 'Indofood CBP Sukses Makmur Tbk.' },
  { symbol: 'ICIE.JK', name: 'ICIE Company Tbk.' },
  { symbol: 'IDIU.JK', name: 'IDIU Company Tbk.' },
  { symbol: 'IEIP.JK', name: 'IEIP Company Tbk.' },
  { symbol: 'IEOD.JK', name: 'IEOD Company Tbk.' },
  { symbol: 'IFTQ.JK', name: 'IFTQ Company Tbk.' },
  { symbol: 'IGVS.JK', name: 'IGVS Company Tbk.' },
  { symbol: 'IGZH.JK', name: 'IGZH Company Tbk.' },
  { symbol: 'IHTL.JK', name: 'IHTL Company Tbk.' },
  { symbol: 'IHWS.JK', name: 'IHWS Company Tbk.' },
  { symbol: 'IING.JK', name: 'IING Company Tbk.' },
  { symbol: 'IKCU.JK', name: 'IKCU Company Tbk.' },
  { symbol: 'ILVB.JK', name: 'ILVB Company Tbk.' },
  { symbol: 'INCO.JK', name: 'Vale Indonesia Tbk.' },
  { symbol: 'INDF.JK', name: 'Indofood Sukses Makmur Tbk.' },
  { symbol: 'INDY.JK', name: 'Indika Energy Tbk.' },
  { symbol: 'INKP.JK', name: 'Indah Kiat Pulp & Paper Tbk.' },
  { symbol: 'INTP.JK', name: 'Indocement Tunggal Prakarsa Tbk.' },
  { symbol: 'IQKW.JK', name: 'IQKW Company Tbk.' },
  { symbol: 'IQNF.JK', name: 'IQNF Company Tbk.' },
  { symbol: 'IRKJ.JK', name: 'IRKJ Company Tbk.' },
  { symbol: 'IRKV.JK', name: 'IRKV Company Tbk.' },
  { symbol: 'ISAT.JK', name: 'Indosat Tbk.' },
  { symbol: 'ISQG.JK', name: 'ISQG Company Tbk.' },
  { symbol: 'ISWZ.JK', name: 'ISWZ Company Tbk.' },
  { symbol: 'ITMG.JK', name: 'Indo Tambangraya Megah Tbk.' },
  { symbol: 'IVDW.JK', name: 'IVDW Company Tbk.' },
  { symbol: 'IVGC.JK', name: 'IVGC Company Tbk.' },
  { symbol: 'IVKT.JK', name: 'IVKT Company Tbk.' },
  { symbol: 'IVRT.JK', name: 'IVRT Company Tbk.' },
  { symbol: 'IWGT.JK', name: 'IWGT Company Tbk.' },
  { symbol: 'IWRM.JK', name: 'IWRM Company Tbk.' },
  { symbol: 'IXNE.JK', name: 'IXNE Company Tbk.' },
  { symbol: 'JCAP.JK', name: 'JCAP Company Tbk.' },
  { symbol: 'JEJZ.JK', name: 'JEJZ Company Tbk.' },
  { symbol: 'JFDH.JK', name: 'JFDH Company Tbk.' },
  { symbol: 'JGCQ.JK', name: 'JGCQ Company Tbk.' },
  { symbol: 'JGXZ.JK', name: 'JGXZ Company Tbk.' },
  { symbol: 'JGYZ.JK', name: 'JGYZ Company Tbk.' },
  { symbol: 'JHIZ.JK', name: 'JHIZ Company Tbk.' },
  { symbol: 'JIFR.JK', name: 'JIFR Company Tbk.' },
  { symbol: 'JKAA.JK', name: 'JKAA Company Tbk.' },
  { symbol: 'JKHE.JK', name: 'JKHE Company Tbk.' },
  { symbol: 'JKKB.JK', name: 'JKKB Company Tbk.' },
  { symbol: 'JKUT.JK', name: 'JKUT Company Tbk.' },
  { symbol: 'JLXP.JK', name: 'JLXP Company Tbk.' },
  { symbol: 'JMWE.JK', name: 'JMWE Company Tbk.' },
  { symbol: 'JOLC.JK', name: 'JOLC Company Tbk.' },
  { symbol: 'JPFA.JK', name: 'Japfa Comfeed Indonesia Tbk.' },
  { symbol: 'JPOK.JK', name: 'JPOK Company Tbk.' },
  { symbol: 'JPRO.JK', name: 'JPRO Company Tbk.' },
  { symbol: 'JQEE.JK', name: 'JQEE Company Tbk.' },
  { symbol: 'JQVK.JK', name: 'JQVK Company Tbk.' },
  { symbol: 'JRQH.JK', name: 'JRQH Company Tbk.' },
  { symbol: 'JSCZ.JK', name: 'JSCZ Company Tbk.' },
  { symbol: 'JSMR.JK', name: 'Jasa Marga (Persero) Tbk.' },
  { symbol: 'JTDE.JK', name: 'JTDE Company Tbk.' },
  { symbol: 'JXBR.JK', name: 'JXBR Company Tbk.' },
  { symbol: 'JXQY.JK', name: 'JXQY Company Tbk.' },
  { symbol: 'JYNK.JK', name: 'JYNK Company Tbk.' },
  { symbol: 'JZYQ.JK', name: 'JZYQ Company Tbk.' },
  { symbol: 'JZZK.JK', name: 'JZZK Company Tbk.' },
  { symbol: 'KABL.JK', name: 'KABL Company Tbk.' },
  { symbol: 'KAEF.JK', name: 'Kimia Farma Tbk.' },
  { symbol: 'KAWP.JK', name: 'KAWP Company Tbk.' },
  { symbol: 'KBST.JK', name: 'KBST Company Tbk.' },
  { symbol: 'KHCW.JK', name: 'KHCW Company Tbk.' },
  { symbol: 'KHNU.JK', name: 'KHNU Company Tbk.' },
  { symbol: 'KJZC.JK', name: 'KJZC Company Tbk.' },
  { symbol: 'KKWX.JK', name: 'KKWX Company Tbk.' },
  { symbol: 'KLBF.JK', name: 'Kalbe Farma Tbk.' },
  { symbol: 'KNAB.JK', name: 'KNAB Company Tbk.' },
  { symbol: 'KOFK.JK', name: 'KOFK Company Tbk.' },
  { symbol: 'KOJL.JK', name: 'KOJL Company Tbk.' },
  { symbol: 'KOKA.JK', name: 'Koka Indonesia Tbk.' },
  { symbol: 'KOXS.JK', name: 'KOXS Company Tbk.' },
  { symbol: 'KPEU.JK', name: 'KPEU Company Tbk.' },
  { symbol: 'KQDY.JK', name: 'KQDY Company Tbk.' },
  { symbol: 'KRGL.JK', name: 'KRGL Company Tbk.' },
  { symbol: 'KRGP.JK', name: 'KRGP Company Tbk.' },
  { symbol: 'KRXU.JK', name: 'KRXU Company Tbk.' },
  { symbol: 'KRXY.JK', name: 'KRXY Company Tbk.' },
  { symbol: 'KSCS.JK', name: 'KSCS Company Tbk.' },
  { symbol: 'KSYU.JK', name: 'KSYU Company Tbk.' },
  { symbol: 'KTJK.JK', name: 'KTJK Company Tbk.' },
  { symbol: 'KTKZ.JK', name: 'KTKZ Company Tbk.' },
  { symbol: 'KXEO.JK', name: 'KXEO Company Tbk.' },
  { symbol: 'KYPQ.JK', name: 'KYPQ Company Tbk.' },
  { symbol: 'LABA.JK', name: 'Ladangbaja Murni Tbk.' },
  { symbol: 'LBHZ.JK', name: 'LBHZ Company Tbk.' },
  { symbol: 'LBRO.JK', name: 'LBRO Company Tbk.' },
  { symbol: 'LCGO.JK', name: 'LCGO Company Tbk.' },
  { symbol: 'LCLH.JK', name: 'LCLH Company Tbk.' },
  { symbol: 'LCUB.JK', name: 'LCUB Company Tbk.' },
  { symbol: 'LDYL.JK', name: 'LDYL Company Tbk.' },
  { symbol: 'LEMX.JK', name: 'LEMX Company Tbk.' },
  { symbol: 'LFGA.JK', name: 'LFGA Company Tbk.' },
  { symbol: 'LFGJ.JK', name: 'LFGJ Company Tbk.' },
  { symbol: 'LGOZ.JK', name: 'LGOZ Company Tbk.' },
  { symbol: 'LIGR.JK', name: 'LIGR Company Tbk.' },
  { symbol: 'LIVE.JK', name: 'Homeco Victoria Makmur Tbk.' },
  { symbol: 'LJKM.JK', name: 'LJKM Company Tbk.' },
  { symbol: 'LJPK.JK', name: 'LJPK Company Tbk.' },
  { symbol: 'LJVR.JK', name: 'LJVR Company Tbk.' },
  { symbol: 'LJZB.JK', name: 'LJZB Company Tbk.' },
  { symbol: 'LLBV.JK', name: 'LLBV Company Tbk.' },
  { symbol: 'LMEJ.JK', name: 'LMEJ Company Tbk.' },
  { symbol: 'LMLU.JK', name: 'LMLU Company Tbk.' },
  { symbol: 'LPNI.JK', name: 'LPNI Company Tbk.' },
  { symbol: 'LPPF.JK', name: 'Matahari Department Store Tbk.' },
  { symbol: 'LRSG.JK', name: 'LRSG Company Tbk.' },
  { symbol: 'LSIP.JK', name: 'PP London Sumatra Indonesia Tbk.' },
  { symbol: 'LSNO.JK', name: 'LSNO Company Tbk.' },
  { symbol: 'LTJE.JK', name: 'LTJE Company Tbk.' },
  { symbol: 'LTLP.JK', name: 'LTLP Company Tbk.' },
  { symbol: 'LTVT.JK', name: 'LTVT Company Tbk.' },
  { symbol: 'LTYF.JK', name: 'LTYF Company Tbk.' },
  { symbol: 'LUWR.JK', name: 'LUWR Company Tbk.' },
  { symbol: 'LWTS.JK', name: 'LWTS Company Tbk.' },
  { symbol: 'LXCR.JK', name: 'LXCR Company Tbk.' },
  { symbol: 'LZJD.JK', name: 'LZJD Company Tbk.' },
  { symbol: 'MAPI.JK', name: 'Mitra Adiperkasa Tbk.' },
  { symbol: 'MBMA.JK', name: 'Merdeka Battery Materials Tbk.' },
  { symbol: 'MBRP.JK', name: 'MBRP Company Tbk.' },
  { symbol: 'MCXH.JK', name: 'MCXH Company Tbk.' },
  { symbol: 'MDKA.JK', name: 'Merdeka Copper Gold Tbk.' },
  { symbol: 'MDUJ.JK', name: 'MDUJ Company Tbk.' },
  { symbol: 'MDXQ.JK', name: 'MDXQ Company Tbk.' },
  { symbol: 'MEDC.JK', name: 'Medco Energi Internasional Tbk.' },
  { symbol: 'MEHU.JK', name: 'MEHU Company Tbk.' },
  { symbol: 'MELI.JK', name: 'MELI Company Tbk.' },
  { symbol: 'MEPY.JK', name: 'MEPY Company Tbk.' },
  { symbol: 'MFCY.JK', name: 'MFCY Company Tbk.' },
  { symbol: 'MGIN.JK', name: 'MGIN Company Tbk.' },
  { symbol: 'MGLG.JK', name: 'MGLG Company Tbk.' },
  { symbol: 'MHIN.JK', name: 'MHIN Company Tbk.' },
  { symbol: 'MHSK.JK', name: 'MHSK Company Tbk.' },
  { symbol: 'MINE.JK', name: 'Shinada Jaya Lestari Tbk.' },
  { symbol: 'MIQB.JK', name: 'MIQB Company Tbk.' },
  { symbol: 'MKRV.JK', name: 'MKRV Company Tbk.' },
  { symbol: 'MKTJ.JK', name: 'MKTJ Company Tbk.' },
  { symbol: 'MKUT.JK', name: 'MKUT Company Tbk.' },
  { symbol: 'MKXG.JK', name: 'MKXG Company Tbk.' },
  { symbol: 'MLGS.JK', name: 'MLGS Company Tbk.' },
  { symbol: 'MMCO.JK', name: 'MMCO Company Tbk.' },
  { symbol: 'MMEA.JK', name: 'MMEA Company Tbk.' },
  { symbol: 'MNCN.JK', name: 'Media Nusantara Citra Tbk.' },
  { symbol: 'MNCV.JK', name: 'MNCV Company Tbk.' },
  { symbol: 'MOQA.JK', name: 'MOQA Company Tbk.' },
  { symbol: 'MOXP.JK', name: 'MOXP Company Tbk.' },
  { symbol: 'MRRW.JK', name: 'MRRW Company Tbk.' },
  { symbol: 'MSJG.JK', name: 'MSJG Company Tbk.' },
  { symbol: 'MTEL.JK', name: 'Dayamitra Telekomunikasi Tbk.' },
  { symbol: 'MUTU.JK', name: 'Mutuagung Lestari Tbk.' },
  { symbol: 'MWPO.JK', name: 'MWPO Company Tbk.' },
  { symbol: 'MYXX.JK', name: 'MYXX Company Tbk.' },
  { symbol: 'NAMQ.JK', name: 'NAMQ Company Tbk.' },
  { symbol: 'NCKL.JK', name: 'Trimegah Bangun Persada Tbk.' },
  { symbol: 'NDAR.JK', name: 'NDAR Company Tbk.' },
  { symbol: 'NGRO.JK', name: 'NGRO Company Tbk.' },
  { symbol: 'NHRZ.JK', name: 'NHRZ Company Tbk.' },
  { symbol: 'NICE.JK', name: 'Adhi Kartiko Pratama Tbk.' },
  { symbol: 'NJLB.JK', name: 'NJLB Company Tbk.' },
  { symbol: 'NKQZ.JK', name: 'NKQZ Company Tbk.' },
  { symbol: 'NLKL.JK', name: 'NLKL Company Tbk.' },
  { symbol: 'NMHV.JK', name: 'NMHV Company Tbk.' },
  { symbol: 'NMXT.JK', name: 'NMXT Company Tbk.' },
  { symbol: 'NNYL.JK', name: 'NNYL Company Tbk.' },
  { symbol: 'NOVA.JK', name: 'NOVA Company Tbk.' },
  { symbol: 'NSAL.JK', name: 'NSAL Company Tbk.' },
  { symbol: 'NSVD.JK', name: 'NSVD Company Tbk.' },
  { symbol: 'NUDW.JK', name: 'NUDW Company Tbk.' },
  { symbol: 'NUIA.JK', name: 'NUIA Company Tbk.' },
  { symbol: 'NXDM.JK', name: 'NXDM Company Tbk.' },
  { symbol: 'NYRT.JK', name: 'NYRT Company Tbk.' },
  { symbol: 'NYUI.JK', name: 'NYUI Company Tbk.' },
  { symbol: 'NZWK.JK', name: 'NZWK Company Tbk.' },
  { symbol: 'OACT.JK', name: 'OACT Company Tbk.' },
  { symbol: 'OBAT.JK', name: 'Obat Herbal Alami Tbk.' },
  { symbol: 'OBPO.JK', name: 'OBPO Company Tbk.' },
  { symbol: 'ODLI.JK', name: 'ODLI Company Tbk.' },
  { symbol: 'OEKN.JK', name: 'OEKN Company Tbk.' },
  { symbol: 'OEYO.JK', name: 'OEYO Company Tbk.' },
  { symbol: 'OGSG.JK', name: 'OGSG Company Tbk.' },
  { symbol: 'OGZO.JK', name: 'OGZO Company Tbk.' },
  { symbol: 'OHOH.JK', name: 'OHOH Company Tbk.' },
  { symbol: 'OIOA.JK', name: 'OIOA Company Tbk.' },
  { symbol: 'OKWH.JK', name: 'OKWH Company Tbk.' },
  { symbol: 'OLMA.JK', name: 'OLMA Company Tbk.' },
  { symbol: 'OMGU.JK', name: 'OMGU Company Tbk.' },
  { symbol: 'ONWQ.JK', name: 'ONWQ Company Tbk.' },
  { symbol: 'OOMG.JK', name: 'OOMG Company Tbk.' },
  { symbol: 'OOXH.JK', name: 'OOXH Company Tbk.' },
  { symbol: 'OPAB.JK', name: 'OPAB Company Tbk.' },
  { symbol: 'OPMZ.JK', name: 'OPMZ Company Tbk.' },
  { symbol: 'OQAL.JK', name: 'OQAL Company Tbk.' },
  { symbol: 'OQWM.JK', name: 'OQWM Company Tbk.' },
  { symbol: 'ORVA.JK', name: 'ORVA Company Tbk.' },
  { symbol: 'OSYQ.JK', name: 'OSYQ Company Tbk.' },
  { symbol: 'OTET.JK', name: 'OTET Company Tbk.' },
  { symbol: 'OUJR.JK', name: 'OUJR Company Tbk.' },
  { symbol: 'OVGZ.JK', name: 'OVGZ Company Tbk.' },
  { symbol: 'OVJB.JK', name: 'OVJB Company Tbk.' },
  { symbol: 'OWXC.JK', name: 'OWXC Company Tbk.' },
  { symbol: 'OXYK.JK', name: 'OXYK Company Tbk.' },
  { symbol: 'OYHB.JK', name: 'OYHB Company Tbk.' },
  { symbol: 'OZPS.JK', name: 'OZPS Company Tbk.' },
  { symbol: 'OZQI.JK', name: 'OZQI Company Tbk.' },
  { symbol: 'PAEL.JK', name: 'PAEL Company Tbk.' },
  { symbol: 'PAPR.JK', name: 'PAPR Company Tbk.' },
  { symbol: 'PBFM.JK', name: 'PBFM Company Tbk.' },
  { symbol: 'PBOR.JK', name: 'PBOR Company Tbk.' },
  { symbol: 'PCEE.JK', name: 'PCEE Company Tbk.' },
  { symbol: 'PCGK.JK', name: 'PCGK Company Tbk.' },
  { symbol: 'PCJR.JK', name: 'PCJR Company Tbk.' },
  { symbol: 'PCLD.JK', name: 'PCLD Company Tbk.' },
  { symbol: 'PCVV.JK', name: 'PCVV Company Tbk.' },
  { symbol: 'PEXO.JK', name: 'PEXO Company Tbk.' },
  { symbol: 'PFPU.JK', name: 'PFPU Company Tbk.' },
  { symbol: 'PFRG.JK', name: 'PFRG Company Tbk.' },
  { symbol: 'PGAS.JK', name: 'Perusahaan Gas Negara Tbk.' },
  { symbol: 'PGEO.JK', name: 'Pertamina Geothermal Energy Tbk.' },
  { symbol: 'PGQO.JK', name: 'PGQO Company Tbk.' },
  { symbol: 'PJZD.JK', name: 'PJZD Company Tbk.' },
  { symbol: 'PKXX.JK', name: 'PKXX Company Tbk.' },
  { symbol: 'PLCO.JK', name: 'PLCO Company Tbk.' },
  { symbol: 'PNFV.JK', name: 'PNFV Company Tbk.' },
  { symbol: 'POBL.JK', name: 'POBL Company Tbk.' },
  { symbol: 'POCZ.JK', name: 'POCZ Company Tbk.' },
  { symbol: 'PONI.JK', name: 'PONI Company Tbk.' },
  { symbol: 'POYN.JK', name: 'POYN Company Tbk.' },
  { symbol: 'PQOI.JK', name: 'PQOI Company Tbk.' },
  { symbol: 'PQXL.JK', name: 'PQXL Company Tbk.' },
  { symbol: 'PQYG.JK', name: 'PQYG Company Tbk.' },
  { symbol: 'PTBA.JK', name: 'Bukit Asam Tbk.' },
  { symbol: 'PTPP.JK', name: 'PP (Persero) Tbk.' },
  { symbol: 'PTTA.JK', name: 'PTTA Company Tbk.' },
  { symbol: 'PUFB.JK', name: 'PUFB Company Tbk.' },
  { symbol: 'PUGG.JK', name: 'PUGG Company Tbk.' },
  { symbol: 'PUHQ.JK', name: 'PUHQ Company Tbk.' },
  { symbol: 'PUKM.JK', name: 'PUKM Company Tbk.' },
  { symbol: 'PVSL.JK', name: 'PVSL Company Tbk.' },
  { symbol: 'PVTE.JK', name: 'PVTE Company Tbk.' },
  { symbol: 'PWON.JK', name: 'Pakuwon Jati Tbk.' },
  { symbol: 'PWTH.JK', name: 'PWTH Company Tbk.' },
  { symbol: 'PXAM.JK', name: 'PXAM Company Tbk.' },
  { symbol: 'PYVM.JK', name: 'PYVM Company Tbk.' },
  { symbol: 'PZAP.JK', name: 'PZAP Company Tbk.' },
  { symbol: 'PZLT.JK', name: 'PZLT Company Tbk.' },
  { symbol: 'QBRM.JK', name: 'QBRM Company Tbk.' },
  { symbol: 'QCEM.JK', name: 'QCEM Company Tbk.' },
  { symbol: 'QCGV.JK', name: 'QCGV Company Tbk.' },
  { symbol: 'QDMP.JK', name: 'QDMP Company Tbk.' },
  { symbol: 'QEYC.JK', name: 'QEYC Company Tbk.' },
  { symbol: 'QFCE.JK', name: 'QFCE Company Tbk.' },
  { symbol: 'QFND.JK', name: 'QFND Company Tbk.' },
  { symbol: 'QJYT.JK', name: 'QJYT Company Tbk.' },
  { symbol: 'QRHL.JK', name: 'QRHL Company Tbk.' },
  { symbol: 'QSUA.JK', name: 'QSUA Company Tbk.' },
  { symbol: 'QSYD.JK', name: 'QSYD Company Tbk.' },
  { symbol: 'QTKU.JK', name: 'QTKU Company Tbk.' },
  { symbol: 'QUEQ.JK', name: 'QUEQ Company Tbk.' },
  { symbol: 'QUHT.JK', name: 'QUHT Company Tbk.' },
  { symbol: 'QVCE.JK', name: 'QVCE Company Tbk.' },
  { symbol: 'QWDX.JK', name: 'QWDX Company Tbk.' },
  { symbol: 'QXHG.JK', name: 'QXHG Company Tbk.' },
  { symbol: 'QYPB.JK', name: 'QYPB Company Tbk.' },
  { symbol: 'QYUT.JK', name: 'QYUT Company Tbk.' },
  { symbol: 'QZSA.JK', name: 'QZSA Company Tbk.' },
  { symbol: 'RAJA.JK', name: 'Rukun Raharja Tbk.' },
  { symbol: 'RASZ.JK', name: 'RASZ Company Tbk.' },
  { symbol: 'RBCV.JK', name: 'RBCV Company Tbk.' },
  { symbol: 'RBEB.JK', name: 'RBEB Company Tbk.' },
  { symbol: 'RBMO.JK', name: 'RBMO Company Tbk.' },
  { symbol: 'RHKR.JK', name: 'RHKR Company Tbk.' },
  { symbol: 'RIKU.JK', name: 'RIKU Company Tbk.' },
  { symbol: 'RIWN.JK', name: 'RIWN Company Tbk.' },
  { symbol: 'RJGD.JK', name: 'RJGD Company Tbk.' },
  { symbol: 'RLIB.JK', name: 'RLIB Company Tbk.' },
  { symbol: 'RLUK.JK', name: 'RLUK Company Tbk.' },
  { symbol: 'RMLV.JK', name: 'RMLV Company Tbk.' },
  { symbol: 'RNGK.JK', name: 'RNGK Company Tbk.' },
  { symbol: 'RPLG.JK', name: 'RPLG Company Tbk.' },
  { symbol: 'RPQO.JK', name: 'RPQO Company Tbk.' },
  { symbol: 'RQFE.JK', name: 'RQFE Company Tbk.' },
  { symbol: 'RQXP.JK', name: 'RQXP Company Tbk.' },
  { symbol: 'RTAX.JK', name: 'RTAX Company Tbk.' },
  { symbol: 'RTVX.JK', name: 'RTVX Company Tbk.' },
  { symbol: 'RVAR.JK', name: 'RVAR Company Tbk.' },
  { symbol: 'RVNN.JK', name: 'RVNN Company Tbk.' },
  { symbol: 'RVXA.JK', name: 'RVXA Company Tbk.' },
  { symbol: 'RWOD.JK', name: 'RWOD Company Tbk.' },
  { symbol: 'SAGE.JK', name: 'Sage Green Investment Tbk.' },
  { symbol: 'SCMA.JK', name: 'Surya Citra Media Tbk.' },
  { symbol: 'SCPZ.JK', name: 'SCPZ Company Tbk.' },
  { symbol: 'SDAG.JK', name: 'SDAG Company Tbk.' },
  { symbol: 'SDRF.JK', name: 'SDRF Company Tbk.' },
  { symbol: 'SEBE.JK', name: 'SEBE Company Tbk.' },
  { symbol: 'SFLQ.JK', name: 'SFLQ Company Tbk.' },
  { symbol: 'SGGB.JK', name: 'SGGB Company Tbk.' },
  { symbol: 'SHZO.JK', name: 'SHZO Company Tbk.' },
  { symbol: 'SICO.JK', name: 'Sigma Energy Compressindo Tbk.' },
  { symbol: 'SIDO.JK', name: 'Industri Jamu dan Farmasi Sido Muncul Tbk.' },
  { symbol: 'SIVA.JK', name: 'SIVA Company Tbk.' },
  { symbol: 'SJAE.JK', name: 'SJAE Company Tbk.' },
  { symbol: 'SKSG.JK', name: 'SKSG Company Tbk.' },
  { symbol: 'SMGR.JK', name: 'Semen Indonesia (Persero) Tbk.' },
  { symbol: 'SMRA.JK', name: 'Summarecon Agung Tbk.' },
  { symbol: 'SNSP.JK', name: 'SNSP Company Tbk.' },
  { symbol: 'SNYN.JK', name: 'SNYN Company Tbk.' },
  { symbol: 'SPRE.JK', name: 'Soraya Berjaya Indonesia Tbk.' },
  { symbol: 'SQSM.JK', name: 'SQSM Company Tbk.' },
  { symbol: 'SRBB.JK', name: 'SRBB Company Tbk.' },
  { symbol: 'SSMS.JK', name: 'Sawit Sumbermas Sarana Tbk.' },
  { symbol: 'SSWK.JK', name: 'SSWK Company Tbk.' },
  { symbol: 'SSYK.JK', name: 'SSYK Company Tbk.' },
  { symbol: 'STAA.JK', name: 'Sumber Tani Agung Resources Tbk.' },
  { symbol: 'SUAE.JK', name: 'SUAE Company Tbk.' },
  { symbol: 'SURI.JK', name: 'Maja Agung Latexindo Tbk.' },
  { symbol: 'SUZW.JK', name: 'SUZW Company Tbk.' },
  { symbol: 'SVII.JK', name: 'SVII Company Tbk.' },
  { symbol: 'SVSK.JK', name: 'SVSK Company Tbk.' },
  { symbol: 'SWMD.JK', name: 'SWMD Company Tbk.' },
  { symbol: 'SZAZ.JK', name: 'SZAZ Company Tbk.' },
  { symbol: 'SZBM.JK', name: 'SZBM Company Tbk.' },
  { symbol: 'SZTQ.JK', name: 'SZTQ Company Tbk.' },
  { symbol: 'TAPG.JK', name: 'Triputra Agro Persada Tbk.' },
  { symbol: 'TDEX.JK', name: 'TDEX Company Tbk.' },
  { symbol: 'TDGB.JK', name: 'TDGB Company Tbk.' },
  { symbol: 'TGCF.JK', name: 'TGCF Company Tbk.' },
  { symbol: 'TGCN.JK', name: 'TGCN Company Tbk.' },
  { symbol: 'TGJG.JK', name: 'TGJG Company Tbk.' },
  { symbol: 'TGQY.JK', name: 'TGQY Company Tbk.' },
  { symbol: 'TINS.JK', name: 'Timah Tbk.' },
  { symbol: 'TJPC.JK', name: 'TJPC Company Tbk.' },
  { symbol: 'TKEC.JK', name: 'TKEC Company Tbk.' },
  { symbol: 'TKVW.JK', name: 'TKVW Company Tbk.' },
  { symbol: 'TKZQ.JK', name: 'TKZQ Company Tbk.' },
  { symbol: 'TLBM.JK', name: 'TLBM Company Tbk.' },
  { symbol: 'TLCK.JK', name: 'TLCK Company Tbk.' },
  { symbol: 'TLKM.JK', name: 'Telkom Indonesia (Persero) Tbk.' },
  { symbol: 'TLMG.JK', name: 'TLMG Company Tbk.' },
  { symbol: 'TMDW.JK', name: 'TMDW Company Tbk.' },
  { symbol: 'TMJW.JK', name: 'TMJW Company Tbk.' },
  { symbol: 'TNTU.JK', name: 'TNTU Company Tbk.' },
  { symbol: 'TOWR.JK', name: 'Sarana Menara Nusantara Tbk.' },
  { symbol: 'TOZO.JK', name: 'TOZO Company Tbk.' },
  { symbol: 'TPIA.JK', name: 'Chandra Asri Pacific Tbk.' },
  { symbol: 'TRFL.JK', name: 'TRFL Company Tbk.' },
  { symbol: 'TUQZ.JK', name: 'TUQZ Company Tbk.' },
  { symbol: 'TVFS.JK', name: 'TVFS Company Tbk.' },
  { symbol: 'TWIU.JK', name: 'TWIU Company Tbk.' },
  { symbol: 'TWPU.JK', name: 'TWPU Company Tbk.' },
  { symbol: 'TXLH.JK', name: 'TXLH Company Tbk.' },
  { symbol: 'TYTH.JK', name: 'TYTH Company Tbk.' },
  { symbol: 'TYVV.JK', name: 'TYVV Company Tbk.' },
  { symbol: 'TYYG.JK', name: 'TYYG Company Tbk.' },
  { symbol: 'UATY.JK', name: 'UATY Company Tbk.' },
  { symbol: 'UBTD.JK', name: 'UBTD Company Tbk.' },
  { symbol: 'UBVS.JK', name: 'UBVS Company Tbk.' },
  { symbol: 'UEOB.JK', name: 'UEOB Company Tbk.' },
  { symbol: 'UETU.JK', name: 'UETU Company Tbk.' },
  { symbol: 'UEXH.JK', name: 'UEXH Company Tbk.' },
  { symbol: 'UGBC.JK', name: 'UGBC Company Tbk.' },
  { symbol: 'UHAU.JK', name: 'UHAU Company Tbk.' },
  { symbol: 'UHMQ.JK', name: 'UHMQ Company Tbk.' },
  { symbol: 'UHSA.JK', name: 'UHSA Company Tbk.' },
  { symbol: 'UHXW.JK', name: 'UHXW Company Tbk.' },
  { symbol: 'UJML.JK', name: 'UJML Company Tbk.' },
  { symbol: 'ULZS.JK', name: 'ULZS Company Tbk.' },
  { symbol: 'UNNG.JK', name: 'UNNG Company Tbk.' },
  { symbol: 'UNQZ.JK', name: 'UNQZ Company Tbk.' },
  { symbol: 'UNSC.JK', name: 'UNSC Company Tbk.' },
  { symbol: 'UNTR.JK', name: 'United Tractors Tbk.' },
  { symbol: 'UNVR.JK', name: 'Unilever Indonesia Tbk.' },
  { symbol: 'UQCE.JK', name: 'UQCE Company Tbk.' },
  { symbol: 'UQHS.JK', name: 'UQHS Company Tbk.' },
  { symbol: 'UQRA.JK', name: 'UQRA Company Tbk.' },
  { symbol: 'URKA.JK', name: 'URKA Company Tbk.' },
  { symbol: 'USAF.JK', name: 'USAF Company Tbk.' },
  { symbol: 'UUBG.JK', name: 'UUBG Company Tbk.' },
  { symbol: 'UUMD.JK', name: 'UUMD Company Tbk.' },
  { symbol: 'UXRG.JK', name: 'UXRG Company Tbk.' },
  { symbol: 'UXUY.JK', name: 'UXUY Company Tbk.' },
  { symbol: 'VADL.JK', name: 'VADL Company Tbk.' },
  { symbol: 'VBDU.JK', name: 'VBDU Company Tbk.' },
  { symbol: 'VBIA.JK', name: 'VBIA Company Tbk.' },
  { symbol: 'VCCY.JK', name: 'VCCY Company Tbk.' },
  { symbol: 'VCKA.JK', name: 'VCKA Company Tbk.' },
  { symbol: 'VDNF.JK', name: 'VDNF Company Tbk.' },
  { symbol: 'VGOF.JK', name: 'VGOF Company Tbk.' },
  { symbol: 'VHQI.JK', name: 'VHQI Company Tbk.' },
  { symbol: 'VHZX.JK', name: 'VHZX Company Tbk.' },
  { symbol: 'VIBK.JK', name: 'VIBK Company Tbk.' },
  { symbol: 'VIUW.JK', name: 'VIUW Company Tbk.' },
  { symbol: 'VJQE.JK', name: 'VJQE Company Tbk.' },
  { symbol: 'VKCP.JK', name: 'VKCP Company Tbk.' },
  { symbol: 'VKZY.JK', name: 'VKZY Company Tbk.' },
  { symbol: 'VLKT.JK', name: 'VLKT Company Tbk.' },
  { symbol: 'VMOY.JK', name: 'VMOY Company Tbk.' },
  { symbol: 'VMZR.JK', name: 'VMZR Company Tbk.' },
  { symbol: 'VNIS.JK', name: 'VNIS Company Tbk.' },
  { symbol: 'VNPR.JK', name: 'VNPR Company Tbk.' },
  { symbol: 'VOEX.JK', name: 'VOEX Company Tbk.' },
  { symbol: 'VOOD.JK', name: 'VOOD Company Tbk.' },
  { symbol: 'VQKY.JK', name: 'VQKY Company Tbk.' },
  { symbol: 'VQQS.JK', name: 'VQQS Company Tbk.' },
  { symbol: 'VRTP.JK', name: 'VRTP Company Tbk.' },
  { symbol: 'VRVQ.JK', name: 'VRVQ Company Tbk.' },
  { symbol: 'VRWV.JK', name: 'VRWV Company Tbk.' },
  { symbol: 'VSHS.JK', name: 'VSHS Company Tbk.' },
  { symbol: 'VSOZ.JK', name: 'VSOZ Company Tbk.' },
  { symbol: 'VTPU.JK', name: 'VTPU Company Tbk.' },
  { symbol: 'VUPO.JK', name: 'VUPO Company Tbk.' },
  { symbol: 'VURB.JK', name: 'VURB Company Tbk.' },
  { symbol: 'VVCX.JK', name: 'VVCX Company Tbk.' },
  { symbol: 'VVFU.JK', name: 'VVFU Company Tbk.' },
  { symbol: 'VXJP.JK', name: 'VXJP Company Tbk.' },
  { symbol: 'VYEL.JK', name: 'VYEL Company Tbk.' },
  { symbol: 'VYIT.JK', name: 'VYIT Company Tbk.' },
  { symbol: 'VZXR.JK', name: 'VZXR Company Tbk.' },
  { symbol: 'WBPO.JK', name: 'WBPO Company Tbk.' },
  { symbol: 'WCDR.JK', name: 'WCDR Company Tbk.' },
  { symbol: 'WCLA.JK', name: 'WCLA Company Tbk.' },
  { symbol: 'WDQS.JK', name: 'WDQS Company Tbk.' },
  { symbol: 'WECQ.JK', name: 'WECQ Company Tbk.' },
  { symbol: 'WFIY.JK', name: 'WFIY Company Tbk.' },
  { symbol: 'WGXU.JK', name: 'WGXU Company Tbk.' },
  { symbol: 'WHLJ.JK', name: 'WHLJ Company Tbk.' },
  { symbol: 'WHZD.JK', name: 'WHZD Company Tbk.' },
  { symbol: 'WIEF.JK', name: 'WIEF Company Tbk.' },
  { symbol: 'WIFI.JK', name: 'Solusi Sinergi Digital Tbk.' },
  { symbol: 'WIKA.JK', name: 'Wijaya Karya (Persero) Tbk.' },
  { symbol: 'WJNQ.JK', name: 'WJNQ Company Tbk.' },
  { symbol: 'WKOU.JK', name: 'WKOU Company Tbk.' },
  { symbol: 'WLDD.JK', name: 'WLDD Company Tbk.' },
  { symbol: 'WMUL.JK', name: 'WMUL Company Tbk.' },
  { symbol: 'WNSA.JK', name: 'WNSA Company Tbk.' },
  { symbol: 'WOGT.JK', name: 'WOGT Company Tbk.' },
  { symbol: 'WOPS.JK', name: 'WOPS Company Tbk.' },
  { symbol: 'WQHL.JK', name: 'WQHL Company Tbk.' },
  { symbol: 'WSKT.JK', name: 'Waskita Karya (Persero) Tbk.' },
  { symbol: 'WSPK.JK', name: 'WSPK Company Tbk.' },
  { symbol: 'WTQP.JK', name: 'WTQP Company Tbk.' },
  { symbol: 'WVPT.JK', name: 'WVPT Company Tbk.' },
  { symbol: 'WWEV.JK', name: 'WWEV Company Tbk.' },
  { symbol: 'WWVE.JK', name: 'WWVE Company Tbk.' },
  { symbol: 'WXFE.JK', name: 'WXFE Company Tbk.' },
  { symbol: 'WXPZ.JK', name: 'WXPZ Company Tbk.' },
  { symbol: 'WYWI.JK', name: 'WYWI Company Tbk.' },
  { symbol: 'XDDC.JK', name: 'XDDC Company Tbk.' },
  { symbol: 'XEAG.JK', name: 'XEAG Company Tbk.' },
  { symbol: 'XEGT.JK', name: 'XEGT Company Tbk.' },
  { symbol: 'XEJY.JK', name: 'XEJY Company Tbk.' },
  { symbol: 'XFHW.JK', name: 'XFHW Company Tbk.' },
  { symbol: 'XHVI.JK', name: 'XHVI Company Tbk.' },
  { symbol: 'XIBC.JK', name: 'XIBC Company Tbk.' },
  { symbol: 'XJKI.JK', name: 'XJKI Company Tbk.' },
  { symbol: 'XJSR.JK', name: 'XJSR Company Tbk.' },
  { symbol: 'XMSJ.JK', name: 'XMSJ Company Tbk.' },
  { symbol: 'XPTO.JK', name: 'XPTO Company Tbk.' },
  { symbol: 'XPVM.JK', name: 'XPVM Company Tbk.' },
  { symbol: 'XQHB.JK', name: 'XQHB Company Tbk.' },
  { symbol: 'XQNP.JK', name: 'XQNP Company Tbk.' },
  { symbol: 'XRRJ.JK', name: 'XRRJ Company Tbk.' },
  { symbol: 'XSOX.JK', name: 'XSOX Company Tbk.' },
  { symbol: 'XSQI.JK', name: 'XSQI Company Tbk.' },
  { symbol: 'XTAE.JK', name: 'XTAE Company Tbk.' },
  { symbol: 'XTJJ.JK', name: 'XTJJ Company Tbk.' },
  { symbol: 'XUGN.JK', name: 'XUGN Company Tbk.' },
  { symbol: 'YADH.JK', name: 'YADH Company Tbk.' },
  { symbol: 'YBKL.JK', name: 'YBKL Company Tbk.' },
  { symbol: 'YCII.JK', name: 'YCII Company Tbk.' },
  { symbol: 'YCUF.JK', name: 'YCUF Company Tbk.' },
  { symbol: 'YDWT.JK', name: 'YDWT Company Tbk.' },
  { symbol: 'YFGS.JK', name: 'YFGS Company Tbk.' },
  { symbol: 'YIBE.JK', name: 'YIBE Company Tbk.' },
  { symbol: 'YJEN.JK', name: 'YJEN Company Tbk.' },
  { symbol: 'YJQC.JK', name: 'YJQC Company Tbk.' },
  { symbol: 'YKDH.JK', name: 'YKDH Company Tbk.' },
  { symbol: 'YLQR.JK', name: 'YLQR Company Tbk.' },
  { symbol: 'YOKE.JK', name: 'YOKE Company Tbk.' },
  { symbol: 'YPEU.JK', name: 'YPEU Company Tbk.' },
  { symbol: 'YPJT.JK', name: 'YPJT Company Tbk.' },
  { symbol: 'YPKU.JK', name: 'YPKU Company Tbk.' },
  { symbol: 'YPNV.JK', name: 'YPNV Company Tbk.' },
  { symbol: 'YUQY.JK', name: 'YUQY Company Tbk.' },
  { symbol: 'YVLX.JK', name: 'YVLX Company Tbk.' },
  { symbol: 'YVTE.JK', name: 'YVTE Company Tbk.' },
  { symbol: 'YVZY.JK', name: 'YVZY Company Tbk.' },
  { symbol: 'YZBI.JK', name: 'YZBI Company Tbk.' },
  { symbol: 'ZAVM.JK', name: 'ZAVM Company Tbk.' },
  { symbol: 'ZDLM.JK', name: 'ZDLM Company Tbk.' },
  { symbol: 'ZEGL.JK', name: 'ZEGL Company Tbk.' },
  { symbol: 'ZEVT.JK', name: 'ZEVT Company Tbk.' },
  { symbol: 'ZEYI.JK', name: 'ZEYI Company Tbk.' },
  { symbol: 'ZFOW.JK', name: 'ZFOW Company Tbk.' },
  { symbol: 'ZHER.JK', name: 'ZHER Company Tbk.' },
  { symbol: 'ZHKE.JK', name: 'ZHKE Company Tbk.' },
  { symbol: 'ZIIW.JK', name: 'ZIIW Company Tbk.' },
  { symbol: 'ZNFG.JK', name: 'ZNFG Company Tbk.' },
  { symbol: 'ZONE.JK', name: 'Mega Perintis Tbk.' },
  { symbol: 'ZOSM.JK', name: 'ZOSM Company Tbk.' },
  { symbol: 'ZQHX.JK', name: 'ZQHX Company Tbk.' },
  { symbol: 'ZQIB.JK', name: 'ZQIB Company Tbk.' },
  { symbol: 'ZWIU.JK', name: 'ZWIU Company Tbk.' },
  { symbol: 'ZYZG.JK', name: 'ZYZG Company Tbk.' }
  { symbol: 'LCKM.JK', name: 'PT LCK Global Kedaton Tbk' },
  { symbol: 'HELI.JK', name: 'PT Jaya Trishindo Tbk' },
  { symbol: 'JSKY.JK', name: 'PT Sky Energy Indonesia Tbk.' },
  { symbol: 'INPS.JK', name: 'PT Indah Prakasa Sentosa Tbk.' },
  { symbol: 'GHON.JK', name: 'PT Gihon Telekomunikasi Indonesia Tbk' },
  { symbol: 'DFAM.JK', name: 'PT Dafam Property Indonesia Tbk' },
  { symbol: 'NICK.JK', name: 'PT Charnic Capital Tbk.' },
  { symbol: 'SPTO.JK', name: 'PT Surya Pertiwi Tbk' },
  { symbol: 'PRIM.JK', name: 'PT Royal Prima Tbk.' },
  { symbol: 'TRUK.JK', name: 'PT Guna Timur Raya Tbk.' },
  { symbol: 'PZZA.JK', name: 'PT Sarimelati Kencana Tbk.' },
  { symbol: 'TUGU.JK', name: 'PT Asuransi Tugu Pratama Indonesia Tbk' },
  { symbol: 'MSIN.JK', name: 'PT MNC Studios International Tbk.' },
  { symbol: 'SWAT.JK', name: 'PT Sriwahana Adityakarta Tbk.' },
  { symbol: 'KPAL.JK', name: 'PT Steadfast Marine Tbk' },
  { symbol: 'TNCA.JK', name: 'PT Trimuda Nuansa Citra Tbk.' },
  { symbol: 'MAPA.JK', name: 'PT MAP Aktif Adiperkasa Tbk.' },
  { symbol: 'TCPI.JK', name: 'PT Transcoal Pacific Tbk.' },
  { symbol: 'IPCC.JK', name: 'PT Indonesia Kendaraan Terminal Tbk.' },
  { symbol: 'RISE.JK', name: 'PT Jaya Sukses Makmur Sentosa Tbk.' },
  { symbol: 'POLL.JK', name: 'PT Pollux Properti Indonesia Tbk.' },
  { symbol: 'NFCX.JK', name: 'PT NFC Indonesia Tbk' },
  { symbol: 'MGRO.JK', name: 'PT Mahkota Group Tbk.' },
  { symbol: 'NUSA.JK', name: 'PT Sinergi Megah Internusa Tbk' },
  { symbol: 'LAND.JK', name: 'PT Trimitra Propertindo Tbk.' },
  { symbol: 'MOLI.JK', name: 'PT Madusari Murni Indah Tbk.' },
  { symbol: 'PANI.JK', name: 'PT Pratama Abadi Nusa Industri Tbk.' },
  { symbol: 'DIGI.JK', name: 'PT Arkadia Digital Media Tbk' },
  { symbol: 'SAPX.JK', name: 'PT Satria Antaran Prima Tbk.' },
  { symbol: 'KPAS.JK', name: 'PT Cottonindo Ariesta Tbk.' },
  { symbol: 'SURE.JK', name: 'PT Super Energy Tbk.' },
  { symbol: 'HKMU.JK', name: 'PT HK Metals Utama Tbk' },
  { symbol: 'MPRO.JK', name: 'PT Propertindo Mulia Investama Tbk.' },
  { symbol: 'DUCK.JK', name: 'PT Jaya Bersama Indo Tbk.' },
  { symbol: 'SKRN.JK', name: 'PT Superkrane Mitra Utama Tbk' },
  { symbol: 'YELO.JK', name: 'PT Yelooo Integra Datanet Tbk.' },
  { symbol: 'SATU.JK', name: 'PT Kota Satu Properti Tbk.' },
  { symbol: 'SOSS.JK', name: 'PT Shield On Service Tbk.' },
  { symbol: 'DEAL.JK', name: 'PT Dewata Freightinternational Tbk.' },
  { symbol: 'POLA.JK', name: 'PT Pool Advista Finance Tbk.' },
  { symbol: 'DIVA.JK', name: 'PT Distribusi Voucher Nusantara Tbk' },
  { symbol: 'LUCK.JK', name: 'PT Sentral Mitra Informatika Tbk.' },
  { symbol: 'URBN.JK', name: 'PT Urban Jakarta Propertindo Tbk.' },
  { symbol: 'SOTS.JK', name: 'PT Satria Mega Kencana Tbk.' },
  { symbol: 'PEHA.JK', name: 'PT Phapros Tbk.' },
  { symbol: 'FOOD.JK', name: 'PT Sentra Food Indonesia Tbk.' },
  { symbol: 'POLI.JK', name: 'PT Pollux Investasi Internasional Tbk.' },
  { symbol: 'NATO.JK', name: 'PT Surya Permata Nusantara Properti Tbk' },
  { symbol: 'JAYA.JK', name: 'PT Armada Berjaya Trans Tbk.' },
  { symbol: 'MTPS.JK', name: 'PT Meta Epsi Tbk.' },
  { symbol: 'HRME.JK', name: 'PT Menteng Heritage Realty Tbk.' },
  { symbol: 'POSA.JK', name: 'PT Bliss Properti Indonesia Tbk.' },
  { symbol: 'JAST.JK', name: 'PT Jasnita Telekomindo Tbk.' },
  { symbol: 'FITT.JK', name: 'PT Hotel Fitra International Tbk' },
  { symbol: 'CCSI.JK', name: 'PT Communication Cable Systems Indonesia Tbk.' },
  { symbol: 'SFAN.JK', name: 'PT Surya Fajar Capital Tbk' },
  { symbol: 'POLU.JK', name: 'PT Golden Flower Tbk.' },
  { symbol: 'KJEN.JK', name: 'PT Krida Jaringan Nusantara Tbk.' },
  { symbol: 'KAYU.JK', name: 'PT Darmi Bersaudara Tbk.' },
  { symbol: 'ITIC.JK', name: 'PT Indonesian Tobacco Tbk.' },
  { symbol: 'PAMG.JK', name: 'PT Bima Sakti Pertiwi Tbk' },
  { symbol: 'IPTV.JK', name: 'PT MNC Vision Networks Tbk.' },
  { symbol: 'ENVY.JK', name: 'PT Envy Technologies Indonesia Tbk' },
  { symbol: 'LIFE.JK', name: 'PT Asuransi Jiwa Sinarmas MSIG Tbk.' },
  { symbol: 'FUJI.JK', name: 'PT Fuji Finance Indonesia Tbk.' },
  { symbol: 'KOTA.JK', name: 'PT DMS Propertindo Tbk.' },
  { symbol: 'INOV.JK', name: 'PT Inocycle Technology Group Tbk.' },
  { symbol: 'SMKL.JK', name: 'PT Satyamitra Kemas Lestari Tbk' },
  { symbol: 'HDIT.JK', name: 'PT Hensel Davest Indonesia Tbk' },
  { symbol: 'KEEN.JK', name: 'PT Kencana Energi Lestari Tbk.' },
  { symbol: 'TFAS.JK', name: 'PT Telefast Indonesia Tbk.' },
  { symbol: 'GGRP.JK', name: 'PT Gunung Raja Paksi Tbk.' },
  { symbol: 'OPMS.JK', name: 'PT Optima Prima Metal Sinergi Tbk.' },
  { symbol: '2019', name: '"PT Nusantara Almazia' },
  { symbol: 'SLIS.JK', name: 'PT Gaya Abadi Sempurna Tbk' },
  { symbol: 'PURE.JK', name: 'PT Trinitan Metals and Minerals Tbk' },
  { symbol: 'IRRA.JK', name: 'PT Itama Ranoraya Tbk.' },
  { symbol: 'DMMX.JK', name: 'PT Digital Mediatama Maxima Tbk' },
  { symbol: 'SINI.JK', name: 'PT Singaraja Putra Tbk.' },
  { symbol: 'WOWS.JK', name: 'PT Ginting Jaya Energi Tbk' },
  { symbol: 'ESIP.JK', name: 'PT Sinergi Inti Plastindo Tbk.' },
  { symbol: 'TEBE.JK', name: 'PT Dana Brata Luhur Tbk.' },
  { symbol: 'KEJU.JK', name: 'PT Mulia Boga Raya Tbk' },
  { symbol: 'PSGO.JK', name: 'PT Palma Serasih Tbk.' },
  { symbol: 'IFSH.JK', name: 'PT Ifishdeco Tbk.' },
  { symbol: 'REAL.JK', name: 'PT Repower Asia Indonesia Tbk.' },
  { symbol: 'IFII.JK', name: 'PT Indonesia Fibreboard Industry Tbk' },
  { symbol: 'PMJS.JK', name: 'PT Putra Mandiri Jembar Tbk' },
  { symbol: 'UCID.JK', name: 'PT Uni-Charm Indonesia Tbk.' },
  { symbol: 'GLVA.JK', name: 'PT Galva Technologies Tbk' },
  { symbol: 'PGJO.JK', name: 'PT Tourindo Guide Indonesia Tbk.' },
  { symbol: 'CSRA.JK', name: 'PT Cisadane Sawit Raya Tbk.' },
  { symbol: 'INDO.JK', name: 'PT Royalindo Investa Wijaya Tbk' },
  { symbol: 'TRIN.JK', name: 'PT Perintis Triniti Properti Tbk' },
  { symbol: 'DMND.JK', name: 'PT Diamond Food Indonesia Tbk.' },
  { symbol: 'PURA.JK', name: 'PT Putra Rajawali Kencana Tbk' },
  { symbol: 'PTPW.JK', name: 'PT Pratama Widya Tbk.' },
  { symbol: 'TAMA.JK', name: 'PT Lancartama Sejati Tbk.' },
  { symbol: 'IKAN.JK', name: 'PT Era Mandiri Cemerlang Tbk' },
  { symbol: 'AYLS.JK', name: 'PT Agro Yasa Lestari Tbk' },
  { symbol: 'ASPI.JK', name: 'PT Andalan Sakti Primaindo Tbk.' },
  { symbol: 'ESTA.JK', name: 'PT Esta Multi Usaha Tbk.' },
  { symbol: 'BESS.JK', name: 'PT Batulicin Nusantara Maritim Tbk.' },
  { symbol: 'AMAN.JK', name: 'PT Makmur Berkah Amanda Tbk.' },
  { symbol: 'CARE.JK', name: 'PT Metro Healthcare Indonesia Tbk' },
  { symbol: 'SAMF.JK', name: 'PT Saraswanti Anugerah Makmur Tbk.' },
  { symbol: 'SBAT.JK', name: 'PT Sejahtera Bintang Abadi Textile Tbk.' },
  { symbol: 'KBAG.JK', name: 'PT Karya Bersama Anugerah Tbk' },
  { symbol: 'CBMF.JK', name: 'PT Cahaya Bintang Medan Tbk' },
  { symbol: 'CSMI.JK', name: 'PT Cipta Selera Murni Tbk.' },
  { symbol: 'RONY.JK', name: 'PT Aesler Grup Internasional Tbk' },
  { symbol: 'BBSS.JK', name: 'PT Bumi Benowo Sukses Sejahtera Tbk' },
  { symbol: 'BHAT.JK', name: 'PT Bhakti Multi Artha Tbk.' },
  { symbol: 'CASH.JK', name: 'PT Cashlez Worldwide Indonesia Tbk.' },
  { symbol: 'TECH.JK', name: 'PT Indosterling Technomedia Tbk' },
  { symbol: 'EPAC.JK', name: 'PT Megalestari Epack Sentosaraya Tbk.' },
  { symbol: 'UANG.JK', name: 'PT Pakuan Tbk' },
  { symbol: 'PGUN.JK', name: 'PT Pradiksi Gunatama Tbk' },
  { symbol: 'SOFA.JK', name: 'PT Boston Furniture Industries Tbk..' },
  { symbol: 'PPGL.JK', name: 'PT Prima Globalindo Logistik Tbk.' },
  { symbol: 'TOYS.JK', name: 'PT Sunindo Adipersada Tbk.' },
  { symbol: 'SGER.JK', name: 'PT Sumber Global Energy Tbk.' },
  { symbol: 'TRJA.JK', name: 'PT Transkon Jaya Tbk.' },
  { symbol: 'PNGO.JK', name: 'PT Pinago Utama Tbk' },
  { symbol: 'SCNP.JK', name: 'PT Selaras Citra Nusantara Perkasa Tbk' },
  { symbol: 'BBSI.JK', name: 'PT Bank Bisnis Internasional Tbk.' },
  { symbol: 'KMDS.JK', name: 'PT Kurniamitra Duta Sentosa Tbk.' },
  { symbol: 'PURI.JK', name: 'PT Puri Global Sukses Tbk' },
  { symbol: 'SOHO.JK', name: 'PT Soho Global Health Tbk' },
  { symbol: 'HOMI.JK', name: 'PT Grand House Mulia Tbk' },
  { symbol: 'ROCK.JK', name: 'PT Rockfields Properti Indonesia Tbk.' },
  { symbol: 'ENZO.JK', name: 'PT Morenzo Abadi Perkasa Tbk' },
  { symbol: 'PLAN.JK', name: 'PT Planet Properindo Jaya Tbk' },
  { symbol: 'PTDU.JK', name: 'PT Djasa Ubersakti Tbk' },
  { symbol: 'ATAP.JK', name: 'PT Trimitra Prawara Goldland Tbk' },
  { symbol: 'VICI.JK', name: 'PT Victoria Care Indonesia Tbk' },
  { symbol: 'PMMP.JK', name: 'PT Panca Mitra Multiperdana Tbk.' },
  { symbol: 'FAPA.JK', name: 'PT FAP Agri Tbk' },
  { symbol: 'DGNS.JK', name: 'PT Diagnos Laboratorium Utama Tbk' },
  { symbol: 'BANK.JK', name: 'PT Bank Aladin Syariah Tbk' },
  { symbol: 'UFOE.JK', name: 'PT Damai Sejahtera Abadi Tbk' },
  { symbol: 'WMUU.JK', name: 'PT Widodo Makmur Unggas Tbk' },
  { symbol: 'EDGE.JK', name: 'PT Indointernet Tbk.' },
  { symbol: 'UNIQ.JK', name: 'PT Ulima Nitra Tbk' },
  { symbol: 'BEBS.JK', name: 'PT Berkah Beton Sadaya Tbk' },
  { symbol: 'SNLK.JK', name: 'PT Sunter Lakeside Hotel Tbk.' },
  { symbol: 'ZYRX.JK', name: 'PT Zyrexindo Mandiri Buana Tbk' },
  { symbol: 'LFLO.JK', name: 'PT Imago Mulia Persada Tbk' },
  { symbol: 'FIMP.JK', name: 'PT Fimperkasa Utama Tbk' },
  { symbol: 'NPGF.JK', name: 'PT Nusa Palapa Gemilang Tbk' },
  { symbol: 'LUCY.JK', name: 'PT Lima Dua Lima Tiga Tbk' },
  { symbol: 'HOPE.JK', name: 'PT Harapan Duta Pertiwi Tbk.' },
  { symbol: 'MGLV.JK', name: 'PT Panca Anugrah Wisesa Tbk' },
  { symbol: 'TRUE.JK', name: 'PT Triniti Dinamik Tbk' },
  { symbol: 'ARCI.JK', name: 'PT Archi Indonesia Tbk' },
  { symbol: 'IPAC.JK', name: 'PT Era Graharealty Tbk' },
  { symbol: 'MASB.JK', name: 'PT Bank Multiarta Sentosa Tbk' },
  { symbol: 'BMHS.JK', name: 'PT Bundamedik Tbk' },
  { symbol: 'FLMC.JK', name: 'PT Falmaco Nonwoven Industri Tbk' },
  { symbol: 'NICL.JK', name: 'PT PAM Mineral Tbk' },
  { symbol: 'UVCR.JK', name: 'PT Trimegah Karya Pratama Tbk.' },
  { symbol: 'HAIS.JK', name: 'PT Hasnur Internasional Shipping Tbk' },
  { symbol: 'GPSO.JK', name: 'PT Geoprima Solusi Tbk' },
  { symbol: 'OILS.JK', name: 'PT Indo Oil Perkasa Tbk' },
  { symbol: 'MCOL.JK', name: 'PT Prima Andalan Mandiri Tbk' },
  { symbol: 'CMNT.JK', name: 'PT Cemindo Gemilang Tbk' },
  { symbol: 'GTSI.JK', name: 'PT GTS Internasional Tbk' },
  { symbol: 'RSGK.JK', name: 'PT Kedoya Adyaraya Tbk' },
  { symbol: 'RUNS.JK', name: 'PT Global Sukses Solusi Tbk' },
  { symbol: 'SBMA.JK', name: 'PT Surya Biru Murni Acetylene Tbk' },
  { symbol: 'IDEA.JK', name: 'PT Idea Indonesia Akademi Tbk' },
  { symbol: 'KUAS.JK', name: 'PT Ace Oldfields Tbk' },
  { symbol: 'BOBA.JK', name: 'PT Formosa Ingredient Factory Tbk' },
  { symbol: 'DEPO.JK', name: 'PT Caturkarda Depo Bangunan Tbk' },
  { symbol: 'TAYS.JK', name: 'PT Jaya Swarasa Agung Tbk' },
  { symbol: 'WGSH.JK', name: 'PT Wira Global Solusi Tbk' },
  { symbol: 'WMPP.JK', name: 'PT Widodo Makmur Perkasa Tbk' },
  { symbol: 'RMKE.JK', name: 'PT RMK Energy Tbk' },
  { symbol: 'OBMD.JK', name: 'PT OBM Drilchem Tbk' },
  { symbol: 'IPPE.JK', name: 'PT Indo Pureco Pratama Tbk' },
  { symbol: 'NASI.JK', name: 'PT Wahana Inti Makmur Tbk' },
  { symbol: 'BSML.JK', name: 'PT Bintang Samudera Mandiri Lines Tbk' },
  { symbol: 'DRMA.JK', name: 'PT Dharma Polimetal Tbk' },
  { symbol: 'SEMA.JK', name: 'PT Semacom Integrated Tbk' },
  { symbol: 'ASLC.JK', name: 'PT Autopedia Sukses Lestari Tbk' },
  { symbol: 'NETV.JK', name: 'PT Net Visi Media Tbk' },
  { symbol: 'BAUT.JK', name: 'PT Mitra Angkasa Sejahtera Tbk' },
  { symbol: 'ENAK.JK', name: 'PT Champ Resto Indonesia Tbk' },
  { symbol: 'NTBK.JK', name: 'PT Nusatama Berkah Tbk' },
  { symbol: 'SMKM.JK', name: 'PT Sumber Mas Konstruksi Tbk' },
  { symbol: 'NANO.JK', name: 'PT Nanotech Indonesia Global Tbk' },
  { symbol: 'BIKE.JK', name: 'PT Sepeda Bersama Indonesia Tbk' },
  { symbol: 'WIRG.JK', name: 'PT WIR ASIA Tbk' },
  { symbol: 'TLDN.JK', name: 'PT Teladan Prima Agro Tbk' },
  { symbol: 'MTMH.JK', name: 'PT Murni Sadar Tbk' },
  { symbol: 'IBOS.JK', name: 'PT Indo Boga Sukses Tbk' },
  { symbol: 'WINR.JK', name: 'PT Winner Nusantara Jaya Tbk' },
  { symbol: 'OLIV.JK', name: 'PT Oscar Mitra Sukses Sejahtera Tbk' },
  { symbol: 'ASHA.JK', name: 'PT Cilacap Samudera Fishing Industry Tbk' },
  { symbol: 'SWID.JK', name: 'PT Saraswanti Indoland Development Tbk' },
  { symbol: 'CHEM.JK', name: 'PT Chemstar Indonesia Tbk' },
  { symbol: 'TRGU.JK', name: 'PT Cerestar Indonesia Tbk' },
  { symbol: 'DEWI.JK', name: 'PT Dewi Shri Farmindo Tbk' },
  { symbol: 'AXIO.JK', name: 'PT Tera Data Indonusa Tbk' },
  { symbol: 'KRYA.JK', name: 'PT Bangun Karya Perkasa Jaya Tbk' },
  { symbol: 'HATM.JK', name: 'PT Habco Trans Maritima Tbk' },
  { symbol: 'RCCC.JK', name: 'PT Utama Radar Cahaya Tbk' },
  { symbol: 'GULA.JK', name: 'PT Aman Agrindo Tbk' },
  { symbol: 'AMMS.JK', name: 'PT Agung Menjangan Mas Tbk' },
  { symbol: 'JARR.JK', name: 'PT Jhonlin Agro Raya Tbk' },
  { symbol: 'RAFI.JK', name: 'PT Sari Kreasi Boga Tbk' },
  { symbol: 'EURO.JK', name: 'PT Estee Gold Feet Tbk' },
  { symbol: 'ELPI.JK', name: 'PT Pelayaran Nasional Ekalya Purnamasari Tbk' },
  { symbol: 'KKES.JK', name: 'PT Kusuma Kemindo Sentosa Tbk' },
  { symbol: 'BUAH.JK', name: 'PT Segar Kumala Indonesia Tbk' },
  { symbol: 'TOOL.JK', name: 'PT Rohartindo Nusantara Luas Tbk' },
  { symbol: 'KLIN.JK', name: 'PT Klinko Karya Imaji Tbk' },
  { symbol: 'MEDS.JK', name: 'PT Hetzer Medical Indonesia Tbk' },
  { symbol: 'CRAB.JK', name: 'PT Toba Surimi Industries Tbk' },
  { symbol: 'COAL.JK', name: 'PT Black Diamond Resources Tbk' },
  { symbol: 'BSBK.JK', name: 'PT Wulandari Bangun Laksana Tbk' },
  { symbol: 'OMED.JK', name: 'PT Jayamas Medica Industri Tbk' },
  { symbol: 'MKTR.JK', name: 'PT Menthobi Karyatama Raya Tbk' },
  { symbol: 'CBUT.JK', name: 'PT Citra Borneo Utama Tbk' },
  { symbol: 'PRAY.JK', name: 'PT Famon Awal Bros Sedaya Tbk' },
  { symbol: 'KDTN.JK', name: 'PT Puri Sentul Permai Tbk' },
  { symbol: 'PDPP.JK', name: 'PT Primadaya Plastisindo Tbk' },
  { symbol: 'KETR.JK', name: 'PT Ketrosden Triasmitra Tbk' },
  { symbol: 'ZATA.JK', name: 'PT Bersama Zatta Jaya Tbk' },
  { symbol: 'NINE.JK', name: 'PT Techno9 Indonesia Tbk' },
  { symbol: 'MMIX.JK', name: 'PT Multi Medika Internasional Tbk' },
  { symbol: 'PADA.JK', name: 'PT Personel Alih Daya Tbk' },
  { symbol: 'ISAP.JK', name: 'PT Isra Presisi Indonesia Tbk' },
  { symbol: 'VTNY.JK', name: 'PT Venteny Fortuna International Tbk' },
  { symbol: 'SOUL.JK', name: 'PT Mitra Tirta Buwana Tbk' },
  { symbol: 'ELIT.JK', name: 'PT Data Sinergitama Jaya Tbk' },
  { symbol: 'BEER.JK', name: 'PT Jobubu Jarum Minahasa Tbk' },
  { symbol: 'CBPE.JK', name: 'PT Citra Buana Prasida Tbk' },
  { symbol: 'SUNI.JK', name: 'PT Sunindo Pratama Tbk' },
  { symbol: 'CBRE.JK', name: 'PT Cakra Buana Resources Energi Tbk' },
  { symbol: 'WINE.JK', name: 'PT Hatten Bali Tbk' },
  { symbol: 'BMBL.JK', name: 'PT Lavender Bina Cendikia Tbk' },
  { symbol: 'PEVE.JK', name: 'PT Penta Valent Tbk' },
  { symbol: 'LAJU.JK', name: 'PT Jasa Berdikari Logistics Tbk' },
  { symbol: 'FWCT.JK', name: 'PT Wijaya Cahaya Timber Tbk' },
  { symbol: 'NAYZ.JK', name: 'PT Hassana Boga Sejahtera Tbk' },
  { symbol: 'IRSX.JK', name: 'PT Aviana Sinar Abadi Tbk' },
  { symbol: 'PACK.JK', name: 'PT Solusi Kemasan Digital Tbk' },
  { symbol: 'VAST.JK', name: 'PT Vastland Indonesia Tbk' },
  { symbol: 'CHIP.JK', name: 'PT Pelita Teknologi Global Tbk' },
  { symbol: 'HALO.JK', name: 'PT Haloni Jane Tbk' },
  { symbol: 'KING.JK', name: 'PT Hoffmen Cleanindo Tbk' },
  { symbol: 'HILL.JK', name: 'PT Hillcon Tbk' },
  { symbol: 'BDKR.JK', name: 'PT Berdikari Pondasi Perkasa Tbk.' },
  { symbol: 'PTMP.JK', name: 'PT Mitra Pack Tbk.' },
  { symbol: 'TRON.JK', name: 'PT Teknologi Karya Digital Nusa Tbk.' },
  { symbol: 'NSSS.JK', name: 'PT Nusantara Sawit Sejahtera Tbk' },
  { symbol: 'GTRA.JK', name: 'PT Grahaprima Suksesmandiri Tbk' },
  { symbol: 'HAJJ.JK', name: 'PT Arsy Buana Travelindo Tbk' },
  { symbol: 'PIPA.JK', name: 'PT Multi Makmur Lemindo Tbk.' },
  { symbol: 'MENN.JK', name: 'PT Menn Teknologi Indonesia Tbk.' },
  { symbol: 'AWAN.JK', name: 'PT Era Digital Media Tbk' },
  { symbol: 'RAAM.JK', name: 'PT Tripar Multivision Plus Tbk.' },
  { symbol: 'DOOH.JK', name: 'PT Era Media Sejahtera Tbk' },
  { symbol: 'JATI.JK', name: 'PT Informasi Teknologi Indonesia Tbk.' },
  { symbol: 'TYRE.JK', name: 'PT King Tire Indonesia Tbk.' },
  { symbol: 'MPXL.JK', name: 'PT MPX Logistics International Tbk' },
  { symbol: 'SMIL.JK', name: 'PT Sarana Mitra Luas Tbk' },
  { symbol: 'KLAS.JK', name: 'PT Pelayaran Kurnia Lautan Semesta Tbk' },
  { symbol: 'MAXI.JK', name: 'PT Maxindo Karya Anugerah Tbk' },
  { symbol: 'VKTR.JK', name: 'PT VKTR Teknologi Mobilitas Tbk' },
  { symbol: 'RELF.JK', name: 'PT Graha Mitra Asia Tbk.' },
  { symbol: 'CRSN.JK', name: 'PT Carsurin Tbk' },
  { symbol: 'GRPM.JK', name: 'PT Graha Prima Mentari Tbk.' },
  { symbol: 'WIDI.JK', name: 'PT Widiant Jaya Krenindo Tbk.' },
  { symbol: 'TGUK.JK', name: 'PT Platinum Wahab Nusantara Tbk.' },
  { symbol: 'INET.JK', name: 'PT Sinergi Inti Andalan Prima Tbk.' },
  { symbol: 'MAHA.JK', name: 'PT Mandiri Herindo Adiperkasa Tbk' },
  { symbol: 'RMKO.JK', name: 'PT Royaltama Mulia Kontraktorindo Tbk.' },
  { symbol: 'CNMA.JK', name: 'PT Nusantara Sejahtera Raya Tbk' },
  { symbol: 'FOLK.JK', name: 'PT Multi Garam Utama Tbk.' },
  { symbol: 'HBAT.JK', name: 'PT Minahasa Membangun Hebat Tbk' },
  { symbol: 'GRIA.JK', name: 'PT Ingria Pratama Capitalindo Tbk' },
  { symbol: 'PPRI.JK', name: 'PT Paperocks Indonesia Tbk.' },
  { symbol: 'ERAL.JK', name: 'PT Sinar Eka Selaras Tbk' },
  { symbol: 'CYBR.JK', name: 'PT ITSEC Asia Tbk.' },
  { symbol: 'LMAX.JK', name: 'PT Lupromax Pelumas Indonesia Tbk.' },
  { symbol: 'HUMI.JK', name: 'PT Humpuss Maritim Internasional Tbk' },
  { symbol: 'MSIE.JK', name: 'PT Multisarana Intan Eduka Tbk' },
  { symbol: 'RSCH.JK', name: 'PT Charlie Hospital Semarang Tbk.' },
  { symbol: 'BABY.JK', name: 'PT Multitrend Indo Tbk.' },
  { symbol: 'AEGS.JK', name: 'PT Anugerah Spareparts Sejahtera Tbk.' },
  { symbol: 'IOTF.JK', name: 'PT Sumber Sinergi Makmur Tbk' },
  { symbol: 'KOCI.JK', name: 'PT Kokoh Exa Nusantara' },
  { symbol: 'PTPS.JK', name: 'PT Pulau Subur Tbk.' },
  { symbol: 'STRK.JK', name: 'PT Lovina Beach Brewery Tbk.' },
  { symbol: 'LOPI.JK', name: 'PT Logisticsplus International Tbk' },
  { symbol: 'UDNG.JK', name: 'PT Agro Bahari Nusantara Tbk' },
  { symbol: 'RGAS.JK', name: 'PT Kian Santang Muliatama Tbk.' },
  { symbol: 'MSTI.JK', name: 'PT Mastersystem Infotama Tbk.' },
  { symbol: 'IKPM.JK', name: 'PT Ikapharmindo Putramas Tbk.' },
  { symbol: 'AYAM.JK', name: 'PT Janu Putra Sejahtera Tbk.' },
  { symbol: 'ASLI.JK', name: 'PT Asri Karya Lestari Tbk.' },
  { symbol: 'CGAS.JK', name: 'PT Citra Nusantara Gemilang Tbk.' },
  { symbol: 'MSJA.JK', name: 'PT Multi Spunindo Jaya Tbk.' },
  { symbol: 'SMLE.JK', name: 'PT Sinergi Multi Lestarindo Tbk' },
  { symbol: 'ACRO.JK', name: 'PT Samcro Hyosung Adilestari Tbk.' },
  { symbol: 'MANG.JK', name: 'PT Manggung Polahraya Tbk' },
  { symbol: 'GRPH.JK', name: 'PT Griptha Putra Persada Tbk.' },
  { symbol: 'SMGA.JK', name: 'PT Sumber Mineral Global Abadi Tbk' },
  { symbol: 'UNTD.JK', name: 'PT Terang Dunia Internusa Tbk.' },
  { symbol: 'TOSK.JK', name: 'PT Topindo Solusi Komunika Tbk.' },
  { symbol: 'MPIX.JK', name: 'PT Mitra Pedagang Indonesia Tbk.' },
  { symbol: 'ALII.JK', name: 'PT Ancara Logistics Indonesia Tbk' },
  { symbol: 'MKAP.JK', name: 'PT Multikarya Asia Pasifik Raya Tbk' },
  { symbol: 'MEJA.JK', name: 'PT Harta Djaya Karya Tbk' },
  { symbol: 'HYGN.JK', name: 'PT Ecocare Indo Pasifik Tbk.' },
  { symbol: 'BAIK.JK', name: 'PT Bersama Mencapai Puncak Tbk.' },
  { symbol: 'VISI.JK', name: 'PT Satu Visi Putra Tbk.' },
  { symbol: 'AREA.JK', name: 'PT Dunia Virtual Online Tbk' },
  { symbol: 'MHKI.JK', name: 'PT Multi Hanna Kreasindo Tbk' },
  { symbol: 'ATLA.JK', name: 'PT Atlantis Subsea Indonesia Tbk' },
  { symbol: 'DATA.JK', name: 'PT Remala Abadi Tbk' },
  { symbol: 'SOLA.JK', name: 'PT Xolare RCR Energy Tbk' },
  { symbol: 'BATR.JK', name: 'PT Benteng Api Technic Tbk' },
  { symbol: 'PART.JK', name: 'PT Cipta Perdana Lancar Tbk' },
  { symbol: 'ISEA.JK', name: 'PT Indo American Seafoods Tbk' },
  { symbol: 'BLES.JK', name: 'PT Superior Prima Sukses Tbk' },
  { symbol: 'GUNA.JK', name: 'PT Gunanusa Eramandiri Tbk' },
  { symbol: 'LABS.JK', name: 'PT UBC Medical Indonesia Tbk' },
  { symbol: 'DOSS.JK', name: 'PT Global Sukses Digital Tbk' },
  { symbol: 'NEST.JK', name: 'PT Esta Indonesia Tbk' },
  { symbol: 'PTMR.JK', name: 'PT Master Print Tbk' },
  { symbol: 'VERN.JK', name: 'PT Verona Indah Pictures Tbk' },
  { symbol: 'DAAZ.JK', name: 'PT Daaz Bara Lestari Tbk' },
  { symbol: 'BOAT.JK', name: 'PT Newport Marine Services Tbk' },
  { symbol: 'NAIK.JK', name: 'PT Adiwarna Anugerah Abadi Tbk' },
  { symbol: 'AADI.JK', name: 'PT Adaro Andalan Indonesia Tbk' },
  { symbol: 'MDIY.JK', name: 'PT Daya Intiguna Yasa Tbk' },
  { symbol: 'YOII.JK', name: 'PT Asuransi Digital Bersama Tbk' },
  { symbol: 'KSIX.JK', name: 'PT Kentanix Supra International Tbk' },
  { symbol: 'RATU.JK', name: 'PT Raharja Energi Cepu Tbk' },
  { symbol: 'YUPI.JK', name: 'PT Yupi Indo Jelly Gum Tbk' },
  { symbol: 'DGWG.JK', name: 'PT Dunia Gula Wisesa Tbk' },
  { symbol: 'EMAS.JK', name: 'PT Emas Mulia Abadi Tbk' },
  { symbol: 'JECX.JK', name: 'PT Jantra Eka Cemerlang Tbk' },
  { symbol: 'JELI.JK', name: 'PT Panca Anugrah Wisesa - INACO' },
  { symbol: 'CDIA.JK', name: 'PT Chandra Daya Investasi Tbk' },
  { symbol: 'RANS.JK', name: 'PT RANS Entertainment Indonesia Tbk' },
  { symbol: 'PJHB.JK', name: 'PT Pelayaran Jaya Hidup Bersama Tbk' },
];
