export const ARA_SCANNER_POLICY = {
  name: 'Algoritma ARA Internal Agent Speed',
  version: 'v0.3',
  lifecycle: ['RESEARCH_ONLY', 'EXPERIMENTAL', 'UNCALIBRATED'] as const,
  scoreName: 'ACS',
  scoreIsProbability: false,
  autoBuyAllowed: false,
  maxCandidates: 5,
  dataGate: {
    maxFutureSkewMinutes: 10,
    minimumAvailableWeight: 0.75,
    requiresCorporateActionAdjustment: true,
    requiresTradeableSecurity: true,
    requiresTraceableSourceAndTime: true,
    failure: { acs: null, action: 'NO_ACTION' as const },
  },
  formula: {
    expressionAsProvided: 'ACS = 100 x (0.15 x V + 0.20 x C + 0.20 x B + 0.10 x R + 0.05 x T + 0.10 x RS + 0.05 x S + 0.15 x K) - penalti',
    status: 'CONFIRMED' as const,
    penaltyUnit: 'ACS_POINTS' as const,
    reviewNote: 'Semua komponen adalah kontribusi positif. Hanya penalti rejection, failed breakout, dan kenaikan terlalu panjang yang dikurangi dari base ACS.',
    components: [
      { key: 'V', label: 'Volume expansion', weight: 0.15, detail: 'Volume aktual dibandingkan volume normal atau rata-rata.' },
      { key: 'C', label: 'Quality of close', weight: 0.20, detail: 'Posisi penutupan terhadap rentang harga harian; dekat high bernilai lebih besar.' },
      { key: 'B', label: 'Breakout quality', weight: 0.20, detail: 'Kekuatan dan persistensi breakout tanpa kegagalan atau rejection material.' },
      { key: 'R', label: 'Range expansion', weight: 0.10, detail: 'Ekspansi rentang harga yang mendukung pergerakan.' },
      { key: 'T', label: 'Turnover expansion', weight: 0.05, detail: 'Perubahan nilai transaksi relatif; bobot dibatasi karena berkorelasi dengan volume.' },
      { key: 'RS', label: 'Relative strength', weight: 0.10, detail: 'Kinerja saham dibandingkan IHSG atau benchmark relevan.' },
      { key: 'S', label: 'Supply condition', weight: 0.05, detail: 'Kualitas kondisi supply; rejection dan distribusi diterapkan sebagai penalti terpisah.' },
      { key: 'K', label: 'Verified catalyst', weight: 0.15, detail: 'Kualitas katalis terverifikasi, bukan rumor.' },
    ] as const,
    penalties: [
      { key: 'rejection', label: 'Rejection' },
      { key: 'failedBreakout', label: 'Failed breakout' },
      { key: 'multiDayExtension', label: 'Kenaikan terlalu panjang' },
    ] as const,
  },
  thresholds: [
    { min: 80, max: 100, label: 'HIGH' },
    { min: 65, max: 79, label: 'MODERATE-HIGH' },
    { min: 50, max: 64, label: 'WATCH' },
    { min: 0, max: 49, label: 'LOW' },
  ] as const,
  classifications: {
    continuation: [
      'Penutupan kuat dan dekat harga tertinggi',
      'Breakout bersih serta bertahan',
      'Volume dan nilai transaksi meningkat',
      'Relative strength positif',
      'Katalis terverifikasi',
      'Tidak ada rejection atau distribusi material',
      'Saham masih layak diperdagangkan',
    ],
    exhaustion: [
      'Upper wick atau rejection kuat',
      'Breakout gagal',
      'Distribusi atau tekanan jual meningkat',
      'Kenaikan beberapa hari sudah terlalu jauh',
      'Likuiditas menurun',
      'Harga gagal mempertahankan level penting',
    ],
    exhaustionActions: ['WAIT', 'AVOID_CHASING', 'NO_ACTION'] as const,
  },
  investabilityOrder: ['Kualitas continuation', 'Investability', 'ACS'] as const,
  investabilityChecks: [
    'Likuiditas',
    'Spread',
    'Kedalaman bid-offer',
    'Slippage',
    'Status suspensi/UMA',
    'Free float',
    'Aksi korporasi',
    'Risiko governance',
    'Kelayakan entry dan exit',
  ] as const,
  decisionGates: [
    'Quant/Data',
    'Fundamental dan valuasi',
    'Trader/teknikal',
    'Makro dan sektor',
    'Bear/Risk Reviewer',
    'Portfolio fit',
  ] as const,
  finalOutcomes: ['EKSEKUSI', 'PANTAU', 'TOLAK_ATAU_DIAM'] as const,
  riskReviewerCanVeto: true,
  prohibitions: [
    'Menganggap ACS sebagai probabilitas kenaikan',
    'Menghasilkan BUY otomatis',
    'Mengejar saham yang sudah ARA',
    'Mengarang order book, volume, katalis, atau harga',
    'Menggunakan data stale sebagai kondisi live',
    'Menganggap input yang tidak tersedia sebagai netral',
    'Mengubah sinyal SahamLens menjadi keputusan tanpa evaluasi independen',
    'Mengirim lebih dari lima kandidat',
  ] as const,
} as const;

export type AraScannerPolicy = typeof ARA_SCANNER_POLICY;
